ministryofjustice/hmpps-book-secure-move-api

app/services/ethnicities/importer.rb, spec/services/ethnicities/importer_spec.rb
Just one hidden ethnicity for now - 'MERGE'
=> [P4-557] Create a list of Hidden ethnicities and disable at import time

config/initializers/prometheus_exporter.rb, config/puma.rb
This change adds per-process memory metrics
=> [P4-443] Extend metrics from prometheus exporter

app/controllers/api/v1/moves_controller.rb, app/models/move.rb, app/serializers/move_serializer.rb, config/database.yml, db/migrate/20190828102621_add_cancellation_reason_and_comment_to_moves.rb, db/schema.rb, spec/factories/move.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/requests/api/v1/moves_controller_update_spec.rb, swagger/v1/move.json
FIX https://dsdmoj.atlassian.net/browse/P4-631
- Adds properties `cancellation_reason` and `cancellation_reason_comment`
- `database.yml` uses `DB_USERNAME` environment variable
=> Added cancellation reason and comment, configurable DB_USERNAME

swagger/v1/swagger.json
Updates the assessment question summary.
=> Fix assessment question description

app/controllers/api/v1/moves_controller.rb, lib/tasks/fake_data.rake, spec/requests/api/v1/moves_controller_show_spec.rb
As in https://dsdmoj.atlassian.net/browse/P4-569
Retrieves moves on /show
There was a minor bug in the rake to populate the db with fake data.
=> Retrieves data on show + corrected fake_data gen

README.md, app/controllers/api/v1/moves_controller.rb, app/lib/nomis_client/alerts.rb, app/lib/nomis_client/moves.rb, app/lib/nomis_client/people.rb, app/services/moves/anonymiser.rb, app/services/people/anonymiser.rb, lib/tasks/fake_data.rake, lib/tasks/nomis_fixtures.rake, spec/lib/nomis_client/alerts_spec.rb, spec/lib/nomis_client/moves_spec.rb, spec/lib/nomis_client/people_spec.rb, spec/requests/api/v1/moves_controller_show_spec.rb, spec/services/moves/anonymiser_spec.rb, spec/services/people/anonymiser_spec.rb
Solves ticket https://dsdmoj.atlassian.net/browse/P4-652
=> NomisClient now anonymises data when in test_mod

app/lib/nomis_client/personal_care_needs.rb, spec/fixtures/files/nomis_get_personal_care_needs_200.json
Also need to handle (non-standard?) response (Hash not an Array).
=> [P4-708] Add a `type` parameter to the PersonalCareNeeds URL

app/services/moves/importer.rb, spec/services/moves/importer_spec.rb
Most of the mapping logic was already in place for this
=> [P4-669] Ensure that `Move#status` is imported from NOMIS

Gemfile.lock, app/controllers/api/v1/moves_controller.rb, app/services/moves/params_validator.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/services/moves/params_validator_spec.rb, swagger/v1/get_moves_responses.json
Fixes https://dsdmoj.atlassian.net/browse/P4-701
=> Validator for move params

README.md, app/models/supplier.rb, db/fixtures/suppliers.yml, db/migrate/20191002101831_create_suppliers.rb, db/schema.rb, lib/tasks/reference_data.rake, spec/factories/suppliers.rb, spec/models/supplier_spec.rb
Supplier model.
Seed development/staging/production data with:
`$~ bundle exec rake db:insert_suppliers`
=> Supplier model + data seeding

app/controllers/api/v1/moves_controller.rb, app/models/location.rb, app/models/supplier.rb, db/migrate/20191007150340_create_locations_suppliers.rb, db/schema.rb, spec/factories/move.rb, spec/models/location_spec.rb, spec/models/supplier_spec.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/services/moves/finder_spec.rb, swagger/v1/swagger.json
Soves https://dsdmoj.atlassian.net/browse/P4-725 by adding a many to many relationship between locations and suppliers
=> Add habtm locations-suppliers

app/controllers/api/v1/reference/locations_controller.rb, app/services/locations/finder.rb, spec/requests/api/v1/reference/locations_controller_spec.rb, swagger/v1/swagger.json
Solves https://dsdmoj.atlassian.net/browse/P4-731 by adding a filter on `reference/locations` that accepts `supplier_ids`.
=> locations accept filter supplier_ids

swagger/v1/swagger.json
Documentation I previously forgot
=> Documentation for /reference/supplier*

app/controllers/api/v1/reference/locations_controller.rb, app/serializers/location_serializer.rb, app/services/locations/finder.rb, db/migrate/20191007150340_create_locations_suppliers.rb, db/schema.rb, spec/requests/api/v1/reference/locations_controller_spec.rb, spec/serializers/location_serializer_spec.rb, spec/services/locations/finder_spec.rb, swagger/v1/swagger.json
Includes suppliers in reference/location* output
=> Adding suppliers to locations output

lib/tasks/reference_data.rake
```
bundle exec rake reference_data:link_suppliers
```
=> Creating references between locations and suppliers

app/controllers/api/v1/people_controller.rb, app/services/people/finder.rb, config/routes.rb, spec/factories/profile.rb, spec/requests/api/v1/people_controller_index_spec.rb, spec/services/people/finder_spec.rb, swagger/v1/get_people_responses.json
Fixes https://dsdmoj.atlassian.net/browse/P4-740 by adding a `/people?police_national_computer=$PNC` endpoint
=> police national computer filter

Gemfile, Gemfile.lock, config/initializers/faraday.rb
Add keepalive connections as per https://dsdmoj.atlassian.net/browse/P4-769
=> Add keepalive connections

app/models/move.rb, app/services/moves/importer.rb, app/services/moves/sweeper.rb, db/migrate/20191023104425_add_moves_nomis_event_ids.rb, db/schema.rb, lib/tasks/data_maintenance.rake, spec/models/move_spec.rb, spec/requests/api/v1/moves_controller_update_spec.rb, spec/services/moves/importer_spec.rb, spec/services/moves/sweeper_spec.rb, swagger/v1/swagger.json
Attempts to fix https://dsdmoj.atlassian.net/browse/P4-765
Includes previously forgotten swagger documentation.
=> P4 765 updated sync logic for nomis

app/services/moves/sweeper.rb, spec/services/moves/sweeper_spec.rb
HOTFIX for wrong moves state changes
=> Fixing mass moves cancellation

app/lib/nomis_client/alerts.rb, app/lib/nomis_client/base.rb, app/lib/nomis_client/people.rb, app/services/moves/importer.rb, spec/fixtures/files/nomis_post_alerts_200.json, spec/lib/nomis_client/alerts_spec.rb, spec/lib/nomis_client/people_spec.rb, spec/services/moves/importer_spec.rb
Closes https://dsdmoj.atlassian.net/browse/P4-786
Batches calls to import alerts
=> Batching calls for /alerts/

lib/tasks/reference_data.rake
Found code by running the importer in https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/167, and using:
```
Location.where(title: "Bishopsgate Police Station")
```
=> Add Bishopsgate police custody to Serco supplier reference data

lib/tasks/reference_data.rake
Partially resolves https://dsdmoj.atlassian.net/browse/P4-811.
This PR also refactors the block slightly to 1-line-per-location, to aid readability as we add more locations.
Once this PR is merged we need to:
1. Deploy to production
2. Run the `reference_data:link_suppliers` rake task on all environments
3. Flush Redis on all environments
=> Add GeoAmey locations for rollout on Monday

lib/tasks/reference_data.rake
For https://dsdmoj.atlassian.net/browse/P4-811
Heathrow Custody -> Heathrow Police Station, MPS23
Charing Cross -> Charing Cross Police Station, MPS18
Thorpe Wood Custody Suite -> Thorpe Wood Custody Suite, CAM5
Parkside Custody Suite -> Cambridge (Parkside) Police Station, CAM1
Huntingdon Custody Suite -> Huntingdon Police Station, CAM3
March Custody Suite -> March Police Station, CAM4
=> Add Serco locations for Weds 4th December

app/serializers/document_serializer.rb, app/serializers/move_serializer.rb, config/storage.yml, spec/serializers/document_serializer_spec.rb
Adds S3 configuration and the filesize to the serializer.
=> S3 configuration and filesize

Gemfile, Gemfile.lock
=> ActiveStorage need S3 gem

app/serializers/document_serializer.rb, config/environments/development.rb, config/environments/production.rb
Attempt to fix S3 configuration
=> S3 works locally

lib/tasks/reference_data.rake
This PR sorts the GEOAmey locations in our reference Rake task, and adds `NRU1` and `NRU4` locations for P4-869.
=> P4 869 additional suppliers

lib/tasks/reference_data.rake
This PR resolves P4-873 by adding the remaining custody suites for the GEOAmey January rollout
=> P4-873 adds remaining 28 custody suites for GEOAmey

app/lib/nomis_client/moves.rb, app/services/alerts/importer.rb, app/services/moves/importer.rb, app/services/moves/nomis_synchroniser.rb, app/services/people/importer.rb, app/services/personal_care_needs/importer.rb, spec/factories/assessment_question.rb, spec/lib/nomis_client/moves_spec.rb, spec/models/assessment_question_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/services/moves/importer_spec.rb, spec/services/moves/nomis_synchroniser_spec.rb
Expanded importer test to cover more scenarios with fewer mock components
=> P4 876 synch wrong personal care record

.circleci/config.yml, .rubocop.yml, Gemfile, Gemfile.lock, app/controllers/api/v1/documents_controller.rb, app/controllers/api/v1/reference/suppliers_controller.rb, app/controllers/api_controller.rb, app/lib/nomis_client/alerts.rb, app/lib/nomis_client/base.rb, app/lib/nomis_client/moves.rb, app/lib/nomis_client/people.rb, app/models/location.rb, app/models/profile/assessment_answer.rb, app/services/alerts/anonymiser.rb, app/services/alerts/importer.rb, app/services/moves/importer.rb, app/services/nomis_alerts/importer.rb, app/services/people/anonymiser.rb, app/services/personal_care_needs/importer.rb, lib/tasks/fake_data.rake, lib/tasks/reference_data.rake, lib/tasks/rubocop.rake, spec/factories/documents.rb, spec/lib/nomis_client/moves_spec.rb, spec/requests/api/v1/documents_controller_create_spec.rb, spec/services/moves/importer_spec.rb
Part of the challenge here is that Rubocop can't count method lines
=> implement GDS rubocop standards 

config/environments/preprod.rb, config/environments/production.rb, config/environments/staging.rb
P4-878 set hostname from ENV var to fix broken ActiveStorage URL generation
=> P4-878 set hostname from ENV var

config/environments/preprod.rb, config/environments/production.rb, config/environments/staging.rb
Removed default_path for action_mailer
=> Remove action_mailer default_host

app/controllers/api/v1/documents_controller.rb, spec/requests/api/v1/documents_controller_access_spec.rb, spec/requests/api/v1/documents_controller_destroy_spec.rb, swagger/v1/swagger.yaml
Moves are now fully editable and updatable given the application is linked to the right supplier
=> Documents follow moves' permissions

.gitignore, Dockerfile, swagger/v1/swagger.yaml
Reverts the swagger YAML changes due to complications with circle generating swagger docs
=> Revert swagger yaml

app/services/assessment_questions/importer.rb, spec/services/assessment_questions/importer_spec.rb
Added special vehicle assessment question
https://dsdmoj.atlassian.net/browse/P4-926
=> added special vehicle assessment question

app/services/moves/finder.rb, lib/tasks/fake_data.rake, spec/services/moves/finder_spec.rb, spec/swagger/definitions/hand_coded_paths.json, swagger/v1/swagger.yaml
Update moves API to support mutiple move status values from filter
=> P4 915 multiple status values

app/lib/nomis_client/moves.rb, app/models/profile/assessment_answer.rb, spec/lib/nomis_client/moves_spec.rb, spec/rails_helper.rb
sync completed moved by setting movements=true in NOMIS API calls
=> P4 922 sync completed moves

.circleci/config.yml, .env.example, app/models/subscription.rb, app/services/encryptor.rb, db/migrate/20200205151906_make_subscription_secret_encrypted.rb, db/schema.rb, spec/models/subscription_spec.rb, spec/services/encryptor_spec.rb, swagger/v1/swagger.yaml
Encrypts secrets.
ENV variables must be added to the .env file: `SECRET_KEY_BASE` and `ENCRYPTOR_SALT`.
I've generated my own key_base with `rake secret` and the salt with https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/P4-951_storing-secrets/spec/services/encryptor_spec.rb#L9
=> Encryptor + encrypted_secret

spec/rails_helper.rb
Add comment explaining the purpose of the mininum percentage and tighten threshold
=> add comment about coverage percentage

app/controllers/api/v1/documents_controller.rb, app/models/document.rb, config/routes.rb, db/migrate/20200207111034_remove_documents_move_constraint.rb, db/schema.rb, spec/requests/api/v1/documents_controller_create_spec.rb, spec/swagger/definitions/document.json, spec/swagger/definitions/post_document_responses.json, spec/swagger_helper.rb
It is now possible to POST to /documents and create a Document without a move
=> POST /documents to upload a document without a move

app/services/moves/importer.rb
Remove duplicate save! call on profile when importing people
=> remove duplicated profile save during move imports

app/serializers/notification_serializer.rb, spec/factories/notification.rb, spec/serializers/notification_serializer_spec.rb
=> notification serialization

lib/tasks/reference_data.rake
=> Adding portsmouth to geoamey

.circleci/config.yml
This should *hopefully* deploy the api to the sidekiq pods, as well to the api pods.
https://dsdmoj.atlassian.net/browse/P4-1057
=> Use CircleCI to deploy to sidekiq pods

spec/rails_helper.rb
increased coverage_drop based on experience
=> added new improved coverage numbers

app/views/layouts/_links.html.md, app/views/layouts/application.html.erb, app/views/pages/authentication.html.md, app/views/pages/contributing.html.md, app/views/pages/feedback.html.md, app/views/pages/overview.html.erb, app/views/pages/webhooks.html.md
This is initial documentation for webhooks notifications
=> P4 1038 webhooks documentation

Dockerfile, app/controllers/application_controller.rb
Added asset pipeline to support P4-999 in staging
=> Run asset pipeline in dockerfile

app/serializers/document_serializer.rb, app/serializers/move_serializer.rb, spec/requests/api/v1/documents_controller_destroy_spec.rb, spec/requests/api/v1/moves_controller_destroy_spec.rb, spec/requests/api/v1/moves_controller_role_access_spec.rb, spec/serializers/document_serializer_spec.rb, spec/swagger/definitions/document.json, spec/swagger/definitions/get_move_responses.json, spec/swagger/definitions/hand_coded_paths.json, spec/swagger/definitions/location_reference.json, spec/swagger/definitions/move.json, spec/swagger/definitions/person_reference.json, swagger/v1/assessment_answer.json, swagger/v1/document.json, swagger/v1/ethnicity.json, swagger/v1/ethnicity_reference.json, swagger/v1/gender.json, swagger/v1/gender_reference.json, swagger/v1/identifier_type.json, swagger/v1/location.json, swagger/v1/location_reference.json, swagger/v1/move.json, swagger/v1/nationality.json, swagger/v1/pagination.json, swagger/v1/pagination_links.json, swagger/v1/person.json, swagger/v1/person_reference.json, swagger/v1/supplier.json
Fixup a number of documentation anomalies, and fixed a couple of minor bugs 
e.g. when to_location not present in a move, don't serialize the to_location field
=> P4 983 documentation anomalies

app/models/move.rb, spec/models/move_spec.rb
remove validation for move_agreed and move_agreed_by
=> Removed validation for move_agreed and move_agreed_by

app/services/assessment_questions/importer.rb, spec/services/assessment_questions/importer_spec.rb
Ticket: https://dsdmoj.atlassian.net/browse/P4-1079
This PR add a new assessment questions for Not For Release
=> P4 1079 new assessment question for nfr

app/serializers/person_serializer.rb, spec/requests/api/v1/people_controller_index_spec.rb
Fixes P4-1099
- Return correct data if ethnicity is missing
- perform a person search on staging with nomis id A5021DY
=> p4-1099 missing ethnicity bad JSON response

Dockerfile
Fixes P4-982
- tweak to Dockerfile missed during story
- deploy to staging
=> P4-982 fix dockerfile issue

spec/factories/location.rb, spec/factories/profile.rb, spec/serializers/location_serializer_spec.rb, spec/serializers/move_serializer_spec.rb, spec/serializers/person_serializer_spec.rb, spec/services/moves/reference_generator_spec.rb
Add Faker data to locations and profiles to help testing
=> add faker data to locations and profiles

db/migrate/20200302095515_remove_superfluous_index.rb, db/schema.rb
=> P4-1117 remove superfluous index as it causes crashes

.gitignore, Dockerfile, Gemfile, Gemfile.lock, config/application_insights.erb, run.sh
Fixes P4-982
- Put back Azure App Insights
- Perform any API call (e.g. by clicking around front-end) and check that app insights
=> P4 982 azure app insights redux

spec/factories/document.rb, spec/factories/move.rb, spec/services/moves/finder_spec.rb
Factory + test tweak to allow 'date' field on move to no longer have a fixed value
=> add variable 'date' field in move factory

.rubocop.yml, app/controllers/api/v1/moves_controller.rb, app/models/location.rb, app/models/prison_transfer_reason.rb, app/models/profile.rb, app/services/moves/finder.rb, app/services/moves/params_validator.rb, spec/factories/location.rb, spec/factories/move.rb, spec/factories/prison_transfer_reason.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/requests/api/v1/moves_controller_sorting_spec.rb, spec/serializers/move_serializer_spec.rb, spec/serializers/prison_transfer_reason_serializer_spec.rb, spec/services/moves/finder_spec.rb, spec/services/moves/params_validator_spec.rb, spec/services/moves/reference_generator_spec.rb, spec/swagger/definitions/hand_coded_paths.json
Fixes P4-1123
- Adds sort -> by and direction to moves index action
- test out sort parameters in postman or swagger
=> P4-1123 adding sort_by to moves#index

.rubocop.yml, app/controllers/api/v1/people_controller.rb, app/lib/nomis_client/image.rb, app/models/image.rb, app/models/person.rb, app/serializers/image_serializer.rb, app/serializers/person_serializer.rb, app/services/people/retrieve_image.rb, config/routes.rb, spec/models/person_spec.rb, spec/requests/api/v1/documents_controller_create_spec.rb, spec/requests/api/v1/people_controller_image_spec.rb, spec/requests/api/v1/people_controller_index_spec.rb, spec/swagger/api/v1/people_controller_image_spec.rb
Jira: https://dsdmoj.atlassian.net/browse/P4-1143
When the Image is retrieved from Nomis, it store it on S3 and return the URL
call the API get `/people/person_id/image`
=> Save picture in S3 and return S3 URL

.circleci/config.yml, .gitignore, Dockerfile, Gemfile, Gemfile.lock, config/application_insights.erb, run.sh
Fixes P4-1090
- use a new base image for the app, as we were using an outdated MoJ image. Activate AppInsights on staging, preprod and production
- Browse environment, and check matching Azure App Insights data
=> P4 1090 send azure events

.circleci/config.yml
This reverts commit 6b3a8b68ddd7d8be1a8ee751925ec01926d1a4a7.
Reverts accidental push done to master.
=> Revert "use vendor/bundle for bundler"

.circleci/config.yml
Relates to P4-1200
- push to new 'dev' environment in circle
- check that new 'dev' env gets pushed when this branch is built.
=> support new 'dev' environment

.env.example, config/initializers/gov_uk_notify.rb, spec/mailer/move_mailer_spec.rb
Fixes P4-1211
Adds a GOVUK_NOTIFY_ENABLED flag which should only be set on Sidekiq containers
- TODO
=> Add GOVUK_NOTIFY_ENABLED flag

app/mailers/move_mailer.rb, spec/mailer/move_mailer_spec.rb
Fixes P4-1188
Display 'N/A' if the To-location is nil. Text agreed with Jason.
Demo email:
=> P4-1188-tweaks

spec/swagger/api/v1/people_controller_court_cases_spec.rb
=> id -> person_id

app/controllers/api/v1/moves_controller.rb, app/serializers/court_hearing_serializer.rb, db/migrate/20200407141146_create_court_hearings.rb, db/schema.rb, spec/factories/court_hearings.rb, spec/requests/api/v1/moves_controller_create_spec.rb, spec/serializers/person_serializer_spec.rb, spec/services/moves/create_court_hearings_spec.rb, spec/swagger/definitions/court_hearing.json, swagger/v1/court_hearing.json
- Change court_type -> case_type
=> court_type -> case_type

.rubocop.yml, app/lib/nomis_client/court_hearing.rb, app/services/court_hearings/create_in_nomis.rb, spec/lib/nomis_client/court_hearings_spec.rb, spec/services/court_hearings/create_in_nomis_spec.rb
Jira ticket: P4-1165
This PR adds a service that allow to create Court Hearing in Nomis.
=> Add service CreateHearingInNomis

app/controllers/api/v1/court_hearings_controller.rb, app/services/court_hearings/create_in_nomis.rb, spec/requests/api/v1/court_hearings_controller_create_spec.rb, spec/services/court_hearings/create_in_nomis_spec.rb
Jira: P4-1308-nomis-prison-to-court
This PR allows the hearing court to be created in nomis.
=> Call the service to create court hearings in Nomis

db/migrate/20200416101454_rename_court_type_to_case_type_in_court_hearing.rb, db/schema.rb
- Fixes broken migration after moving from court_type -> case_type https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/363
=> Fixes migration after change to db column

app/lib/nomis_client/court_hearing.rb
Add log for court hearing in case of success
=> Add log for court hearing in case of success

spec/swagger/definitions/court_hearing.json, swagger/v1/court_hearing.json
Add some clarity on description of move relationship and how it is required to create a Hearing in Nomis
=> Update swagger doc to explain need for move to create a nomis hearing

app/controllers/api/v1/court_hearings_controller.rb, app/lib/nomis_client/court_hearing.rb
related to jira: https://dsdmoj.atlassian.net/browse/P4-1308
Add sentry log if move is missing.
=> Add sentry log if move is missing

app/controllers/api/v1/court_hearings_controller.rb, app/lib/nomis_client/court_hearing.rb, app/services/court_hearings/create_in_nomis.rb, spec/requests/api/v1/court_hearings_controller_create_spec.rb
[P4-1308](https://dsdmoj.atlassian.net/browse/P4-1308)
- The api is broken
=> Fix nomis integration

lib/tasks/data/supplier_locations.yml
https://dsdmoj.atlassian.net/browse/P4-1337
Link Nottingham (Prison) to Geoamey (Supplier) and Link Thameside (Prison) to Serco (Supplier)
=> Update supplier locations

app/controllers/api/v1/people_controller.rb, app/lib/nomis_client/court_cases.rb, app/services/people/retrieve_court_cases.rb, spec/lib/nomis_client/court_cases_spec.rb, spec/requests/api/v1/people_controller_court_cases_spec.rb, spec/services/people/retrieve_court_cases_spec.rb, spec/swagger/api/v1/people_controller_court_cases_spec.rb
[P4-1264](https://dsdmoj.atlassian.net/browse/P4-1264)
- This is a required feature by the frontend in future and enables easily adding additional filters.
=> [P4-1264] Court case filters

CHANGELOG.md
=> updating changelog to 1.8.1

app/controllers/api/v1/allocations_controller.rb, config/routes.rb, spec/factories/allocation_complex_case.rb, spec/requests/api/v1/allocations_controller_create_spec.rb, spec/swagger/definitions/hand_coded_paths.yaml, spec/swagger_helper.rb, swagger/v1/allocation.yaml, swagger/v1/post_allocations_responses.yaml
P4-1284
- Required to support Front end allocations work
- This is a new endpoint, so no risk to deployment
=> P4-1284 create allocation

spec/requests/api/v1/moves_controller_update_spec.rb
=> Fix flaky spec

swagger/v1/court_hearing_reference.yaml
This is the accurate form of the reference
=> A move can have many court hearings

app/controllers/api/v1/people_controller.rb, app/services/moves/import_people.rb, spec/requests/api/v1/people_controller_index_spec.rb, spec/services/moves/import_people_spec.rb
`Moves::ImportPeople` is spaghetti 🍝  code,
I need to work on that part at the moment,  so this is just a mini step to clean it up with minimal risk.
=> Small improvement for Moves::ImportPeople. More need to be done!

app/lib/nomis_client/personal_care_needs.rb, app/models/profile/assessment_answer.rb, app/services/personal_care_needs/importer.rb, spec/factories/assessment_question.rb, spec/models/profile/assessment_answer_spec.rb, spec/services/personal_care_needs/importer_spec.rb
P4-1185
We create AssessmentAnswers which indicate needs of offenders during a move. These AssessmentAnswers are populated by attributes coming from two places:
1. `AssessmentQuestions` imported from a static list: https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/c3911d5914c43f85e7a81a1d1a135aeebd3cac77/app/services/assessment_questions/importer.rb#L5-L23
2. Either `Alerts` (pulled from Nomis) or `PersonalCareNeeds` (also pulled from Nomis)
The purpose of this PR is to extend the filtered domains that we return personal care needs for and correctly associate a personal care need with a relevant question (to pull out it's attributes, see above) - especially interesting for us are special vehicle needs key on the question, which the frontend are interested in.
These will …
=> [P4-1185] adds special vehicle to personal care needs

app/controllers/api/v1/court_hearings_controller.rb
P4-<TODO>
Reduce noisy and incorrect messaging when we do not save to Nomis.
=> Log Nomis court hearing saving result

app/controllers/api/v1/moves_controller.rb, app/models/move.rb, app/models/person.rb, app/models/profile.rb, app/serializers/move_serializer.rb, app/services/court_hearings/create_in_nomis.rb, app/services/moves/finder.rb, lib/tasks/move_profile.rake, spec/factories/move.rb, spec/jobs/prepare_person_notifications_job_spec.rb, spec/models/move_spec.rb, spec/requests/api/v1/moves_controller_create_spec.rb, spec/requests/api/v1/moves_controller_destroy_spec.rb, spec/requests/api/v1/moves_controller_sorting_spec.rb, spec/requests/api/v1/moves_controller_update_spec.rb, spec/serializers/move_serializer_spec.rb, spec/services/court_hearings/create_in_nomis_spec.rb, spec/services/moves/reference_generator_spec.rb, spec/services/people/retrieve_image_spec.rb
This reverts commit 7436fd4e9fbff93e62f5a8ebcdada42c82d9da2b.
=> Revert "Add profile relationship to Move (#432)"

app/controllers/api/v1/moves_controller.rb, app/models/move.rb, lib/tasks/data_maintenance.rake, spec/models/location_spec.rb, spec/models/move_spec.rb, spec/requests/api/v1/moves_controller_filter_spec.rb, spec/requests/api/v1/moves_controller_index_spec.rb, spec/requests/api/v1/moves_controller_sorting_spec.rb, spec/requests/api/v1/moves_controller_update_cancellation_reason_spec.rb, spec/requests/api/v1/moves_controller_update_spec.rb, spec/services/moves/finder_spec.rb, swagger/v1/get_moves_responses.yaml, swagger/v1/move.yaml
[P4-1469](https://dsdmoj.atlassian.net/browse/P4-1469)
- new reasons are required by the FE
=> P4-1469 new cancellation reason

CHANGELOG.md
Updating the change log to v1.10.0
=> V1.10.0 Update CHANGELOG.md

lib/tasks/move_profile.rake, lib/tasks/reference_data.rake
- Remove the long noisy output of rake `link_suppliers`
- Add some useful output to check the rake progression in `create_all`
=> Clean up rake tasks reference_data

CHANGELOG.md
=> V1.10.3 Update CHANGELOG.md

app/controllers/api/v2/people_controller.rb, app/serializers/v2/person_serializer.rb, app/serializers/v2/profile_serializer.rb, app/services/v2/people/finder.rb, app/services/v2/people/include_params_validator.rb, config/routes.rb, spec/requests/api/v1/people_controller_index_spec.rb, spec/requests/api/v2/people_controller_index_spec.rb, spec/serializers/v2/person_serializer_spec.rb, spec/serializers/v2/profile_serializer_spec.rb, spec/services/v2/people/finder_spec.rb, spec/services/v2/people/include_params_validator_spec.rb, spec/support/json_schemas.rb, swagger/v2/get_people_responses.yaml, swagger/v2/person.yaml, swagger/v2/profile.yaml
https://dsdmoj.atlassian.net/browse/P4-1493
Add api/V2/people endpoint
API docs are updated in a different PR, to keep this PR clean.
We are going to have a new set of endpoint having a clear separation between People and Profile.
No risk, the new endpoint will not change the behaviour of the old endpoints.
=> Add GET /api/v2/people

.circleci/config.yml
[[P4-1631]](https://dsdmoj.atlassian.net/browse/P4-1631)
- It makes it easier and cleaner to define the CI job's environments. 
- It speeds up tests a lot! 
This PR just affects the workflow up to the PR stage, the rest keep fairly the same. The deployment approach will be changed in part-2, making this one lower risk and simpler to review.
=> [P4-1631] Streamline Pipeline "Part I - Divide and Conquer"

app/controllers/api/v1/allocations_controller.rb, app/serializers/allocation_serializer.rb, spec/requests/api/v1/allocations_controller_index_spec.rb
Not 100% sure if this is right, will be ideal if this can be tested against the front end.
P4-<TODO>
-
-
-
=> Hotfix returned allocation relationships for index view

app.json
Without redis the notifier sidekiq jobs fail, so some of the endpoints to create data fail with a 500 error.
P4-<TODO>
-
-
-
=> Add redis addon for heroku review apps

app/models/move.rb, spec/models/move_spec.rb
=> HOTFIX: ignore nil profiles when fetching documents

.circleci/config.yml, Dockerfile, k8s_migrate_job.yml, run.sh
[P4-586](https://dsdmoj.atlassian.net/browse/P4-586)
[P4-1168](https://dsdmoj.atlassian.net/browse/P4-1168)
- We want to stop running migration every time each instance of the container (re)starts
- It could prevent a deployment from being executed.
=> [P4-586] Run migrations out of band

.circleci/config.yml
N/A
- It prevents a step from running
=> Fix typo in macro

lib/tasks/fake_data.rake
Fixes fake data that was missed during dereferencing a profile
=> Fix fake data

app/controllers/api_controller.rb, spec/requests/api/people_controller_create_v2_spec.rb
https://dsdmoj.atlassian.net/browse/P4-1666
Add 415 error in case the API version in the header is wrong.
To add error check in the version supported.
=> Add 415 http error if version in not supported.

lib/routing_filter/versioned_path.rb
=> Handle swagger v1 routes

.circleci/config.yml
P4-1722
- We introduced a new environment and we need a way to deploy onto it.
=> Add the new UAT environment  to the pileine.

config/initializers/active_storage.rb
https://dsdmoj.atlassian.net/browse/P4-1558
This is an attempt to make urls expire in n minutes.
For security reasons we must not create permanent url.
=> Set service_urls_expire_in to 5 min

app/controllers/api/court_hearings_controller.rb, app/services/court_hearings/create_in_nomis.rb
P4-1786
I am struggling to see any issues locally and this will make it easier to discover the time issue.
=> [P4-1786] Instrument court hearing creation for easier reproduction and debug

lib/tasks/create_application.rake
[P4-1796](https://dsdmoj.atlassian.net/browse/P4-1796)
- it was broken
=> Fix create_application.rake

app/controllers/api/court_hearings_controller.rb
P4-1786
Adds more logging for debugging court hearing times
More information about what the frontend is sending
=> [P4-1786] Log court hearing params

app/serializers/v2/move_serializer.rb, spec/swagger/swagger_doc_v2.yaml
=> Tidy up document swagger

lib/tasks/journeys_report.rake
P4-1768
- It's the first step of the reporting tool, upload a basic the report to S3 to validate the workflow
-
-
=> [P4-1768] Moves report task

app/models/move.rb, spec/models/move_spec.rb
Bugfix
This PR fixes the Move uniqueness error
=> Fix for Move uniqueness

Gemfile, config/application_insights.erb, config/environments/production.rb, config/environments/test.rb, config/initializers/lograge.rb
P4-1797
I've been reverse engineering how we do logging and automatically linting various files.
- Lint some files
- Remove some redundant configuration
This PR will remove noise when I come to make real changes.
=> [P4-1797] Tidy up config files

lib/tasks/data/supplier_locations.yml
P4-1862
Add Westminster Magistrates Court to Serco
=> P4-1862 Add CITWMC to serco

lib/tasks/fake_data.rake, lib/tasks/journeys_report.rake
P4-1788
- [ ] Remapped location id  to nomis_agency_id 
- [ ] Added `supplier` to the Journey object 
- I'm converging the report functionality with the requirements.
=> [P4-1788] Further field re-mapping

lib/tasks/journeys_report.rake
P4-1788
- In staging we have some data quality issues. So this is to protect against those cases
=> Watch out for moves with null profiles

swagger/v1/post_move_accept.yaml
=> Fix typo in swagger docs

spec/requests/api/moves_controller_create_spec.rb
Fix the URL matcher to make spec stable.
=> Fix the URL matcher to make spec stable.

CHANGELOG.md, spec/swagger/swagger_doc_v2.yaml, swagger/v1/allocation.yaml, swagger/v1/allocation_complex_case.yaml, swagger/v1/court_case.yaml, swagger/v1/court_hearing.yaml, swagger/v1/document.yaml, swagger/v1/errors.yaml, swagger/v1/ethnicity.yaml, swagger/v1/gender.yaml, swagger/v1/get_people_responses.yaml, swagger/v1/move.yaml, swagger/v1/person.yaml, swagger/v1/prison_transfer_reason.yaml, swagger/v1/profile.yaml, swagger/v1/region.yaml, swagger/v1/supplier.yaml, swagger/v1/timetable_entry.yaml, swagger/v2/get_people_responses.yaml, swagger/v2/move.yaml, swagger/v2/person.yaml, swagger/v2/post_people_responses.yaml
https://dsdmoj.atlassian.net/browse/P4-1880
- Make id not a required attribute everywhere
- Add a comment in the description to explain that the id field in requests is typically filled in via the path and isn't required in the request body
- It adds missing endpoints to the documentation
- It fixes wrong params/responses
- I add error status/descriptions
- Fixes broken schemas for personal identifiers on person v2
To make API Users happy 😄
=> Improve V2 API swagger Doc

lib/tasks/journeys_report.rake
[P4-1876](https://dsdmoj.atlassian.net/browse/)
- Addressing a requirements 
=> Further report field mapping

app/services/frameworks/question.rb, spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-professional-referral.yml, spec/services/frameworks/question_spec.rb
We should be able to pull in questions without validation, default
to empty array if no validation available
=> Fix Framework importer

app/models/ability.rb, app/models/move.rb, spec/models/ability_spec.rb, spec/models/move_spec.rb, spec/requests/api/journeys_controller_create_spec.rb, spec/requests/api/journeys_controller_index_spec.rb, spec/requests/api/journeys_controller_show_spec.rb, spec/requests/api/journeys_controller_update_spec.rb, spec/requests/api/moves_controller_create_v2_spec.rb, spec/requests/api/moves_controller_role_access_rswag_spec.rb
https://dsdmoj.atlassian.net/browse/P4-1899
I have altered the ability to manage a move
In future we intend to support locations having multiple suppliers so we need to adapt our authorisation model.
=> It change the logic of ability to manage a move.

app/lib/nomis_client/alert_codes.rb, app/services/alerts/importer.rb, app/services/nomis_alerts/importer.rb
I am working on https://dsdmoj.atlassian.net/browse/P4-1933
This PR tries to make `NomisAlerts::Importer` a bit more readable
NomisAlerts::Importer
to make this cleaner in order to work on the P4-1933
=> Update Nomis alert mapping July 2020 + small refactor

Dockerfile
P4-<TODO>
Small optimisation of the dockerfile
- so that it can build faster (the gem installation can be cached even for code changes)
- hopefully OK
=> Small optimisation to dockerfile

CHANGELOG.md
Updates CHANGELOG.md to include all new changes in v2.2.0
=> Changelog v2.2.0

lib/tasks/journeys_report.rake
P4-1729
- Recently some journeys where created with missing details on them.
=> Reporting - Better handling of incomplete journey data.

spec/requests/api_stories/move_workflows/court_to_prison/person_with_nomis_prison_number_spec.rb
Tags api story rspec to it can be easily excluded
api story tests can be excluded with:
```
rspec --tag ~@api_story
```
=> tag api story rsepc

app/models/flag.rb, app/serializers/flag_serializer.rb, app/serializers/framework_question_serializer.rb, app/serializers/move_serializer.rb, app/serializers/v2/move_serializer.rb, app/services/frameworks/question.rb, db/migrate/20200728074625_rename_flag_name.rb, db/schema.rb, spec/factories/flag.rb, spec/models/flag_spec.rb, spec/serializers/flag_serializer_spec.rb, spec/serializers/framework_question_serializer_spec.rb, spec/services/frameworks/importer_spec.rb, spec/services/frameworks/question_spec.rb, swagger/v1/framework_flag.yaml, swagger/v1/move_include_parameter.yaml, swagger/v2/move_include_parameter.yaml
- Add PER required includes on Move resource
- Surface section on a framework question
- Rename name to title on flags, and update documentation for consistency with other resources
=> Add PER includes and rename `name` on flags

app/services/moves/finder.rb
Include all resources on Moves endpoint, followup to https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/761
=> Further includes for Moves endpoint

app/services/moves/finder.rb
Reverts ministryofjustice/hmpps-book-secure-move-api#762
=> Revert "Further includes for Moves endpoint"

spec/swagger/swagger_doc_v1.yaml, swagger/v1/framework.yaml, swagger/v1/framework_question.yaml, swagger/v1/framework_response_reference.yaml, swagger/v1/patch_framework_response.yaml
* Add specific PATCH framework response body
* Add section to framework question attributes
* Amend framework responses value types to include:
- string
- object
- array of strings
- array of objects
=> Update PER documentation

app/services/diagnostics/move_inspector.rb
P4-2029
- to make diagnostics even more useful
```
$ curl --request GET \
--url http://localhost:5001/diagnostics/moves/NXE8317C \
--header 'authorization: Bearer XXX'
MOVE RECORD
-----------
id:	4a8eff04-2f91-4a29-8ad2-15a13f534419
reference:	NXE8317C
date:	2020-06-10
status:		cancelled
cancel reason:	supplier_declined_to_move
move type:	court_appearance
from location:	Bishopsgate Custody Suite
to location:	High Wycombe County Court
created at:	2020-06-10 17:24:25 +0100
updated at:	2020-06-10 17:24:25 +0100
additional information: 
MOVE EVENTS
-----------
(no events recorded)
JOURNEYS
--------
(no journeys recorded)
JOURNEY EVENTS
--------------
(no journeys recorded)
WEBHOOK NOTIFICATIONS
---------------------
TYPE …
```
=> Add webhooks, person and profile to diagnostics

app/services/diagnostics/move_inspector.rb
P4-<TODO>
- so we can see if journeys are billable
=> adds the billable flag to diagnostics

lib/tasks/data/supplier_locations.yml
=> Adds FYI location (FELTHAM A HMPYOI) to Serco

app/lib/cloud_data_feed.rb, config/application.rb, spec/lib/cloud_data_feed_spec.rb
https://dsdmoj.atlassian.net/browse/P4-2018
Create a module to upload reporting to S3
To make uploading report on S3 easy.
=> Add CloudDataFeed to make simple to update report on S3

lib/tasks/journeys_report.rake
n/a
- it was not capturing "cancelled" events for journeys
=> fix a typo in the journey where clause

lib/tasks/journeys_report.rake
=> Update journey report with cancellation reason

app/models/journey.rb, app/services/feeds/journey.rb, lib/tasks/feeds/all.rake, lib/tasks/feeds/journey.rake, spec/factories/person.rb, spec/models/journey_spec.rb, spec/models/move_spec.rb, spec/models/person_spec.rb, spec/models/profile_spec.rb, spec/services/feeds/journey_spec.rb, spec/services/feeds/move_spec.rb
https://dsdmoj.atlassian.net/browse/P4-2013
Generate feed for Journey
To generate reports
=> Generate feed for journeys

lib/tasks/feeds/person.rake, lib/tasks/feeds/profile.rake
=> Feeds: Fix wrong task name

app/models/event.rb, app/services/feeds/event.rb, lib/tasks/feeds/all.rake, lib/tasks/feeds/event.rake, spec/models/event_spec.rb, spec/services/feeds/event_spec.rb, spec/services/feeds/notification_spec.rb
=> [P4-2011] Adds event feed

lib/tasks/feeds/all.rake
=> Fix elapsed time

app/models/application_record.rb, app/models/concerns/updated_at_range.rb, app/models/event.rb, app/models/journey.rb, app/models/move.rb, app/models/notification.rb, app/models/person.rb, app/models/profile.rb, app/services/feeds/event.rb, app/services/feeds/journey.rb, app/services/feeds/move.rb, app/services/feeds/notification.rb, spec/models/event_spec.rb, spec/models/journey_spec.rb, spec/models/move_spec.rb, spec/models/notification_spec.rb, spec/models/person_spec.rb
https://dsdmoj.atlassian.net/browse/P4-2057
the code for selecting entries based on date is duplicated in event, journey, move, notification, person and profile. The same applies for the tests.
We need to clean up that code to keep the feed clean and easy to maintain.
=> Refactor updated_range_at scope

app/services/diagnostics/move_inspector.rb
fixes updated_at time for diagnostics; adds supplier if available
=> fix updated_at, add supplier

app/serializers/move_serializer.rb, app/serializers/person_escort_record_serializer.rb, app/serializers/v2/move_serializer.rb, swagger/v1/move_include_parameter.yaml, swagger/v1/person_escort_record_include_parameter.yaml, swagger/v2/move_include_parameter.yaml
=> P4 2004 add collection multiple

db/migrate/20200819130412_add_type_to_event.rb, db/schema.rb
P4-1975
- This is required for STI to work in the events table
=> [P4-1975] Adds type to events table

Gemfile, Gemfile.lock
Bumps appinsights gem
See https://github.com/ministryofjustice/appinsights/pull/4
=> [P4-2069] Updates appinsights gem

CHANGELOG.md
=> Changelog for v2.3.3

lib/tasks/update_supplier_for_moves.rake
https://dsdmoj.atlassian.net/browse/P4-2036
This is a small rake task to update all the Supplier,
This is not yet completed since the new SupplierChooser is WIP.
=> Rake to update suppliers for all moves

config/puma.rb
=> Lint and try different puma callback

config/puma.rb
=> Run puma in clustered mode

config/initializers/prometheus_exporter.rb, config/puma.rb
It seems Rails methods aren't being loaded on loading Puma config, use native ruby include? instead
=> Change in? to include? on checking ENV

lib/tasks/notifications.rake
=> change update to create

CHANGELOG.md
=> Changelog 2.3.8

lib/tasks/notifications.rake
P4-2114
- the initial version without a delay overwhelmed one of the pods a little
- minimal
=> P4 2114 improve webhook rake task

CHANGELOG.md
=> 2.4.2 changelog

app/services/event_copier.rb
This PR add some output to the event copier
To have a clue on how the process is progressing (if stuck, if progressing and how fast it is)
=> Add some console log to event copier

lib/prometheus/collectors.rb, lib/prometheus/move_collector.rb, lib/prometheus/person_escort_record_collector.rb, spec/lib/prometheus/move_collector_spec.rb, spec/lib/prometheus/person_escort_record_collector_spec.rb, spec/rails_helper.rb
P4-2165
- so that move and PER counters can be consumed in dashboards
=> P4-2165 Add some new prometheus counters

app/lib/nomis_client/reasonable_adjustments.rb, spec/fixtures/files/nomis/get_reasonable_adjustments_200.json, spec/lib/nomis_client/reasonable_adjustments_spec.rb
jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2112
To get a reasonable adjustment for an offender, the booking id and the list of treatment codes are passed into a GET query to return a list of reasonable adjustments.
=> P4-2112 Add Reasonable Adjustments NOMIS query

lib/prometheus/move_collector.rb, lib/prometheus/person_escort_record_collector.rb, spec/lib/prometheus/move_collector_spec.rb, spec/lib/prometheus/person_escort_record_collector_spec.rb
=> Prometheus change nil to asterisk deploydev

lib/prometheus/move_collector.rb, lib/prometheus/person_escort_record_collector.rb, spec/lib/prometheus/move_collector_spec.rb, spec/lib/prometheus/person_escort_record_collector_spec.rb
=> disable move and PER prometheus metrics

app/controllers/api/generic_events_controller.rb, app/models/generic_event.rb, spec/factories/generic_event.rb, spec/models/generic_event_spec.rb, spec/requests/api/generic_events_controller_create_spec.rb
P4-2265
- This is now required for the feed
=> [P4-2265] Adds supplier to all new generic event rows transparently

app/models/person_escort_record.rb
This isn't being caught, so add all possible errors to rescue on
=> Rescue multiple errors on unique index error

lib/tasks/data/supplier_locations_go_live.yml
P4-2281
- so it is mapped to Geoamey
=> P4 2281 add supplier locations

app/models/framework_nomis_code.rb, app/models/framework_question.rb, app/services/frameworks/question.rb, db/migrate/20200923082044_create_framework_nomis_codes.rb, db/migrate/20200923123415_create_framework_nomis_codes_questions_join_table.rb, db/schema.rb, spec/factories/framework_nomis_code.rb, spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-professional-referral.yml, spec/fixtures/files/frameworks/person-escort-record-1/questions/wheelchair-users.yml, spec/models/framework_nomis_code_spec.rb, spec/models/framework_question_spec.rb, spec/services/frameworks/importer_spec.rb, spec/services/frameworks/question_spec.rb
jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2111
* Create new table for NOMIS codes and fallbacks. A question can be associated to multiple NOMIS codes, or can be a fallback question if no other questions link to a certain type of NOMIS resource. Those properties are not mutually exclusive, and a question could be a fallback question and also be linked to other codes.
* Import NOMIS codes for a question when pulling in new Frameworks, also set questions as fallback questions if the NOMIS fallback option is available.
=> P4-2111 Import NOMIS mappings and fallbacks into Frameworks

app/lib/nomis_client/reasonable_adjustments.rb, spec/fixtures/files/nomis/get_reasonable_adjustments_200.json, spec/lib/nomis_client/reasonable_adjustments_spec.rb
Now this has been added in NOMIS, pull in code descriptions for reasonable adjustments.
=> Add treatment description to reasonable adjustments

app/lib/nomis_client/reasonable_adjustments.rb
This was a copy paste blunder, fix url to point to correct reasonable adjustments NOMIS url
=> P4-2067 Fix reasonable adjustments url

app/services/diagnostics/move_inspector.rb
P4-<TODO>
See https://sentry.io/organizations/ministryofjustice/issues/1944589456/?project=2014776&referrer=slack
=> Fix diagnostics endpoint

app/services/framework_nomis_mappings/importer.rb, spec/services/framework_nomis_mappings/importer_spec.rb
jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2211
Log a Sentry error if NOMIS mappings are not persisted in bulk, to surface any validation issues when importing NOMIS resources. Also log any new NOMIS codes we receive to surface those values to be actioned and added to our system.
=> P4-2211 Log exceptions when NOMIS mappings fail or new NOMIS codes detected

app/models/framework_response.rb, spec/models/framework_response_spec.rb
https://dsdmoj.atlassian.net/browse/IM-52
When an application is deployed, and new migrations run, we end up with cached prepared statements which are no
longer valid since the underlying schema has changed. Since we have a rolling deploy, we cannot resolve this by restarting all pods at once after migrations is run. Retry the transaction instead, only once.
Sources used for this: https://medium.com/carwow-product-engineering/activerecord-error-cached-plan-must-not-change-result-type-aca72cdef504
https://flexport.engineering/avoiding-activerecord-preparedstatementcacheexpired-errors-4499a4f961cf
I opted out of having to retry all transactions and only this specific one as we don't know how safe other transactions are now or new ones added in the future, so to avoid that we only retry the …
=> Retry transaction when it fails on updating responses

CHANGELOG.md
=> Changelog v2.5.5

app/controllers/api/populations_controller.rb, config/routes.rb, spec/requests/api/populations_controller_update_spec.rb, spec/swagger/swagger_doc_v1.yaml, swagger/v1/patch_population_responses.yaml
P4-1427
- To support front end requirements, notably this screen: https://projects.invisionapp.com/share/YET7ANHWV9K#/screens/432812534
- New endpoint, so minimal risk
=> Add new PATCH /populations/:id endpoint to update populations

lib/tasks/fake_data.rake
=> Fixes fake data generation

.env.example, .env.test, app.json
Update example and test ENVs to remove old variables for NOMIS. Also update Heroku app.json to pull in variables.
The variables have been updated on Heroku itself, but I'll cleanup those after the PR goes in.
=> Update ENV variables to latest NOMIS envs

.circleci/config.yml
n/a
- The JSON blob started to come out formatted in pretty json with newlines, breaking the shell command.
=> Fix ECR cleanup job

CHANGELOG.md
=> Changelog v2.5.9

lib/tasks/data/supplier_locations.yml, lib/tasks/data/supplier_locations_go_live.yml
Add Snow Hill Custody Suite to Serco locations
=> Add Snow Hill Custody Suite to Serco

lib/tasks/data/supplier_locations_go_live.yml
New supplier mappings for locations
=> new locations for suppliers

CHANGELOG.md
=> Bumps changelog

lib/tasks/events.rake
P4-2507
We need to disable timestamp and touch updates to the updated_at of both the event itself, the eventable and all of its descendants when tweaking the supplier on `MoveRequested` and `MoveProposed` events
- Don't overrun reports whilst correcting the supplier on `MoveRequested` and `MoveProposed` events.
=> [P4-2507] Avoid timestamp changes to events and eventables when tweaking supplier

app/jobs/prepare_assessment_notifications_job.rb, spec/jobs/prepare_assessment_notifications_job_spec.rb
jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2521
To support multiple assessment webhooks and notifications add a generic assessment job for sending webhooks and emails
=> P4-2521 Add new generic assessment job

app/lib/cloud_data/metrics_feed.rb, lib/tasks/metrics.rake
to allow co-existance with other S3 env vars
=> Small rename of metrics S3 env vars

app/models/youth_risk_assessment.rb, spec/models/youth_risk_assessment_spec.rb
If the from location is a youth offender institution, allow a youth risk assessment to be created
=> Add youth offender institution to list of accepted location for assessment

lib/tasks/data/supplier_locations.yml
New locations <--> supplier mappings
based on the latest spreadsheets from the programme
=> New supplier locations

spec/requests/api/journeys_controller_create_spec.rb, spec/requests/api/journeys_controller_update_spec.rb
P4-<1716>
Journey controller tests for the event triggers.
This ensure the Journey events are created correctly.
=> Add Journey controller tests for events

app/jobs/prepare_base_notifications_job.rb, spec/jobs/prepare_assessment_notifications_job_spec.rb
P4-<TODO>
- one supplier has reported problems with a specific webhook
=> disables webhook as required

app/jobs/prepare_base_notifications_job.rb, spec/jobs/prepare_assessment_notifications_job_spec.rb
=> Feature flag supplier specific webhook

.circleci/config.yml
P4-XXXX
- Mentions are currently now shown in the messages
- Buttons are displaying inconsistently
=> refactor: Update Slack messages template to show mentions, fix buttons

.circleci/config.yml
Fix emoji attribute and make sure every text element has the correct type attribute.
=> refactor: Fix errors in slack message template

.circleci/config.yml
Use Slack mentions directly in template to avoid env var interpolation problems.
=> refactor: Simplify slack message mentions

app/jobs/notify_email_job.rb, app/jobs/notify_webhook_job.rb, config/initializers/sentry.rb
Fix sentry field scrubbing - filter the request if it is present
=> Fix sentry pii scrubbing

.circleci/config.yml, README.md
Renames references to master to main to match new default branch.
=> Rename master to main

app/controllers/api_controller.rb, config/initializers/lograge.rb
P4-<TODO>
- to allow for front-end requests to be traced through to API calls
minimal - tested on `dev`
=> logs transaction id in Kibana

CHANGELOG.md
=> Changelog v3.0.4

CHANGELOG.md
=> Update CHANGELOG.md 

CHANGELOG.md
=> Generated changelog for v3.1.0

CHANGELOG.md
=> Changelog v3.1.2

config/initializers/sentry.rb
Update the tracing sampler to check the environment and the name of the transaction before sending it to sentry. We don't want to record tracing on anything that's not production and we also don't want to record ping or health transactions.
=> Update the tracing setup to only be used in prod and ignore health

CHANGELOG.md
=> Changelog v3.1.3

app/controllers/api/profiles_controller.rb, app/lib/nomis_client/booking_details.rb, app/models/person.rb, app/serializers/v2/profile_serializer.rb, db/migrate/20210610144657_add_csra_to_profiles.rb, db/schema.rb, spec/fixtures/files/nomis/get_booking_details_200.json, spec/lib/nomis_client/booking_details_spec.rb, spec/models/person_spec.rb, spec/serializers/v2/profile_serializer_spec.rb
P4-2892
- It will make it accessible by the frontend.
=> [P4-2892] Store CSRA from NOMIS on Profile create

CHANGELOG.md
Generated the latest changelog changes for the 3.1.6 release.
=> Update changelog for v3.1.6

app/lib/nomis_client/assessments.rb, app/models/framework_nomis_code.rb, app/models/framework_nomis_mapping.rb, app/serializers/framework_nomis_mapping_serializer.rb, app/services/framework_nomis_mappings/assessments.rb, app/services/framework_nomis_mappings/importer.rb, app/services/framework_nomis_mappings/nomis_sync_status.rb, db/migrate/20210716100831_add_assessment_dates_to_framework_nomis_mapping.rb, db/schema.rb, spec/fixtures/files/nomis/get_assessments_200.json, spec/lib/nomis_client/assessments_spec.rb, spec/models/framework_nomis_code_spec.rb, spec/models/framework_nomis_mapping_spec.rb, spec/rails_helper.rb, spec/serializers/framework_nomis_mapping_serializer_spec.rb, spec/services/framework_nomis_mappings/assessments_spec.rb, spec/services/framework_nomis_mappings/importer_spec.rb, spec/services/framework_nomis_mappings/nomis_sync_status_spec.rb
[P4-2893](https://dsdmoj.atlassian.net/browse/P4-2893)
I have added the ability for assessments to be imported from NOMIS into the API.
This is in advance of assessments being added to the framework (https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks/pull/56).
=> Import assessments from NOMIS

CHANGELOG.md
I've updated the change log for v3.2.0.
=> Generated changelog for v3.2.0

Gemfile, Gemfile.lock, config/initializers/rack_timeout.rb, config/initializers/sentry.rb
This improves how we monitor performance of the API in Sentry. See individual commits for more details.
=> Improve Sentry performance monitoring

CHANGELOG.md
Generated the changelog for version 3.3.0 using `rake changelog`.
=> Generated changelog for v3.3.0

CHANGELOG.md
This builds the changelog for version 3.3.1.
=> Generated changelog for v3.3.1

CHANGELOG.md
Generated the changelog for version 3.4.0.
=> Generated changelog for v3.4.0

app/lib/reports/person_escort_record_quality.rb, lib/tasks/reports.rake, spec/lib/reports/person_escort_record_quality_spec.rb, spec/lib/tasks/reports/person_escort_record_quality_spec.rb, spec/rails_helper.rb
This adds a new Rake task which outputs information about person escort records which we can analyse to determine the quality of them.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3081)
=> PER Quality Report

CHANGELOG.md
This generates the changelog for version 3.5.0.
=> Generated changelog for v3.5.0

CHANGELOG.md
This generates the changelog for version 3.5.1.
=> Generated changelog for v3.5.1

CHANGELOG.md
This is the changelog for version 3.5.2.
=> Generated changelog for v3.5.2

app/services/gps_report.rb, spec/services/gps_report_spec.rb
P4-2944
- Currently we're only fetching 999 data points due to pagination
=> Pull more data from athena if we're limited

app/models/person.rb, spec/factories/person.rb, spec/models/person_spec.rb, spec/requests/api/people_controller_create_spec.rb, spec/requests/api/people_controller_create_v2_spec.rb, spec/requests/api/people_controller_index_spec.rb, spec/requests/api/people_controller_index_v2_spec.rb, spec/requests/api/people_controller_patch_v2_spec.rb, spec/requests/api/people_controller_update_spec.rb, spec/serializers/person_serializer_spec.rb, spec/services/people/creator_spec.rb, spec/services/people/finder_spec.rb, spec/services/people/updater_spec.rb, spec/services/v2/people/finder_spec.rb
This reverts commit 1005b285382c5c7cef05e8d657f37fce8eafe087, reversing
changes made to 5327d28b799a83ed553b772af7944dfed92df3c4.
P4-2828
- We aren't ready to add PNC validation yet
=> Revert "Merge pull request #1555 from ministryofjustice/P4-2828/add-pnc-number-validation"

CHANGELOG.md
=> Generated changelog for v3.7.1

CHANGELOG.md
Generated the changelog for version 3.7.3.
=> Generated changelog for v3.7.3

CHANGELOG.md
This updates the changelog for version 3.7.4.
=> Generated changelog for v3.7.4

app/lib/imports/column_mapper.rb, app/lib/imports/journeys_missing_vehicle.rb, app/lib/imports/missing_move_ending_events.rb, app/lib/imports/missing_move_start_events.rb, app/lib/imports/moves_without_ending_state.rb, spec/lib/imports/column_mapper_spec.rb
It looks like in some cases the spreadsheets we receive from the suppliers contain extra unexpected whitespace at the end of some cells which needs to be stripped away.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3289)
=> Strip whitespace from spreadsheet cells

app/lib/imports/missing_journey_start_events.rb, lib/tasks/import.rake, spec/lib/imports/missing_journey_start_events_spec.rb, spec/lib/tasks/imports/missing_journey_start_events_spec.rb
This adds import tasks for journeys which are missing start events, similar to #1620.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3068)
=> Import journey missing start events

app/lib/imports/delete_events.rb, app/lib/imports/events_incorrect_occurred_at.rb, lib/tasks/import.rake, spec/lib/imports/delete_events_spec.rb, spec/lib/imports/events_incorrect_occurred_at_spec.rb, spec/lib/tasks/imports/delete_events_spec.rb, spec/lib/tasks/imports/events_incorrect_occurred_at_spec.rb
This adds some tasks for correcting duplicate events and events which don't have the right occurred at date/time.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3379)
=> Add tasks for importing events

lib/tasks/data/categories.yml, lib/tasks/data/regions.yml
It's recently re-opened and the category and region need to be updated to reflect the latest information.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3387)
=> Update category and region for HMP Morton Hall

lib/tasks/data/categories.yml, lib/tasks/data/regions.yml, lib/tasks/data/supplier_locations.yml
This adds information for the new Five Wells prison (nomis agency ID `FWI`).
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3399)
=> Add Five Wells location information

.circleci/config.yml
This PR removes the deploy step in CircleCI for staging on live-1
=> Migrate staging to live

spec/swagger/swagger_doc_v1.yaml
This explains what value it takes if not specified.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3425)
=> Add line about journey dates in Swagger docs

lib/tasks/data/categories.yml, lib/tasks/data/regions.yml, lib/tasks/data/supplier_locations.yml
This new location is split from HMP Parc (`PRI`) so the youth and adult prison side are represented as two separate locations.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3032)
=> Add HMP Parc (YOI) location

app/models/generic_event.rb, app/models/generic_event/medical.rb, app/models/generic_event/per_medical_aid.rb, app/models/generic_event/per_medical_drugs_alcohol.rb, app/models/generic_event/per_medical_mental_health.rb, lib/tasks/data_maintenance.rake, spec/factories/generic_event.rb, spec/models/generic_event/incident_spec.rb, spec/models/generic_event/medical_spec.rb, spec/models/generic_event/per_medical_aid_spec.rb, spec/models/generic_event/per_medical_drugs_alcohol_spec.rb, spec/models/generic_event/per_medical_mental_health_spec.rb, spec/models/generic_event_spec.rb, spec/support/an_event_about_a_medical.rb
These new events are supposed to represent an update to the PER, once the move has started. See individual commits for more details.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3335)
=> Add new medical events for lockouts

app/models/move.rb
We don't need to look for events on the person or the journeys for important events, and we don't need to apply a certain order.
These were all accidentally added in https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1822.
=> Improve performance of Move#important_events

app/controllers/api/journeys_controller.rb, spec/requests/api/journeys_controller_create_spec.rb
[P4-3221](https://dsdmoj.atlassian.net/browse/P4-3221)
Added validation to prevent duplicate journeys being created 
I am doing this because: To prevent users from creating duplicate journeys for a move
=> Add validation to prevent duplicate journeys

app/models/move.rb, spec/models/move_spec.rb
We need this on the frontend to determine when to show the button to add lockout events or to record a handover.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3396)
=> Include MoveLodgingStart in important events

.circleci/config.yml
[P4-3715](https://dsdmoj.atlassian.net/browse/P4-3715)
- Temporary increase of the timeout of the migration job.
- We are seeing the job timeout due to a long running migration
=> P4-3715 temporary increase of the timeout for the migration job to improve chances of a long running index creation migration from working.

.circleci/config.yml
Reverts ministryofjustice/hmpps-book-secure-move-api#1864
=> Revert "P4-3715 temporary increase of the timeout for the migration job to improve chances of a long running index creation migration from working."

db/fixtures/prison_transfer_reasons.yml
P4-[3757](https://dsdmoj.atlassian.net/browse/P4-3757)
This PR changes the wording for the court move name and adds  a new transfer reason
=> Add new PrisonTransferReason Court video link

README.md
I've changed the README to include the correct deployment instructions.
=> Update the deployment instructions in the README

app/controllers/api/v1/moves_actions.rb, app/controllers/api/v2/moves_actions.rb, app/workers/notify_unnotified_moves_worker.rb, spec/workers/notify_unnotified_moves_worker_spec.rb
Also add MoveProposed instead of MoveRequested for moves that were initially proposed.
=> Change NotifyUnnotifiedMovesWorker to check for moves without any notifications

app/models/generic_event.rb, app/models/generic_event/move_overnight_lodge.rb, spec/factories/generic_event.rb, spec/models/generic_event/move_overnight_lodge_spec.rb
P4-3956
- This event is being added as part of the overnight lodging work, it's purpose is to make users aware that a move has an overnight lodging planned.
=> [P4-3956] Add new event: MoveOvernightLodge

app/models/journey.rb, spec/models/journey_spec.rb
[P4-4085](https://dsdmoj.atlassian.net/browse/P4-4085)
- Added audit trail for Journey model
- Tracking this will help with debugging and with analysis of security breaches
[P4-4085]: https://dsdmoj.atlassian.net/browse/P4-4085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add audit trail for journeys

CHANGELOG.md
[P4-4052](https://dsdmoj.atlassian.net/browse/P4-4052)
Generate changelog for v3.30.0
- We need a record of what changes have been released in which versions of the app
[P4-4052]: https://dsdmoj.atlassian.net/browse/P4-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Generated changelog for v3.30.0

app/controllers/api_controller.rb, docker-compose.yml
[P4-4100](https://dsdmoj.atlassian.net/browse/P4-4100)
- Log at the beginning of the controller action, not just at the end
- So that we can get a better idea of the sequence of events during a controller action
[P4-4100]: https://dsdmoj.atlassian.net/browse/P4-4100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Log controller entry [P4-4100]

CHANGELOG.md
[P4-4131](https://dsdmoj.atlassian.net/browse/P4-4131)
- Generated changelog for v3.31.2
- To track app releases
[P4-4131]: https://dsdmoj.atlassian.net/browse/P4-4131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Generated changelog for v3.31.2

.rubocop.yml, Gemfile.lock, app/controllers/api/allocations_controller.rb, app/services/allocations/updater.rb, config/routes.rb, spec/lib/reports/person_escort_record_quality_spec.rb, spec/requests/api/allocations_controller_update_spec.rb, spec/requests/api/reference/regions_controller_index_spec.rb, spec/swagger/swagger_doc_v1.yaml, swagger/v1/patch_allocation_responses.yaml
[P4-4139](https://dsdmoj.atlassian.net/browse/P4-4139)
- It was requested by PMU
- Changes an api that is used in production (non-breaking change)
[P4-4139]: https://dsdmoj.atlassian.net/browse/P4-4139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update allocation date

CHANGELOG.md
- Generate changelog for version 3.32.0
- So that we can track our releases
=> Generated changelog for v3.32.0

.gitignore, helm_deploy/.helmignore, helm_deploy/README.md, helm_deploy/hmpps-book-secure-move-api/.helmignore, helm_deploy/hmpps-book-secure-move-api/Chart.lock, helm_deploy/hmpps-book-secure-move-api/Chart.yaml, helm_deploy/hmpps-book-secure-move-api/templates/_helpers.tpl, helm_deploy/hmpps-book-secure-move-api/templates/cron_jobs.yaml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-api.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-pod.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-summary.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard.yml, helm_deploy/hmpps-book-secure-move-api/templates/deployment_sidekiq.yaml, helm_deploy/hmpps-book-secure-move-api/templates/feeds_checker_configmap.yaml, helm_deploy/hmpps-book-secure-move-api/values.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml
- Added Helm charts
- Because we are making the deployment pipeline more DPS-like
=> [MAP-26] Add Helm charts

.circleci/config.yml, helm_deploy/README.md, helm_deploy/values-preprod.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml, spec/swagger/swagger_doc_v1.yaml, spec/swagger/swagger_doc_v2.yaml
- Deploy to Staging using Helm chart
- To make the pipeline more DPS-like
=> [MAP-26] Deploy to Staging using Helm

helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml
- Tweaked some of the Helm templates
- The ingress annotations weren't in the expected format
- Some values were duplicated in secrets when they were supposed to be regular env vars
=> [MAP-26] tweak the Helm templates

.circleci/config.yml
- Deploy to UAT using Helm chart
- To make the pipeline more DPS-like
=> ci: Deploy UAT using Helm

.circleci/config.yml, README.md
- Deploy to Preprod using Helm chart
- To make the pipeline more DPS-like
=> [MAP-26] Deploy preprod using Helm

helm_deploy/values-preprod.yaml
[MAP-26]
- Fix some env vars and secrets in the Helm config for Preprod
- It was wrong and broke the deployment
=> ci: Fix some Helm values for preprod

.circleci/config.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-api.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-pod.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard-summary.yml, helm_deploy/hmpps-book-secure-move-api/templates/dashboard.yml
- Deploy to Production using Helm chart
- To make the pipeline more DPS-like
=> [MAP-26] Deploy to Production using Helm

.circleci/config.yml, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml
MAP-26
- Fix malformed ingress config for prod & preprod
- Require prod approval
- There were errors in the CircleCI and Helm config
=> [MAP-26] Fix ingresses and CircleCI config

app/lib/cloud_data/reports_feed.rb, app/workers/feeds/feed_worker.rb, app/workers/gps_report_worker.rb, helm_deploy/hmpps-book-secure-move-api/values.yaml, spec/lib/cloud_data/reports_feed_spec.rb, spec/workers/feeds/feed_worker_spec.rb, spec/workers/gps_report_worker_spec.rb
MAP-19
- Change the folder structure for the reporting bucket
- We are moving to a new analytical platform that requires a certain folder structure for the data
=> fix: Change the folder structure for the reporting bucket

helm_deploy/values-staging.yaml
MAP-19
- Configure reporting env vars in staging
- We need to test the reporting jobs
=> fix: Configure reporting env vars in staging

helm_deploy/values-staging.yaml
MAP-144
Added service account name to staging helm values to test use of IRSA module
=> MAP-144 Add service account to stagin environment

app/lib/cloud_data/reports_feed.rb, app/workers/gps_report_worker.rb, spec/lib/cloud_data/reports_feed_spec.rb, spec/workers/gps_report_worker_spec.rb
MAP-19
- Use correct ACL and SSE for reporting bucket
- There is blanket rejection for requests using the wrong ACL or SSE
=> [MAP-19] Use correct ACL and SSE for reporting bucket

app/services/moves/finder.rb, spec/services/moves/finder_spec.rb
MAP-84
- Improve move finder performance
- We were seeing long page load times in preprod, so we have rewritten the move finder code to try and reduce the number of subqueries.
=> [MAP-84] Improve move finder performance

app/services/moves/finder.rb
- DRY up the lodgings filters
- Because the method was very big, and _hopefully_ this makes it more readable...
=> refactor: DRY up the lodgings filters

CHANGELOG.md
Generated changelog for v3.36.5
=> Generated changelog for v3.36.5

app/services/feeds/jpc.rb, app/workers/feeds/feed_worker.rb, app/workers/feeds/jpc_worker.rb, lib/tasks/feed.rake, spec/services/feeds/jpc_spec.rb, spec/workers/feeds/feed_worker_spec.rb
MAP-319
- Added new JPC feed with more useful data
- It seems to miss some moves/journeys/events for various reasons (see ticket)
=> MAP-319: Add new feed for JPC with more useful data

app/services/moves/exporter.rb, spec/services/moves/exporter_spec.rb
MAP-346
- Add PER alert flags to moves CSV download
- To assist with Operation Safeguard
=> MAP-346: Add PER alert flags to moves CSV download

CHANGELOG.md
- Updated changelog
- To track our releases
=> Generated changelog for v3.40.3

app/services/moves/exporter.rb
This seems to improve performance by over 250%
[MAP-511]
[MAP-511]: https://dsdmoj.atlassian.net/browse/MAP-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Memoise flag descriptions for CSV

app/services/moves/exporter.rb, spec/services/moves/exporter_spec.rb
The performance is still too poor so we will remove the columns for now.
[MAP-511]
[MAP-511]: https://dsdmoj.atlassian.net/browse/MAP-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAP-511] Remove alert columns from CSV unless enabled by feature flag

app/controllers/sre_swagger_docs_controller.rb, config/initializers/rswag-ui.rb, config/routes.rb, spec/swagger/swagger_doc_base.yaml, spec/swagger_helper.rb, swagger/base/swagger.yaml, swagger/v2/get_subject_access_request_responses.yaml
MAP-922
- The SAR team have requested it
=> MAP-922: Add swagger docs for SAR

reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml, reports/weekly-cancelled-moves/02-weekly-cancelled-moves-cronjob.yaml
MAP-<942>
- It was previously being managed on a local machine
=> MAP-942 - Weekly cancelled moves report

helm_deploy/hmpps-book-secure-move-api/values.yaml
- They were out of date/lists used when original reports were created in dev/preprod.
=> Updated recipients for Helm reports.

CHANGELOG.md
Generated changelog for v3.45.6
=> Generated changelog for v3.45.6

app/services/moves/exporter.rb, spec/services/moves/exporter_spec.rb
MAP-1421
- Users identified these columns as no longer needed and helps with the size of the files causing the download timeout issue.
=> MAP-1421 removed 7 columns from the csv download as per the ticket

CHANGELOG.md, Gemfile.lock
Generated changelog for v3.50.0
=> Generated changelog for v3.50.0

app/services/feeds/all.rb, app/services/feeds/jpc.rb, app/workers/feeds/all_worker.rb, spec/services/feeds/all_spec.rb
MAP-1582
- AP have requested it
=> MAP-1582 - Add PER/YRA events to all feed for AP

Gemfile, Gemfile.lock
[MAP-1682](https://dsdmoj.atlassian.net/browse/MAP-1682)
Bump doorkeeper gem 
https://github.com/ministryofjustice/hmpps-book-secure-move-api/security/dependabot/47
[MAP-1682]: https://dsdmoj.atlassian.net/browse/MAP-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1682 Bump doorkeeper gem

Gemfile, Gemfile.lock, app/services/framework_responses/bulk_updater.rb, config/environments/development.rb
[MAP-1664](https://dsdmoj.atlassian.net/browse/MAP-1664)
Added the bullet gem to development: https://github.com/flyerhzm/bullet
Resolved [Sentry Issue](https://ministryofjustice.sentry.io/share/issue/df851226bfe049c893582b9ca7d7228f/)
```
db - SELECT "framework_nomis_mappings".* FROM "framework_nomis_mappings" INNER JOIN "framework_nomis_mappings_responses" ON "framework_nomis_mappings"."id" = "framework_nomis_mappings_responses"."framework_nomis_mapping_id" WHERE "framework_nomis_mappin...
```
N+1 queries impact performance
[MAP-1664]: https://dsdmoj.atlassian.net/browse/MAP-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1664 N+1 Queries

CHANGELOG.md
Update the CHANGELOG for v3.52.6 release
=> Generated CHANGELOG for v3.52.6

app/services/moves/exporter.rb
https://dsdmoj.atlassian.net/browse/MAP-530
Tidy up the CSV headers
Recently added headers had underscores, which is inconsistent with the rest of the CSV headers
=> MAP-520 Group cancellation fields and title-ize headers

helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-court-moves/01-weekly-cancelled-court-moves-config.yaml, helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml
[MAP-1920](https://dsdmoj.atlassian.net/browse/MAP-1920)
- Remove indentation from SQL 
- Remove wildcard `*` from subquery
- Lowercase SQL keywords
The weekly reports failed, and came through empty / with no results. 
We can run these reports locally or validate the SQL so this is a trial and error approach.
[MAP-1920]: https://dsdmoj.atlassian.net/browse/MAP-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1920 Fix weekly report

CHANGELOG.md
=> Generated changelog for v3.53.4

app/services/moves/exporter.rb, spec/services/moves/exporter_spec.rb
https://dsdmoj.atlassian.net/browse/MAP-1971
I have disabled CSV Download Framework Flags with a Feature Flag.
To enable, set:
`FEATURE_FLAG_CSV_ALERT_COLUMNS=true`
Performance issues loading the Framework Flags
=> Disable CSV Download Framework Flags with a Feature Flag

Gemfile, Gemfile.lock, config/initializers/doorkeeper.rb
https://dsdmoj.atlassian.net/browse/MAP-1682
This reverts commit 1b1c1108766b7c5a6f09b6667d23ccbe1f69b4ff
that attempted to upgrade the Doorkeeper gem
401 errors on Staging
=> Revert "Update Doorkeeper configuration to fix 401 errors (#2511)"

CHANGELOG.md
Deployment: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-book-secure-move-api/13004/workflows/5ea1275b-5eee-4d9c-bfca-5a4fa00fce76
=> Generated changelog for v3.65.0
