app/services/moves/reference_generator.rb
spec/services/moves/reference_generator_spec.rb

This change just fixes the position of the characters and numbers, it's still basically random and still 8 characters long. But you get something like `ABC1234D` rather than `1AB2C34D`

[P4-551] Change move reference format to ABC1234D

---

app/controllers/api/v1/reference/locations_controller.rb
app/services/locations/finder.rb
spec/requests/api/v1/reference/locations_controller_spec.rb
swagger/v1/swagger.json

HMPPS SSO provides the frontend application with a list of locations for the user in the form of their NOMIS agency ID(s). The frontend application therefore needs a way to look those up and resolve them to the IDs used in the API.
This provides an additional filter to find locations by their NOMIS agency ID. It is theoretically possible for there to be more than one with the same ID, but I haven't tried to resolve this here. For now the frontend will just use the first one that isn't disabled.

Allow filtering of location by NOMIS agency ID

---

config/initializers/prometheus_exporter.rb

Prometheus will currently attempt to collect stats for all environments
apart from `test`. This causes regular warnings when running the app
locally without Prometheus correctly configured.
This change makes the check look for `production` before setting up
Prometheus.

Change Prometheus collection condition

---

app/models/move.rb
app/serializers/move_serializer.rb
db/migrate/20190808113402_add_moves_move_type.rb
db/migrate/20190808142502_add_moves_additional_information.rb
db/migrate/20190808151619_make_moves_to_location_nullable.rb
db/schema.rb
spec/factories/location.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/serializers/move_serializer_spec.rb
swagger/v1/move.json

In future we would probably want to make `Move#move_type` `NOT NULL` but we will make that part of a follow up PR (and deploy) to avoid potential upgrade issues.

[P4-561] Backend work to support prison recalls

---

app/controllers/api/v1/moves_controller.rb
app/models/move.rb
app/services/moves/finder.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/services/moves/finder_spec.rb
swagger/v1/location_reference.json

Adds some further more specific request specs to cover the rules around `move_type` and `to_location`.
Also need to relax the implicit validation on `belongs_to :to_location`.

[P4-561] Bugfix for persistence of `Move#move_type`

---

app/lib/nomis_client/moves.rb
db/migrate/20190821095338_change_time_due_to_datetime.rb
db/schema.rb
spec/lib/nomis_client/moves_spec.rb

All the moves in production have a time_due that is null, so dropping and recreating the column in the database is safe

Change moves time_due to be a datetime

---

Gemfile
Gemfile.lock

https://nvd.nist.gov/vuln/detail/CVE-2019-5477

Upgrade nokogiri following recommendation from Github

---

app/services/moves/finder.rb

We were previously sorting moves by location title to help with
the frontend. This currently causing issues with pagination where
results may be returned across multiple pages as location is not
always guaranteed.
This change amends the sort to be by ID so the order returned during
pagination will always be the same.

Set default sort order to ID on moves

---

app/lib/nomis_client/alerts.rb
app/services/alerts/anonymiser.rb
lib/tasks/nomis_fixtures.rake
spec/services/alerts/anonymiser_spec.rb

Include alerts in the data fixture files exported to `db/fixtures/nomis`. These are used in https://github.com/ministryofjustice/elite2-api-mock (separate PR to follow).

[P4-564] Alerts data fixtures

---

app/models/profile.rb
app/models/profile/assessment_answer.rb
app/services/alerts/importer.rb
spec/factories/nomis_alert.rb
spec/models/profile/assessment_answer_spec.rb
spec/models/profile_spec.rb
spec/services/alerts/importer_spec.rb

This PR adds an `Alerts::Importer` class to import alerts for moves (via profiles).
Alerts from NOMIS are merged into our `AssessmentAnswer`s by overwriting all existing NOMIS imported assessment answers but leaving any that were manually created. To facilitate this we have included an `AssessmentAnswer#imported_from_nomis` attribute that is `true` iff the assessment answer came from NOMIS direct.

[P4-606] Alerts importer

---

app/lib/nomis_client/moves.rb
app/services/moves/importer.rb
spec/services/moves/importer_spec.rb

This PR just invokes `Alerts::Importer` from `Moves::Importer` so alerts are imported at the same time as moves and profiles.

[P4-606] Trigger alerts import when importing a move from NOMIS

---

app/services/people/importer.rb
spec/services/people/importer_spec.rb

I found at least one real-life profile that has a nil value for ethnicity. It caused a crash so handling it here as well as genders.

QUICKFIX: Handle nil values for ethnicity and gender

---

app/controllers/api/v1/moves_controller.rb
app/models/location.rb
app/services/moves/nomis_synchroniser.rb
app/services/people/anonymiser.rb
spec/factories/location.rb
spec/lib/nomis_client/locations_spec.rb
spec/models/location_spec.rb
spec/services/moves/nomis_synchroniser_spec.rb

We have been doing the call to NOMIS on all requests up to now. They are redundant for Police so we will skip for now.
Have also refactored some business logic out of the controller into a new `Moves::NomisSynchroniser` service class (if anybody can think of a better name let me know).

[P4-664] Only synchronise move data from NOMIS for prisons

---

app/serializers/assessment_question_serializer.rb
db/migrate/20190916113440_remove_assessment_questions_nomis_code.rb
db/schema.rb
spec/factories/assessment_question.rb
spec/requests/api/v1/reference/assessment_questions_controller_spec.rb
spec/serializers/assessment_question_serializer_spec.rb
swagger/v1/assessment_question.json

This PR removes the following attributes from `AssessmentQuestion` (they were never used):
* `nomis_alert_code`
* `nomis_alert_type`
Mappings to NOMIS alerts are now declared in the `NomisAlerts` model.

[P4-670] Remove redundant AssessmentQuestion attributes

---

README.md

Need to populate NomisAlerts to map NOMIS alert codes to our assessment questions.

Add missing instruction to README

---

app/controllers/api/v1/moves_controller.rb
app/lib/nomis_client/moves.rb
app/services/moves/nomis_synchroniser.rb
app/services/moves/sweeper.rb
spec/lib/nomis_client/moves_spec.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/requests/api/v1/moves_controller_show_spec.rb
spec/services/moves/nomis_synchroniser_spec.rb
spec/services/moves/sweeper_spec.rb

We can now use the environment variable `NOMIS_AGENCY_IDS` to specify a comma-separated list of NOMIS ids for the prisons that form part of the pilot program. This value will be used for requests to `GET /moves` that do not specify a `from_location_id`, e.g.
```
NOMIS_AGENCY_IDS=HLI,PVI
```

[P4-707] Support for multiple location downloads

---

app/controllers/api/v1/moves_controller.rb
spec/factories/move.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/services/moves/finder_spec.rb
swagger/v1/swagger.json

The new `from_location_id` and `to_location_id` (which wasn't working previously) are now accepting arrays.
The goal is to follow json api recommendations (https://jsonapi.org/recommendations/#filtering) without breaking HTTP query strings (which require array parameters to be like "from_location_id[]=foo&from_location_id[]=bar")

Attempt to fix to_location_id and fetch multiple from_location_id

---

app/lib/nomis_client/base.rb

This PR wraps all `NomisClient`requests so we can log their response times to help understand the `/moves/` performance issue.

Add rudimentary timing for NOMIS client requests

---

.circleci/config.yml

This PR should resolve the failed Cloud Platform deployments by using the updates RBAC team `book-a-secure-move`.

use updated GH team for CP deploy

---

app/services/moves/sweeper.rb
db/migrate/20191106121438_unique_index_on_moves.rb
db/schema.rb
lib/tasks/data_maintenance.rake
spec/services/moves/sweeper_spec.rb

The old fix dealing with duplicate moves has been ported to deal with the new `nomis_event_ids` field

Hotfix duplicate moves

---

swagger/v1/swagger.json

After chasing my tail for 30 minutes trying to figure out why CORS options weren't being honoured, I realised our Swagger JSON is static, and always reference staging.
This PR adds production and `localhost:3000` as options for Swagger UI requests. 
I think there's a more elegant way to add localhost only for dev environments with a lambda, but my Internet connection is pretty poor right now (🚂), so if that's possible I'll raise another PR.

Enable Swagger UI to run against prod, staging and localhost

---

config/environments/production.rb
config/initializers/filter_parameter_logging.rb

Fixes https://dsdmoj.atlassian.net/browse/P4-790
AR logs are now going to /dev/null and most sensitive data are filtered out

Do not log AR in production + filter sensitive data

---

.env.example
Gemfile
Gemfile.lock
config/initializers/cors.rb

Attempting to use the Swagger UI locally yields the following error for any request:
```
TypeError: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.
```
This PR:
- Adds CORS support
- Adds a blanket allow for development environments
- Uses a new environment variable (`CORS_ALLOWED_ORIGINS`) to specify allowed origins in production & staging environments

Add CORS for Swagger UI

---

app/models/location.rb
spec/fixtures/files/nomis_get_locations_200.json
spec/lib/nomis_client/locations_spec.rb

This PR adds  the `POLICE` agency type to the NOMIS importer, so we can pull police custodies.

Add POLICE agency type to NOMIS location import

---

lib/tasks/reference_data.rake

Removes the Serco -> Brixton association as that's not ready to rollout yet in production.
Note that this PR doesn't remove the association from any instances where it's already been made, so we'll also need to go into prod and remove that manually:
```
PECS_APP=api
PECS_ENV=production
kubectl --namespace=hmpps-book-secure-move-${PECS_APP}-${PECS_ENV} exec -it `kubectl get pods --namespace=hmpps-book-secure-move-${PECS_APP}-${PECS_ENV} -o json |  jq -r '.items[0].metadata.name'` rails c
```
and
```
serco = Supplier.find_by(name: 'Serco')
serco.locations = serco.locations.all.reject{|location| location.key == 'bxi'}
```

Removes the Serco -> Brixton association

---

lib/tasks/reference_data.rake

This PR:
- does a minor refactor to only query once per supplier for the supplier details (previously once per location)
- adds console output to make validating the run easier

Supplier relationship rake output

---

app/lib/nomis_client/base.rb
spec/lib/nomis_client/base_spec.rb

Implements retries when the `NomisClient` raises a Faraday::ConnectionFailed or a Faraday::TimeoutError.
The number of retries is hardcoded to 3.
Solves https://dsdmoj.atlassian.net/browse/P4-768

Retries on timeout and connection failed

---

app/controllers/api/v1/documents_controller.rb
app/serializers/document_serializer.rb
app/serializers/move_serializer.rb
config/environments/development.rb
swagger/v1/document.json

This fixes a weird bug happening when POSTing to `documents/` with an empty `file` attribute, for some reasons the server returns a `ActiveSupport::MessageVerifier::InvalidSignature` instead of generating a validation error (https://groups.google.com/forum/#!topic/rubyonrails-core/xI5HPnxIAIE).
It also adds the url attribute to the Document's JSON serializer.

Fixes validation when file is missing + attachment url

---

lib/tasks/reference_data.rake

This PR adds the remaining supplier/location mappings to the rake task for December 2019.
For https://dsdmoj.atlassian.net/browse/P4-811 (see recent comments for the requested codes for validation).
Once this has been merged it needs to be:
- Deployed to staging, preprod & production
- Log in to each environment & run the rake task
- Flush each environment's Redis cache

Add supplier/location mappings to rake task for December 2019 rollout

---

app/controllers/api/v1/documents_controller.rb
app/controllers/api_controller.rb
app/serializers/document_serializer.rb
app/serializers/move_serializer.rb
config/environments/development.rb
spec/requests/api/v1/documents_controller_create_spec.rb
spec/requests/api/v1/documents_controller_destroy_spec.rb
spec/support/responds_with_success_200.rb
spec/support/responds_with_success_201.rb
swagger/v1/document.json

Limit multipart Content-Type to document creation and leave everything else to JSON API
The reason for doing this is that we're returning JSON with content-type `multipart/form-data` which doesn't get parsed by the HTTP library the frontend is using.
This limits the `multipart/form-data` to the document creation, and returns JSON API for everything else.

Hotfix limit multipart to document creation

---

db/migrate/20191114122923_create_active_storage_tables.active_storage.rb
db/schema.rb
spec/requests/api/v1/documents_controller_create_spec.rb

This changes the DB schema to use UUIDs in the ActiveStorage attachments table.
This is a framework bug: https://github.com/rails/rails/issues/35746
1) Pull
2) `cd $YOURLOCATION/hmpps-book-secure-move-api`
3) `bundle exec rake db:migrate VERSION=20191106121438` # this will wipe the broken table from your local db
4) `bundle exec rake db:migrate`

Change db table declaration to be nice with UUIDS

---

lib/tasks/reference_data.rake

Resolves https://dsdmoj.atlassian.net/browse/P4-844.
This PR adds the remaining police custodies from https://docs.google.com/spreadsheets/d/1x0Np9JIjacWHFJceajgOA6kO4A7fZCJr/edit#gid=678683446.
To roll this out to production, we need to follow https://dsdmoj.atlassian.net/wiki/spaces/PECS4/pages/1576632382/Associating+locations+to+suppliers.

Update police custodies for January rollout

---

lib/tasks/reference_data.rake

Partially reverts #187 to resolve 'moves for all locations' page error https://dsdmoj.atlassian.net/browse/P4-860.
This PR is necessary as a temporary solution to restore functionality. I'll create an issue detailing the development effort necessary to allow the additional sites to be re-added.

Revert GEOAmey locations introduced in 

---

app/serializers/document_serializer.rb

This PR reconciles local and production behaviour by using a consistent URL generation scheme. The previous approach raised an exception in development and fell-back to a different approach, meaning the behaviour in each environment was different.
`url_for` retrieves the local URL for the attachment, which redirects to S3 when in use.
If we experience any errors in Cloud Platform with hostname being required, these should be added to the relevant environment configs. We'll be able to test this on staging.

Use url_for across all environments to retrieve service URL.

---

app/lib/nomis_client/people.rb
app/lib/nomis_client/personal_care_needs.rb
spec/lib/nomis_client/people_spec.rb
spec/lib/nomis_client/personal_care_needs_spec.rb

fix crash when > 10 offenders requested, and also when no personal_care_needs records are returned

P4-875 - crashes when >10 offenders, and when no personal care records

---

lib/tasks/reference_data.rake

- Adds Gwent custodies x2 (P4-882)
- Moves Bedfordshire custodies to Serco (P4-879)

P4-879, P4-882 update supplier allocations

---

Gemfile
Gemfile.lock
app/controllers/api/v1/moves_controller.rb
app/models/location.rb
app/models/move.rb
app/services/moves/finder.rb
spec/factories/location.rb
spec/models/location_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_filter_spec.rb
spec/services/moves/finder_spec.rb

- Adds the `supplier_id` filter to `/api/v1/moves` backporting some scopes from the RBAC branch
- Updates rack and puma to fix the security alerts
Fixes https://dsdmoj.atlassian.net/browse/P4-872

Moves can be filtered by supplier

---

lib/tasks/reference_data.rake

This PR resolves P4-870 by adding the suppliers into the rake task.
In addition, the rake task needs to be run on each environment, and the Redis cache flushed.

P4-870 Add locations to suppliers in reference rake task

---

lib/tasks/reference_data.rake

Suppliers were accidentally removed in https://github.com/ministryofjustice/hmpps-book-secure-move-api/commit/e803188a53514cdb17f6d10d0d414bf358dfcf8b\#diff-93545d02752dae13f98f397c317b0986
This PR re-adds them and sorts the list

P4-929 re-add suppliers

---

spec/swagger_helper.rb

These were omitted from the original introduction of RSwag. There's likely a cleaner way we can achieve this in the long run, but as a first pass to get the models back into the UI it'll do.

Re-add schema definitions to swagger_helper

---

README.md

Minor FIX to the README giving the wrong instruction to run rake tasks.

/%s/rails/rake/g in Create reference data section

---

lib/tasks/reference_data.rake

This PR reintroduces 7 custody suites which were lost at some point:
- Middle Engine Custody Suite - NRU1
- South Tynside Custody Suite - NRU4
- Brighton Custody Suite - SUS1
- Hastings Custody Suite - SUS2
- Worthing Custody Suite - SUS3
- Crawley Custody Suite - SUS4
- Eastbourne Custody Suite - SUS5
It also sorts the locations to make finding them easier. This is split over 2 commits to make the diff easier to check.

P4-870 add locations mk2

---

adr/0001-record-architecture-decisions.md
adr/0002-API-params-naming.md

This PR add a template for ADR (see [Michael Nygard's template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md) )
It also adds a simple ADR about API params naming.

Add ADR to keep track of the Architech Decisions

---

app/services/people/finder.rb
spec/factories/profile.rb
spec/services/people/finder_spec.rb

This is part of the ticket: BE - Add support for nomis_offender_no to the /api/v1/people
We'll need to add the support to search for `nomis_offender_no`, this first PR simplyadd the search by nomis_offender_no to the `People::Finder`
Ticket: https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=303&projectKey=P4&modal=detail&selectedIssue=P4-977

Add support for nomis_offender_no to the /api/v1/people - Part1

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Something to do with our usage of OAuth2::Client means that webmock doesn't work in this project. As we have a consistent API for accessing NOMIS, the lack of webmock can be effectively worked-around by mocking NomisClient::Moves#get_response (et al)

remove webmock (for now) as it doesn't work in this project

---

spec/factories/access_token.rb
spec/factories/application.rb
spec/requests/api/v1/moves_controller_create_spec.rb

Our request specs are somewhat torturous (and extremely slow) as we authenticate for every interaction. This PR demonstrates a more standard doorkeeper mechanism

use standard doorkeeper mechanism for move controller create spec

---

app/controllers/api/v1/people_controller.rb
app/services/moves/import_people.rb
app/services/moves/importer.rb
app/services/people/finder.rb
config/database.yml
spec/lib/nomis_client/people_webmock_spec.rb
spec/requests/api/v1/people_controller_index_spec.rb
spec/services/moves/import_people_spec.rb
spec/services/people/finder_spec.rb

This PR add support for the params `nomis_offender_no` to the `People` controller.
Also, whenever `nomis_offender_no` is used, it update the data regarding the Person from Nomis.
(Note that the way we sync this could change in the future)
Tech Details:
- A new service `Moves::ImportPeople` was added, to sync just the person
- `Moves::Importer` was refactored to use `Moves::ImportPeople`

Add support for nomis offender id to v1 people endpoint

---

.circleci/config.yml

This uses the slack Orb in CircleCI config to only alert the channel
on master failures, not branches.

Only notify slack on CircleCI failures

---

lib/tasks/reference_data.rake

Fixes P4-1080
Move SCH9 (Vinney Green) from Serco to GeoAmey (linked in error)
run rake reference_data::link_suppliers on env after deploy. Check that VinneyGreen (SCH9) only linked to GeoAmey and not to Serco
rake reference_data::link_suppliers

move SCH9 from serco to GeoAmey due to error

---

lib/tasks/fake_data.rake
lib/tasks/move_profile.rake

Part of P4-885
- Backfill task so that the migration can be deployed without having to do all the back-filling
- rake move_profile:backfill
- task need to be run on production a few times so that actual migration is quick

P4-885 step 2 = add task to back-fill profile data

---

app/views/layouts/application.html.erb
app/views/pages/authentication.html.md
app/views/pages/contributing.html.md
app/views/pages/feedback.html.md
app/views/pages/overview.html.erb
app/views/pages/webhooks.html.md

#P4-1038
Fixes P4-1038
* Restores link to webhooks document
* Tweaks documentation following feedback from Ryan
* Moves document links to separate partial
* Old live webhooks doc: https://hmpps-book-secure-move-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/docs/webhooks
* New webhooks doc: https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/P4-1038-further-webhooks-documentation/app/views/pages/webhooks.html.md

Small documentation tweaks for webhooks

---

db/migrate/20200225142710_move_agreed_default_false.rb
db/schema.rb

Fixes problem with existing Move(type: prison_transfer) records where move_agreed was nil, so the validation failed when loading and re-saving
- make move_agreed non-nullable defaulting to false
- check that rake move_profile:backfill_moves can be executed

add default to move_agreed so that old data is still valid

---

.circleci/config.yml

This updates the CircleCI workflow to only run production jobs and
the approval process on Git tags.
This will prevent the master status showing as "On hold" on merges.

Only run production build/deploy jobs on Git tags

---

app/controllers/api/v1/moves_controller.rb
app/serializers/move_serializer.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/swagger/definitions/move.json
swagger/v1/move.json

Add support for the fields:
- move_agreed
- move_agreed_by in the apis
in move endpoints (see specs)
https://dsdmoj.atlassian.net/browse/P4-1077
- [x ] API docs has been updated if necessary

Add support for move_agreed and move_agreed_by in the apis

---

app/controllers/api/v1/moves_controller.rb
app/serializers/move_serializer.rb
app/services/moves/finder.rb
db/migrate/20200226113423_add_index_to_move_created_at.rb
db/schema.rb
spec/requests/api/v1/moves_controller_filter_spec.rb
spec/serializers/move_serializer_spec.rb
spec/swagger/definitions/hand_coded_paths.json
swagger/v1/move.json

Fixes P4-1091
- adds created_at to move model, and created_at_from and created_at_to as filter parameters
- execute query with new parameters, show that created_at date range is respected

P4-1091 added created_at to move with filters

---

app/serializers/prison_transfer_reason_serializer.rb
db/migrate/20200302115111_add_disabled_at_to_transfer_reason.rb
db/schema.rb
spec/serializers/prison_transfer_reason_serializer_spec.rb
swagger/v1/prison_transfer_reason.json

Fixes P4-1114
- Adds disabled_at to prison transfer reason
- call prison_transfer_reasons endpoint and see disabled_at property for a disabled entity

p4-1114 add disabled_at to prison_transfer_reasons entity

---

app/services/people/finder.rb
spec/services/people/finder_spec.rb

This is something necessary to completed `P4-1125`
I realized the lack after the merge.
Update people filter with prison_number.
Try to filter the get /people  filtering by prison_number

Update filter for people with prison_number

---

config/database.yml

Issue: 
If you run Postgress by Docker,
and you issue: `bundle exec rake db:create` you get the following error:
```
> bundle exec rake db:create
Created database 'pecs-move-platform-backend'
could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Couldn't create 'pecs_move_platform_backend_test' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/Users/ale/.rvm/gems/ruby-2.6.2/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
/Users/ale/.rvm/gems/ruby-2.6.2/gems/pg-1.0.0/lib/pg.rb:56:in `new
...
```
This is fixed …

Specify localhost in database.yml

---

.rubocop.yml
app/controllers/api/v1/moves_controller.rb
app/models/move.rb
app/serializers/move_serializer.rb
db/migrate/20200302102905_move_add_date_from_to.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
swagger/v1/move.json

Fixes P4-1104
- Adds a date_from and date_to field to the 'Move' object
- add a date_from and date_to to a 'move update' and see that the move gets updated
- [X ] API docs has been updated if necessary

P4 1104 add date_from and date_to to move entity

---

spec/requests/api/v1/documents_controller_create_spec.rb
spec/requests/api/v1/documents_controller_destroy_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_destroy_spec.rb
spec/requests/api/v1/moves_controller_filter_spec.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/requests/api/v1/moves_controller_role_access_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/requests/api/v1/people_controller_create_spec.rb
spec/requests/api/v1/people_controller_index_spec.rb
spec/requests/api/v1/people_controller_update_spec.rb
spec/requests/api/v1/reference/assessment_questions_controller_spec.rb
spec/requests/api/v1/reference/ethnicities_controller_spec.rb
spec/requests/api/v1/reference/genders_controller_spec.rb
spec/requests/api/v1/reference/identifier_types_controller_spec.rb
spec/requests/api/v1/reference/locations_controller_spec.rb
spec/requests/api/v1/reference/nationalities_controller_spec.rb
spec/requests/api/v1/reference/suppliers_controller_spec.rb
spec/requests/api_controller_spec.rb

Speeds up tests by around 100% (4 minutes -> 2mins 20)
- convert quite a few tests from using request-level actual auth to doorkeeper test auth
- run all tests

port specs to doorkeeper test auth

---

.rubocop.yml
app/services/moves/finder.rb
app/services/moves/params_validator.rb
spec/requests/api/v1/moves_controller_filter_spec.rb

Fixes P4-1142
- Make the created_at_to filter inclusive rather than exclusive (as its a date/time not a date)
- check the created_at_to filter on moves to make sure that it is inclusive

P4-1142 created_at_to search needs to be inclusive

---

app/models/location.rb
app/models/move.rb
lib/tasks/data_maintenance.rake
lib/tasks/fake_data.rake

Fixes P4-1159
- Adds a rake task to cancel NOMIS synched moves from prisons
- run rake data_maintenance:cancel_synched_prison_moves
- rake task has to be run manually

P4-1159 cancel NOMIS synched moves from prisons

---

lib/tasks/fake_data.rake

##Problem
the tasks `recreate_all` takes to long to run and does not have any output.
Improving the tasks `recreate_all`
- puts comment on the various tasks
- speed up the tasks reducting the number of

Improve tasks recreate_all fake data.

---

app/mailers/move_mailer.rb
spec/factories/move.rb
spec/mailer/move_mailer_spec.rb

Fixes P4-1188
- Prison recall moves don't have to locations, so attempt to set them in the email
- create a prison recall move when an email subscription is present - notice that the email arrives

p4-1188 emails for prison recall moves

---

app/mailers/move_mailer.rb
spec/mailer/move_mailer_spec.rb

Fixes P4-1186
- Adds the move-date to the email personalisation fields
- Tested locally
*IMPORTANT* do not alter the email template in govuk_notify service until this code is deployed to production - otherwise all emails will break!

Add move_date to email personalisation

---

.circleci/config.yml
spec/swagger_helper.rb

'dev' environment was missing from the swagger docs, so it is not possible to use swagger
to talk to the dev API

Add missing 'dev' environment to list in docs

---

app/services/people/retrieve_image.rb
spec/services/people/retrieve_image_spec.rb

##Bigfix 
Jira: P4 https://dsdmoj.atlassian.net/browse/P4-1201
Sentry: https://sentry.service.dsd.io/mojds/bookasecuremove-production/issues/45695
If the `latest_nomis_booking_id` is nil it does not get the image from Nomis
Run the enpoint /people/<ID>/images
passing a person with no latest_nomis_booking_id

Fix for empty latest_nomis_booking_id when retrieving image from nomis

---

db/migrate/20200207111034_remove_documents_move_constraint.rb

To do with P4-1200
One of the migrations that we need to re-run on production to fix the documents issue turned out to be irreversible - so this fixes it to be reversible. It was missed during the initial analysis.
Make old migration reversible so that it can be re-run

P4-1200 fix old migration to be reversible

---

.circleci/config.yml

Fixes P4-1189
Note: This replaces PR #349 
Refactor Circle CI build to introduce explicit job for API docs
Previously API documentation using swagger was generated at the end of the test job - this meant a dependency on the build job for the test job to complete, in turn slowing down the overall build pipeline. For the staging environment the test and build jobs were performed in parallel, but that introduced a race condition with the swagger file being unavailable when the docker image is created.
This approach adds a new job to generate the swagger docs which can be added as a dependency for the build job - within this job we still need to install all of the dev and test gems, but don't need to run the full test suite before making the `swagger.yml` file available.
All of the …

P4-1189 Refactor circleci build to introduce explicit job for API docs

---

app/models/person.rb

Fixes P4-1213
Previously this implementation made use of a Tempfile to write and then immediately read back the image content retrieved from Nomis API. That didn't feel like a great technique as the entire image blob is already held in memory at that point as a string. Wrapping the same string with a `StringIO` instance means it can be passed directly to active storage for attachment.
I was able to reproduce a consistent test failure on Circle CI prior to this change, and the same seed passes with the change so it looks very likely that using temp files on Circle CI is a little bit brittle.
Tested `RetrieveImage` service locally and ensured that prisoner images are successfully fetched from Nomis and persisted using active storage when calling `/people/{id}/images` endpoint.

P4-1213 Use StringIO rather than temp file to serialize image blob

---

app/controllers/api/v1/moves_controller.rb
app/controllers/api_controller.rb
app/models/move.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/rails_helper.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/requests/api_controller_spec.rb
spec/support/responds_with_error_422.rb
swagger/v1/errors.json

Fixes P4-1027
- Add validation to move to prevent duplicate creation, but allow multiple cancelled moves
- create a move, then create another move with the same person/to/from/date - nice error message returned
Front-end will not understand this error particularily well - it probably needs some specific work to allow it to cope nicely

P4-1027 Non-unique move return error rather than crashing

---

app/mailers/move_mailer.rb
app/models/move.rb
db/migrate/20200407130150_change_move_date_to_allow_null.rb
db/schema.rb
spec/mailer/move_mailer_spec.rb
spec/models/move_spec.rb
swagger/v1/move.json

Fixes P4-1263
Proposed moves will not specify a date, but will specify a date_from and may specify a date to. This updates the date validation rules on Move model accordingly to make them conditional on the appropriate move status. This also extends the variables passed to notification emails to include date_from and date_to, with those and also date defaulting to `N/A` if nil. This then allows the notify email template to be updated in a subsequent ticket to support from/to dates while also ensuring that nothing breaks in the meantime.

P4-1263 Update date validation rules around proposed moves

---

spec/requests/api/v1/moves_controller_create_spec.rb
swagger/v1/move.json

Fixes P4-1263
This is an optional field now (for proposed moves) so the API needs to allow values of either `nil` or a date. Updated API spec to reflect this behaviour and demonstrate successful creation of proposed move.
- See updated API spec

P4-1263 Minor tweak for move date attribute API spec

---

.circleci/config.yml
docs/pull_request_template.md

We've just deployed a new api and our frontend team have noticed that we're missing a bunch of sections that they're interested in interfacing with.
The problem that was causing this is that we're using the swaggerize rake task after a recent change https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/352 where we were previously running all of the tests.
The swaggerize task doesn't match our rspec directory pattern (`spec/swagger/api/v1/*`) so they don't get run (see: [swaggerize rake task](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/tasks/rswag-specs_tasks.rake#L11))
- Stop using swaggerize to generate documentation since we don't have a pattern that rswag expects
- Check documentation in staging

Fixes broken swagger documentation generation

---

app/models/move.rb
spec/factories/move.rb
spec/models/move_spec.rb

Fixes P4-1263
Proposed moves will initially set a `nil` date on creation, and may then be updated to specify a potential fixed date. We should only enforce validation of a unique move date when the move changes to requested or completed state. Updated model and specs.
This was preventing more than one proposed move being created for the same person, from location and to location (was reported as working intermittently).

P4-1263 Updated unique date validation to exclude proposed moves

---

spec/swagger/api/v1/people_controller_image_spec.rb

The images endpoint documentation differs from the existing endpoints.
This change updates the name of the person parameter to be consistent.

Fix ID parameter in person/images endpoint

---

spec/swagger/api/v1/court_hearings_controller_create_spec.rb
spec/swagger/definitions/court_hearing.json
swagger/v1/court_hearing.json

P4-1316
- Run passed Dom/Jonny

P4-1316 fix court hearing swagger

---

app/lib/nomis_client/court_hearing.rb
app/services/court_hearings/create_in_nomis.rb
spec/services/court_hearings/create_in_nomis_spec.rb

This PR allow to Save the CourtHearing.post response and Fix the time format (UTC)
In case the response is not 201 it pushes the result to sentry to easily debug the error.

Save the CourtHearing.post response and Fix the time format

---

app/models/allocation.rb
db/migrate/20200415091520_create_allocations.rb
db/schema.rb
spec/factories/allocation.rb
spec/models/allocation_spec.rb

Fixes P4-1274
This is the first pass that does not yet support associating people with the allocation (that will come in a later sprint). Eventually it's likely that an allocation will support a collection of moves, but that's also out of scope for the time being, as is allocation status. I've elected to use JSON storage for the complex case flags - the same approach is used elsewhere e.g. assessment answers to avoid over normalising the schema.
This PR doesn't do much yet, but I'm keen to get agreement on model & attribute names before proceeding further to add API docs etc.

P4-1274 Added data model to support allocations

---

app/lib/nomis_client/court_hearing.rb
app/services/court_hearings/create_in_nomis.rb
spec/lib/nomis_client/court_hearings_spec.rb
spec/services/court_hearings/create_in_nomis_spec.rb

This PR fixes the way sentry notifies when creating court hearings.

Fix sentry for create court hearing

---

spec/lib/nomis_client/court_hearings_spec.rb
spec/rails_helper.rb

CI is broken because our mocking in court hearing client spec is breaking the other mocks in our suite.
- Marks court hearing client specs as pending

CourtHearing client specs are breaking mocks to Nomis

---

.circleci/config.yml

We currently install all dependencies over the wire over and over.
Specify cache directory for bundled gems so that we actually can restore from a cache.
We already had the caching functionality configured but we weren't using it because we weren't installing to the correct path

Speed up circle ci builds by using cached deps

---

spec/lib/nomis_client/court_hearings_spec.rb

We recently made some specs pending so we could carry on validating an integration with nomis to create court hearings in staging. The way we were mocking was leaking into other tests in the suite

Reinstates pending court_hearings_spec examples

---

.env.example

[P4-1250](https://dsdmoj.atlassian.net/browse/P4-1250)
- This is not the way the setup docs prescribe to configure the database.

Removes unused env var

---

Rakefile

P4-<TODO>
The Rakefile is loaded when building Docker images for production
- To fix broken builds

Fixes Rakefile for production environment

---

app/controllers/api/v1/allocations_controller.rb
app/serializers/allocation_serializer.rb
app/services/allocations/finder.rb
app/services/allocations/params_validator.rb
config/routes.rb
lib/tasks/fake_data.rake
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/serializers/allocation_complex_case_serializer_spec.rb
spec/serializers/allocation_serializer_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/allocations/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths.json
spec/swagger_helper.rb
swagger/v1/allocation.json
swagger/v1/get_allocations_responses.json

P4-1274
- This supports the front end functionality

P4-1274 Add new endpoint to GET /allocations

---

app/controllers/api/v1/people_controller.rb
app/controllers/api_controller.rb
app/lib/nomis_client/api_error.rb
app/lib/nomis_client/base.rb
app/serializers/nomis_api_error_serializer.rb
app/services/people/retrieve_court_cases.rb
spec/lib/nomis_client/api_error_spec.rb
spec/lib/nomis_client/base_spec.rb
spec/lib/nomis_client/court_cases_spec.rb
spec/requests/api/v1/people_controller_court_cases_spec.rb
spec/services/people/retrieve_court_cases_spec.rb
spec/swagger/api/v1/people_controller_court_cases_spec.rb

Jira link: https://dsdmoj.atlassian.net/browse/P4-1261
- Fix error propagation from Nomis Api Calls
- Add Api:Json error in Get people#court_cases
Note: this PR is not yet handling the Timeout error, a new PR will follow soon
To give more info to the caller about Nomis failures.
To have a standard way to handle errors (Api:Json)

Nomis Error handling

---

lib/tasks/data/supplier_locations.yml

https://dsdmoj.atlassian.net/browse/P4-1377
Update supplier location:
- Link PRI to GeoAmey
- Link BZI to Serco
there are more location supported 
REMEMBER to run the task:
`rake reference_data:link_suppliers`
to update the locations for the suppliers

Update supplier location:

---

app/lib/nomis_client/activities.rb
app/lib/nomis_client/court_hearings.rb
spec/lib/nomis_client/activities_spec.rb
spec/lib/nomis_client/court_hearings_spec.rb

P4-<TODO>
- The retrieval services expect parsed json from the client

Fix timetable after integration highlighted bug

---

app/models/move.rb
app/serializers/move_serializer.rb
db/migrate/20200428134954_remove_null_constraint_from_person_on_moves.rb
db/schema.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/serializers/move_serializer_spec.rb
swagger/v1/move.yaml

[P4-1385](https://dsdmoj.atlassian.net/browse/P4-1385)
When a PMU allocation is created, we would like to associate it with moves, for each of the people required for the allocation. However at the time moves are created, they will not be associated with a person, as those will be added later by the OCA.
Allow a move to be created without a person, only if it is a request or a cancellation. As proposed moves coming from the singleton flow always will require a person associated, while moves created for an association will always start with the request status.
Also validate on uniqueness of date unless the person is not associated with a move to not group `nil` people moves together created for an allocation and deem them as invalid.

P4-1385 Allow move creation and serialisation without a person

---

app/controllers/api/v1/court_hearings_controller.rb
spec/requests/api/v1/court_hearings_controller_create_spec.rb
spec/swagger/api/v1/court_hearings_controller_create_spec.rb

P4-1422
Update default behaviour when creating a hearing in Nomis
The original implementation breaks the frontend flow.

[P4-1422] Change to defaulting to creating a court hearing in Nomis

---

app/serializers/timetable_serializer.rb
swagger/v1/timetable_entry.yaml

P4-1413
- Pluralization libs don't understand this type

[P4-1413] Change plural form of timetable

---

.rubocop.yml
app/controllers/api/v1/moves_controller.rb
spec/requests/api/v1/moves_controller_update_spec.rb
swagger/v1/document_reference.yaml
swagger/v1/move.yaml

P4-1392
The frontend are creating a page for viewing and changing a move's documents and they need this for associating/disassociating created documents with the move.

P4-1392 Patch a moves document relationships

---

app/controllers/api/v1/allocations_controller.rb
app/services/allocations/finder.rb
app/services/allocations/params_validator.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/allocations/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths.yaml
swagger/v1/pagination_parameters.yaml

P4-1275
This is needed to support a few front end scenarios around allocations; we've decided to let the front end handle the concept of regions so rather than passing a region to filter allocations on, it will pass a list of location id's to filter on (which will eventually be derived from a regions reference data endpoint).
- The API is still not used in production so is risk free

P4-1275 Added support for filtering by location on GET /allocations endpoint

---

app/lib/nomis_client/api_error.rb
spec/lib/nomis_client/api_error_spec.rb

P4-1444
When the Nomis app isn't routeable from the Azure API Gateway the API Gateway returns a html error and 502 status code. The elite2api is a json api so we hadn't previously added handling for non-json mime types.
This adds a special condition in the html case and returns a cleaner error message to the frontend/supplier.
This is quicker/simpler than getting an infrastructure change to update the default error templates.

[P4-1444] Handle unparseable errors from Azure API Gateway

---

lib/tasks/move_profile.rake

https://dsdmoj.atlassian.net/browse/P4-1449
Update the profile_in the moves, with the the profile that was most recently updated.
This is the first step to change the relationship Move-Person to Move-Profile
run the rake task
`bundle exec rake moves:set_profiles`

Data migration to update profile ID with the correct profile.

---

app/controllers/api/v1/move_events_controller.rb
app/controllers/api/v1/people_controller.rb
app/jobs/prepare_move_notifications_job.rb
app/jobs/prepare_person_notifications_job.rb
app/models/move.rb
app/services/notifier.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/jobs/prepare_person_notifications_job_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/move_events_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/requests/api/v1/people_controller_create_spec.rb
spec/requests/api/v1/people_controller_update_spec.rb
spec/services/notifier_spec.rb

[P4-1357](https://dsdmoj.atlassian.net/browse/P4-1357)
- the "update a move" workflow in the frontend actually patches the profile (/people) and currently doesn't trigger notifications
- Will send duplicate emails; this is a known and accepted limitation

P4 1357 patch people notifications

---

app/serializers/location_serializer.rb
spec/serializers/location_serializer_spec.rb

P4-1433
This [pr](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/143/)
incorrectly added a suppliers relationship as one of the attributes of
the LocationSerializer.
This code never returns SupplierSerializer objects and actually returns the result of just calling Location#suppliers so I can't see any harm removing it. AMS eventually just calls to_json on instances of Supplier and never uses the SupplierSerializer.
In a separate PR/in future I propose we remove the attribute `suppliers` that are each getting `Supplier#to_json` called on them everytime we return a location and instead use includes/relationships in the way specified by json:api.
- This code is not used

[P4-1433] Removes unused supplier serializer code

---

app/models/location.rb
app/models/region.rb
app/services/regions/importer.rb
db/migrate/20200506105933_create_regions.rb
db/schema.rb
lib/tasks/data/regions.yml
lib/tasks/reference_data.rake
spec/services/regions/importer_spec.rb

P4-1273
- The reference data for this is mastered in the back end as the source of truth. Working with a YML file is much simpler and avoids the need to add extra gems (e.g. Roo) to process spreadsheets. We can modify the YML file as needed in future should the regions change.
- Future work will expose a reference data endpoint to return the locations associated with each region
- This is needed for the front end allocations work to allow user to select region of interest
- Rake task `rails reference_data:create_regions` can be run safely as the data is not yet linked to any API endpoints
- Included YML file does not contain any sensitive data

P4-1273 Add importer class to populate regions reference data

---

.rubocop.yml

P4-<TODO>
Our rails app generates a whole bunch of unparseable files that rubocop
opens (see `lsof`) from the tmp/ directory
Most of these files are just bootsnap/spring cache-related and
unnecessary/untouched by us during development.
This adds about 12 seconds to the time it takes to run rubocop:
```bash
time rubocop
________________________________________________________
Executed in   14.62 secs   fish           external
usr time   12.59 secs  120.00 micros   12.59 secs
sys time    0.94 secs  612.00 micros    0.94 secs
time rubocop
________________________________________________________
Executed in    2.12 secs   fish           external
usr time    1.74 secs  127.00 micros    1.74 secs
sys time    0.39 secs  577.00 micros    0.39 secs
```
This should shave 12 seconds off of each test …

Hugely speed up linting

---

app/services/allocations/finder.rb
spec/services/allocations/finder_spec.rb

P4-1462
- In future stories this will be expanded to allow the front end to specify a sort order, but for now we just need to apply a sensible default sort order, showing the most recent planned allocations (by date) first.
- Amends the behaviour of the API, but it's still not used in production

P4-1462 Hard code default sort order for GET /allocations endpoint

---

spec/requests/api/v1/moves_controller_update_spec.rb

This sometimes fails for me but I found a seed (65033) that reliably reproduced the problem. Looks to just be (incorrectly) expecting documents to be returned in a specific order rather than just checking for the correct documents.

Fix flaky specs

---

README.md

I missed this when previously adding these tasks, didn't realise they were documented in the README too.

Add recent rake tasks for reference data to README

---

.circleci/config.yml
spec/services/regions/importer_spec.rb

Run rubocop before tests in circle build to fail fast, and fix flakey test because no one likes flakiness

Fail fast and fix flakey test

---

app/controllers/api/v1/moves_controller.rb
spec/requests/api/v1/moves_controller_update_spec.rb

P4-<TODO>
Adds support for patching a move without any attribute changes (i.e. only the documents)
This is a genuine use case of this api.

Handle missing attributes when patching a moves documents

---

app/services/personal_care_needs/importer.rb
spec/services/moves/import_people_spec.rb
spec/services/personal_care_needs/importer_spec.rb

P4-1185
The initial implementation of the AssessmentAnswer documents for personal care needs was only for female prisons where the person might be pregnant.
This updates the default question to be more appropriate for a wider gamut of people we might move.
This is principally a UX change that will make using our service make more sense.

[P4-1185] Updates default fallback question for building personal care need

---

app/controllers/api/v1/moves_controller.rb
app/serializers/move_serializer.rb
spec/factories/move.rb
spec/serializers/move_serializer_spec.rb
spec/swagger_helper.rb
swagger/v1/allocation_reference.yaml
swagger/v1/get_moves_responses.yaml
swagger/v1/move.yaml

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1466
[P4-1466](https://dsdmoj.atlassian.net/browse/P4-1466)
We would like to surface allocations if they are associated with a move on the moves and move get endpoints. These allocations should appear as a relationship, as well as in detail in the  included section
I also fixed bug in the move serializer where we aren't utilising the correct format for only including fields vs objects. These need to be separated. The `include` key will handle what objects we expect to return, while the `fields` key determines which fields we only want to return per object. After speaking to Dom, we would like to start limiting fields as we go rather to not break current included objects. We are now only limiting allocations, but all other objects will …

P4-1466 Surface an allocation associated to a move

---

app/serializers/allocation_serializer.rb
spec/factories/allocation.rb
spec/rails_helper.rb
spec/requests/api/v1/allocations_controller_create_spec.rb
spec/serializers/allocation_serializer_spec.rb
swagger/v1/allocation.yaml
swagger/v1/get_allocations_responses.yaml
swagger/v1/move_reference.yaml

[P4-1398](https://dsdmoj.atlassian.net/browse/P4-1398)
We would like to surface moves in the allocation endpoints. Moves should also surface people in `includes` if there are any associated with them.
There are two issues I'd like to address in the current implementation:
1) We are including a circular dependency in the `moves` include response where it will also surface the allocation in the relationship.
2) Inferring moves count rather than including an extra attribute

P4-1398 Surface associated moves in allocations

---

.env.example
app.json
app/controllers/api_controller.rb

P4-1428
During local development, the API authentication (and in particular the oauth timeout) is pretty irksome, meaning workarounds (e.g. Postman utility scripts) are needed to continually refresh the token. In most case we just want to test the API without worrying about which supplier invoked the API call.
Similarly for Heroku review apps, these would be much easier to use against front end if we didn't have to worry about generating oauth API credentials and communicating these to the front end team. Instead, with this change front end devs will be able to simply specify the API URL for the deployed review app and everything should work within the API as intended.
There are some caveats to this:
1. Clearly setting an environment variable in production mode that bypasses …

P4-1428 Allow disabling API authentication for local dev and heroku review apps

---

app/controllers/api/v1/moves_controller.rb
app/models/move.rb
app/models/person.rb
app/models/profile.rb
app/serializers/move_serializer.rb
app/services/court_hearings/create_in_nomis.rb
app/services/moves/finder.rb
lib/tasks/move_profile.rake
spec/factories/move.rb
spec/jobs/prepare_person_notifications_job_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_destroy_spec.rb
spec/requests/api/v1/moves_controller_sorting_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/serializers/move_serializer_spec.rb
spec/services/court_hearings/create_in_nomis_spec.rb
spec/services/moves/reference_generator_spec.rb
spec/services/people/retrieve_image_spec.rb

https://dsdmoj.atlassian.net/browse/P4-1450
This add the relationship Move-Profile
and remove the Move-Person
Also, this PR update the `set_profiles` rake task,
so it can run without using the `move.person` relationship.
We must keep the the API interface exactly the same. That is why I did not touch any expected swagger response.

Add profile relationship to Move

---

.circleci/config.yml

This change copies across the notifications from the frontend workflow
to notify the team slack channel of releases being prepared, needing
deployment approval and when they have been successfully deployed.
It also changes the deployment of pre-production to only be done for
releases so that it will more closely mimic production rather than
always containing the latest master changes.
*Click images to enlarge*
- no changes
| Before | After |
| ------ | ----- |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/81823680-73ac6900-952c-11ea-81e2-c5f88f8d54fe.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/81821863-4f4f8d00-952a-11ea-8dc9-4fff8112217e.png"></kbd> |
- will no longer build and deploy to pre-production
| Before | After |
| ------ | …

Add slack notifications to CI workflow

---

README.md
app.json
lib/tasks/reference_data.rake

P4-1428
- Heroku main API app now works as expected and contains reference data so the API endpoints work. Authentication is currently disabled on the Heroku review apps but enabled for the main app. This protects the known good "reference" data - we need to keep that clean and lightweight and use the disposable copies on review apps for testing.
- In the near future I'm hoping that we'll be able to run the end to end test suite against a deployed Heroku review app and get that passing. This would then allow stronger testing of any API changes to ensure that no regressions are introduced.

P4-1428 Replicate review app database from main heroku API app

---

app/models/allocation.rb
app/services/allocations/creator.rb
spec/factories/allocation.rb
spec/models/allocation_spec.rb
spec/requests/api/v1/allocations_controller_create_spec.rb

P4-1525
- This was previously throwing an error when creating an allocation passing `moves_count` as a string value. This blew up within the `Allocations::Creator` service but didn't get caught as a validation error. It turns out Rails is extremely forgiving and will automatically convert string to integer values within the `Allocation` model; the problem was that the creator then used the raw params passed in rather than the allocation attributes. The same code was also relying solely on the presence of a `date` param to determine validity prior to creating associated moves.
- Refactored implementation means that moves are explicitly created after confirming that the allocation is valid, and to use the allocation attributes to build the moves rather than the params. This also allows …

P4-1525 Improve validation of `moves_count` when creating an allocation

---

app/controllers/api/v1/moves_controller.rb
app/services/moves/updater.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/services/moves/updater_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1530
[P4-1530](https://dsdmoj.atlassian.net/browse/P4-1530)
* Move update logic to service
* Allow a person to be updated on a move
* If no person relationship is set on a move do not update the association
* If nil data is set on a move param remove any associated person
To allow a person to be associated to a move on the allocation workflow, amend the PATCH endpoint to accept a person relationship to link/unlink people to that move

P4-1530 Allow person to be updated on a move

---

app/controllers/api/v1/allocation_events_controller.rb
app/models/allocation.rb
app/models/move.rb
app/serializers/allocation_serializer.rb
app/services/allocation_events/params_validator.rb
config/routes.rb
db/migrate/20200514052159_add_status_to_allocations.rb
db/migrate/20200514055112_add_cancellation_reason_and_comment_to_allocations.rb
db/schema.rb
spec/models/allocation_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/allocation_events_controller_create_spec.rb
spec/serializers/allocation_serializer_spec.rb
spec/services/allocation_events/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths.yaml
swagger/v1/allocation.yaml
swagger/v1/allocation_event_name_attribute.yaml
swagger/v1/allocation_id_parameter.yaml
swagger/v1/get_allocation_event.yaml
swagger/v1/move.yaml
swagger/v1/post_allocation_event.yaml
swagger/v1/post_allocation_events_responses.yaml

[P4-1441](https://dsdmoj.atlassian.net/browse/P4-1441)
- Add a status to an allocation. An allocation can have 3 statuses: filled, unfilled and cancelled. We will now only implement cancelled
- Add events to allocation to allow for setting the status
- Add cancellation reason and comment to an allocation 
- Add allocation events create path
To allow the cancellation of an allocation and the associated moves, add a new event endpoint which when set as cancelled will set the new "status" of allocation to cancelled as well as all moves.
The event endpoint is returning a fake response as it is still to be implemented in further work. 
I initially implemented cancellation reason but then it got de-scoped later on, so I kept the implementation to avoid having to redo this.
- Includes …

P4-1441 Cancel allocations

---

README.md
app/controllers/api/v1/moves_controller.rb
app/models/move.rb
app/models/person.rb
app/models/profile.rb
app/models/supplier.rb
app/serializers/move_serializer.rb
app/services/court_hearings/create_in_nomis.rb
app/services/moves/finder.rb
app/services/moves/updater.rb
lib/tasks/data/supplier_locations.yml
lib/tasks/move_profile.rake
spec/factories/move.rb
spec/jobs/prepare_person_notifications_job_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_destroy_spec.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/requests/api/v1/moves_controller_sorting_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/serializers/move_serializer_spec.rb
spec/services/court_hearings/create_in_nomis_spec.rb
spec/services/moves/reference_generator_spec.rb
spec/services/moves/updater_spec.rb
spec/services/people/retrieve_image_spec.rb

P4-1450
Moves in the database can come in three forms:
1. With a profile (what we're moving too in this PR)
2. With a person (previous implementation)
3. With neither (for the allocations work)
We've recently committed to moving away from the person reference on a profile but didn't realise that the state for existing moves that hadn't yet been migrated using the rake task was still referencing a person but not referencing a profile.
This meant that our serializer which pulls out a nil person was nullifying the person returned in the index (although others, too) controller action.
This PR:
This work is needed as part of making our person and profile models actually make sense conceptually and is part of a larger refactor that we're currently iterating on.
We've written extra tests to …

[P4-1450] Migrate a moves reference from a Person to a Profile

---

app/controllers/api/v1/reference/regions_controller.rb
app/serializers/region_serializer.rb
config/routes.rb
spec/factories/region.rb
spec/models/region_spec.rb
spec/requests/api/v1/reference/regions_controller_spec.rb
spec/serializers/region_serializer_spec.rb
spec/services/regions/importer_spec.rb
spec/support/json_schemas.rb
spec/swagger/definitions/hand_coded_paths.yaml
spec/swagger_helper.rb
swagger/v1/allocation.yaml
swagger/v1/get_regions_responses.yaml
swagger/v1/location_reference.yaml
swagger/v1/move_reference.yaml
swagger/v1/region.yaml

P4-1384
- The front end work for allocations will soon allow user to choose a region to work with; this provides a list of locations that can then be used to scope the visible locations for the user, as well as filter the relevant list of prisons when creating an allocation.
- This is a new api endpoint, so no risk to production

P4-1384 GET /reference/regions API endpoint

---

spec/requests/api/v1/moves_controller_sorting_spec.rb

- the test `rspec ./spec/requests/api/v1/moves_controller_sorting_spec.rb:214` fails occasionally without good reasons 🤔

Clearer last_name sorting test

---

lib/tasks/move_profile.rake

This is a small but valuable fix.
This PR fixes the output of the number of total profiles that has been updated in the set_profile_from_person data migration.

Fix output for set_profile_from_person rake

---

app/controllers/api/v1/allocations_controller.rb
app/serializers/allocation_serializer.rb
db/migrate/20200519120027_add_requested_by_to_allocations.rb
db/schema.rb
spec/factories/allocation.rb
spec/requests/api/v1/allocations_controller_create_spec.rb
spec/serializers/allocation_serializer_spec.rb
swagger/v1/allocation.yaml

P4-1474
- This may be passed by the front end when creating an allocation, and should contain the name of the user within PMU creating the allocation.
- The attribute is optional and may be omitted entirely from the JSON request payload so that this change can be merged ahead of the front end implementation to include this new field.
- Changes an api (in a non breaking way) that is used in production

P4-1474 Add support for optional `requested_by` attribute in allocation model

---

app/controllers/api/v1/moves_controller.rb
app/services/moves/finder.rb
spec/requests/api/v1/moves_controller_filter_spec.rb
spec/services/moves/finder_spec.rb
spec/swagger/definitions/hand_coded_paths.yaml

To filter on moves with an allocation association, add a new filter
to either return all moves with an allocation if set to true, or to exclude
all moves associated to an allocation if set to false
P4- todo: create ticket 🥚 🐔 
https://dsdmoj.atlassian.net/browse/P4-1560
To filter on moves with an allocation association, add a new filter
to either return all moves with an allocation if set to true, or to exclude
all moves associated to an allocation if set to false

P4-1560 Add allocation filter to moves endpoint

---

Gemfile.lock

Remove rubocop-rspec from lock file as it's been removed from our gems

Remove rubocop-rspec from lock file as it's been removed from our gems

---

app/controllers/api/v1/allocations_controller.rb
app/services/allocations/finder.rb
spec/factories/allocation.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/services/allocations/finder_spec.rb
spec/swagger/definitions/hand_coded_paths.yaml

P4-1561
- This supports front end work to exclude cancelled allocations in certain circumstances.
- Changes an api that is used in production, but in a non destructive way. Behaviour is unchanged if new filter parameter is not specified, so is backwards compatible.

P4-1561 Add support for filtering GET /allocations by status

---

app/controllers/api/v1/moves_controller.rb
app/serializers/allocation_serializer.rb
app/serializers/move_serializer.rb
app/serializers/person_serializer.rb
spec/requests/api/v1/moves_controller_index_spec.rb

P4-1497
We are expecting includes to come from the query param in the following format:
`?include=gender,location,person.profile`
Which gets parsed by rails/rack as:
```ruby
"include" => [
"gender",
"location",
"person.profile"
]
```
This format is supported by AMS in addition to the current format we're using.
This PR moves our current includes to the same format that comes from the query params to avoid doing things in more than one way and to simplify our setup.
To simplify our setup

[P4-1497] Prepare includes

---

Gemfile.lock

https://dsdmoj.atlassian.net/browse/P4-1567
I've bumped the version of the doorkeeper gem to the latest stable version.
The locked version of the Gem seems to have been bumped up automatically to the next minimal version that satisfied a dependency, but that particular version was causing a rake task to fail.
As suggested by  @martyn-w, bumping it to the latest stable version fixes the problem.
Changing this Gem version did not had adverse effects on the outcome of the tests or on the generation of client application IDs

[P4-1567] Fix create_client_application rake task

---

Gemfile.lock

This reverts commit 77aa6d4f358354a1ab4c48ff35c7e3928807e826, reversing
changes made to 7a312279d07b8db0f48e01f1a07f5f5dcfd16185.
There seems to be some issue with the gem that was updated and active record.
We are reverting this change for now and will investigate further.

Revert "Merge pull request #486"

---

app/models/allocation.rb
app/services/moves/updater.rb
lib/tasks/fake_data.rake
spec/models/allocation_spec.rb
spec/requests/api/v1/allocation_events_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/services/moves/updater_spec.rb
swagger/v1/allocation.yaml

P4-1554
- Allocation `moves_count` attribute should always reflect the number of associated non-cancelled moves. This can then be used reliably for the front end dashboard stats. Note that this PR does **not** change the allocation moves relationship, which still includes cancelled moves.
- When the allocation is first created, the `moves_count` attribute is used to create a number of associated moves with `requested` status, so the `moves_count` attribute on the allocation is correct at that point. Subsequently, the allocation cannot be changed but may be cancelled. Additionally the associated moves may be changed - notably to amend their status.
- If the allocation is cancelled completely, the `moves_count` should be set to zero as all of the associated moves are now cancelled.
- If a …

Allocation `moves_count` now includes only non cancelled moves

---

db/migrate/20200526152251_adds_fields_to_people.rb
db/schema.rb

P4-1435
It makes way more sense to have relatively-infrequently changing `Profile` attributes on a `Person`.
A `Profile` is expected to change every `Move` potentially and a new one should be created for the `Move`.
The full list of `Profile` attributes are:
```ruby
t.uuid "person_id", null: false
t.string "last_name", null: false
t.string "first_names", null: false
t.date "date_of_birth"
t.string "aliases", default: [], array: true
t.uuid "gender_id"
t.uuid "ethnicity_id"
t.uuid "nationality_id"
t.datetime "created_at", null: false
t.datetime "updated_at", null: false
t.jsonb "assessment_answers"
t.jsonb "profile_identifiers"
t.string "gender_additional_information"
t.integer "latest_nomis_booking_id"
```
A profile should contain frequently changing assessments and personal care needs …

[P4-1435] Adds migration for extra person fields

---

app/controllers/api/v1/allocation_events_controller.rb
app/models/allocation.rb
app/models/move.rb
app/services/moves/updater.rb
app/state_machines/allocation_state_machine.rb
lib/tasks/refresh_allocation_data.rake
spec/factories/allocation.rb
spec/models/allocation_spec.rb
spec/models/move_spec.rb
spec/requests/api/v1/allocations_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/moves/updater_spec.rb
spec/state_machines/allocation_state_machine_spec.rb

[P4-1555](https://dsdmoj.atlassian.net/browse/P4-1555)
To ensure that we update an allocation status with filled/unfilled correctly we need to update the status when a move is updated. When a move is linked/unlinked to a profile or when its status changes (all done through the PATCH endpoint for a move for now) a trigger to update the `moves_count` and the `status` is done. We are utilising a state machine for the allocation for all the different steps. 
- A status is filled if all **non cancelled moves** are associated with profiles
- A status is unfilled if no **non cancelled moves** are associated with profiles
- A status is unfilled if some **non cancelled moves** are associated with profiles
- A status is unfilled if all moves are cancelled
Since we have …

P4-1555 Enhance Allocation status

---

app/services/person_populator.rb
db/migrate/20200529085159_fix_fields_on_person.rb
db/schema.rb

P4-1435
- Adds `last_synced_with_nomis` to **People**
- Adds `last_synced_with_nomis` to **Profile**
- Removes `latest_nomis_booking_id` from **People**
After talking we realised it would be valuable to have some audit
information for when a person and profile were last synced
with Nomis.
The booking id should exist on the latest profile because it changes
each time a person receives a new booking in a prison from Nomis

[P4-1435] Fixes fields on a person

---

.gitignore
Dockerfile
README.md
docker-compose.yml
run.sh

P4-1563
- The current docker image is too big ~1.6GB, which takes a longer than desirable to download, delaying pod start.
- Reduces the CVE footprint by not having a full ubuntu/OS distro running in the container
- This PR does not change anything on the application resources or ruby/gem version. It changes however the underling OS and uses different implementation of some system libraries, which might have an impact on natively built gems.  This is considered to be very low risk as alpine is generally used in production for a number of workloads, including ruby, node, java, etc. 
The current test suites don't validate a running image, so testing was done by manually poking some API endpoints.

[P4-1563] Improve docker image size

---

app/controllers/api/v1/people_controller.rb
app/serializers/person_serializer.rb
spec/requests/api/v1/people_controller_index_spec.rb

P4-1502
Support query includes params in PeopleController
Reduce query burden on backend api and be consistent with json:api standards.
Docs are getting updated for all endpoints at the end.

[P4-1502] Adds support for query includes in PeopleController

---

app/models/journey.rb
app/state_machines/journey_state_machine.rb
spec/models/journey_spec.rb
spec/requests/api/v1/journeys_controller_create_spec.rb
spec/requests/api/v1/journeys_controller_show_spec.rb
spec/serializers/journey_serializer_spec.rb
spec/state_machines/journey_state_machine_spec.rb
swagger/v1/get_journey.yaml
swagger/v1/journey_event_name_attribute.yaml

[P4-1562](https://dsdmoj.atlassian.net/browse/P4-1562)
- suppliers have requested this state
- minimal - not currently being used

P4-1562 add proposed journey state

---

app/controllers/api/v1/allocations_controller.rb
app/services/allocations/finder.rb
app/services/allocations/params_validator.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/allocations/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths.yaml

P4-1380
- This is required to support sorting allocation results in the front end
- Both of the new parameters are optional and named with the same convention as `GET /moves` endpoint
- If neither are specified the default sort order is descending date (i.e. most recent allocations first) which matches the existing behaviour prior to this PR
- Changes a production api, but only if additional parameters are specified. The new parameters are optional so this is backwards compatible with the existing front end and can be deployed first.

P4-1380 Add support for sorting on GET /allocations endpoint

---

spec/factories/location.rb
spec/rails_helper.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/requests/api/v1/journeys_controller_index_spec.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/requests/api/v1/moves_controller_role_access_spec.rb
spec/requests/api/v1/reference/locations_controller_spec.rb
spec/requests/api/v2/people_controller_index_spec.rb
spec/support/with_pagination.rb

Set a different Kaminari page default in tests. Where previously it equated to 20, set it to 5 instead and amend tests to create less fixtures. 
Also move pagination tests to a shared example.

Reduce number of fixtures created for pagination tests

---

app/controllers/api/v1/moves_controller.rb
app/services/moves/updater.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/requests/api/v1/moves_controller_update_spec.rb
spec/services/moves/updater_spec.rb
swagger/v1/move.yaml

[P4-1582](https://dsdmoj.atlassian.net/browse/P4-1582)
Allow a move to be created or updated by either passing in a profile id or person id (where latest profile will be associated to a move) in relationships. The profile will take precedence unless a person id is passed in on creation. It will also take precedence with validation errors. On updates the ability has been added to either unlink an existing profile or update it to a new one. 
After migration of profiles/people is complete on moves, all person setting logic is to be cleaned up.

P4-1582 Allow profiles to be associated to moves on POST/PATCH endpoints

---

app/services/include_params_validator.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/services/include_params_validator_spec.rb

P4-1617
Jira link: https://dsdmoj.atlassian.net/browse/P4-1617
We've added a generic validator, see:
https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/530
This validator shares a supported relationships list with Active Model
Serializers.
AMS supports implicit and explicit forms of include query param chains
and we want our validator to support both to match this.
For example:
'foo.bar.baz' is equivalent to ['foo', 'foo.bar', 'foo.bar.baz'] in
AMS and ['foo.bar.baz'] in our validator
- Makes our api more flexible and consistent

[P4-1617] Support explicit and implicit nested chains for includes

---

db/migrate/20200603142002_change_null_move_agreed.rb
db/schema.rb
lib/tasks/data_maintenance.rake
spec/requests/api/v1/moves_controller_create_spec.rb
swagger/v1/move.yaml

P4-1608
- `move_agreed` is not specified by the front end when creating a move initially, but the request succeeds because the model is automatically defaulting the attribute to false. This is incorrect behaviour (although was seemingly intentionally added in a migration previously):
```ruby
class MoveAgreedDefaultFalse < ActiveRecord::Migration[5.2]
def up
Move.update_all(move_agreed: false)
change_column_default :moves, :move_agreed, false
change_column_null :moves, :move_agreed, false
end
def down
change_column_null :moves, :move_agreed, true
change_column_default :moves, :move_agreed, nil
end
end
```
- The `move_agreed` attribute is explicitly set later in the user journey when attaching a person/profile to the move - user should be prompted to explicitly answer this question. However …

P4-1608 Reinstate support for null `move_agreed` attribute on move model

---

app/controllers/api/v2/people_controller.rb
app/serializers/v2/person_serializer.rb
config/routes.rb
db/schema.rb
spec/requests/api/v1/people_controller_create_spec.rb
spec/requests/api/v2/people_controller_create_spec.rb
spec/requests/api/v2/people_controller_index_spec.rb
swagger/v2/post_people_responses.yaml

https://dsdmoj.atlassian.net/browse/P4-1583
This PR adds the endpoint `/v2/people` to create a new person
This is part of the planned set of the new endpoints.
This allows creating a person with more attributes, and it is from a profile (when you create a person, the profile is not created)
The Swagger Doc will be updated in the next PR: https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/507/files
Very low risk, since this is a new endpoint.

Add new post /v2/person endpoint

---

app/serializers/move_serializer.rb
app/services/include_params_validator.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/requests/api/v1/moves_controller_index_spec.rb
spec/services/include_params_validator_spec.rb
swagger/v1/get_moves_responses.yaml

P4-<TODO>
To clarify supported relationships for the frontend/suppliers
To support the way moves are being consumed by the frontend

Return supplier on locations for moves

---

app/controllers/api/v2/profiles_controller.rb
app/serializers/v2/profile_serializer.rb
config/routes.rb
spec/requests/api/v2/profiles_controller_create_spec.rb
spec/serializers/v2/profile_serializer_spec.rb
swagger/v2/post_profile_responses.yaml
swagger/v2/profile.yaml

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1495
[P4-1495](https://dsdmoj.atlassian.net/browse/P4-1495)
To migrate to the new structure of person/profile, allow the new profile to be created under a new V2 endpoint `people/:id/profiles` which will accept only the assessment answers, and return the created profile. There is some legacy logic around validating existing first/last names on the profile, so for now we are maintaining those until migration is complete

P4-1495 Add Profile v2 POST endpoint

---

app/controllers/api/v1/move_events_controller.rb
app/models/event.rb
app/models/move.rb
app/models/move_event.rb
app/serializers/move_serializer.rb
app/services/event_log/move_runner.rb
app/services/move_events/params_validator.rb
config/routes.rb
db/migrate/20200605123822_add_rejection_reason_to_moves.rb
db/schema.rb
spec/factories/events.rb
spec/models/move_spec.rb
spec/requests/api/v1/move_events_controller_reject_spec.rb
spec/serializers/move_serializer_spec.rb
spec/services/event_log/move_runner_spec.rb
spec/services/move_events/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths_v1.yaml
swagger/v1/move_rejection_reason_attribute.yaml
swagger/v1/post_move_reject.yaml

P4-1579
- This will be called when the OCA rejects a singleton move - they must specify a reason for rejecting the move, and optionally include a comment (which is stored in the existing cancellation_reason_comment attribute.
- It's currently possible to reject a move by calling the `PATCH /moves/:move_id` endpoint but we want to deprecate that approach and instead use distinct endpoints which change move status.
- This is a special case of cancelling a move so is worthy of it's own endpoint that requires a rejection reason to be specified.
- Adds a new endpoint, doesn't affect existing production endpoints so minimal risk

P4-1579 Add new endpoint to explicitly reject a move

---

config/database.yml
config/sidekiq.yml

- we get repeated database errors "ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pool..."
- this should ensure the pool size is always larger than that required to service requests.
- potentially a bit risky - but should be ok 🤞 
Related PR: https://github.com/ministryofjustice/hmpps-book-secure-move-api-deploy/pull/63

tweak connection pool and sidekiq concurrency

---

app/serializers/allocation_serializer.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/serializers/allocation_serializer_spec.rb

P4-<TODO>
This was an afterthought and needed by the frontend

Adds support for allocation.moves.person.{gender,ethnicity}

---

.circleci/config.yml

- Building the image only once (per git sha) and re-tag as required 
- The deployment to production using the current flow will still build its own image. The SHA will change with the Changelog update.  
Image will be tagged with Git SHA as usual, and then re-tagged directly in ECR:
```
{
"registryId": "754256621582",
"repositoryName": "book-a-secure-move/hmpps-book-secure-move-api",
"imageDigest": "sha256:b139ec7ba09af869d07320080e1647764c5ac56bf56aadfc00667144f5796d33",
"imageTags": [
"staging.dryrun",
"561f35c95f4852290f858d373eb8f2f9c7a6cf67",
"dev.dryrun"
],
"imageSizeInBytes": 47491411,
"imagePushedAt": "2020-06-08T12:39:11+01:00"
}
```

[P4-1631] Streamline Pipeline "Part II - One image to deploy them all" 

---

app/controllers/api/v1/move_events_controller.rb
app/models/event.rb
app/models/move_event.rb
app/services/event_log/move_runner.rb
app/services/move_events/params_validator.rb
config/routes.rb
spec/factories/events.rb
spec/requests/api/v1/move_events_controller_approve_spec.rb
spec/services/event_log/move_runner_spec.rb
spec/services/move_events/params_validator_spec.rb
spec/swagger/definitions/hand_coded_paths_v1.yaml
swagger/v1/post_move_approve.yaml

P4-1650
- Currently the front end is PATCHING a proposed move and changing the status to `requested` and updating the move date.
- We want to move away from this approach and have dedicated endpoints which explicitly change move status and ensure the relevant related attributes are correctly specified.
- Introduces a new API so minimal production risk

P4-1650 Add an explicit endpoint to approve a move

---

app.json

- Heroku is throwing errors about this now as we don't have a `package.json` file at root level
```
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
!     ERROR: Application not supported by 'heroku/nodejs' buildpack
!
!     The 'heroku/nodejs' buildpack is set on this application, but was
!     unable to detect a Node.js codebase.
!
!     A Node.js app on Heroku requires a 'package.json' at the root of
!     the directory structure.
!
!     If you are trying to deploy a Node.js application, ensure that this
!     file is present at the top level directory. This directory has the
!     following files:
!
!     adr/
!     app/
!     app.json
!     bin/
!     CHANGELOG.md
!     config/
!     config.ru
!     db/
! …
```

Remove NodeJS buildpack

---

.circleci/config.yml

- This seems to be too aggressive at present and ties up all of the build executors for a single workflow, leading to queued PR tests.
- The swagger docs job only runs a few specs so 2 executors should be enough for that.
For the main rspec tests it looks like a law of diminishing returns so 4 should be almost as fast as 8.

Reduce CircleCI parallelism slightly

---

app/controllers/api/v1/allocations_controller.rb
app/serializers/allocation_serializer.rb
spec/requests/api/v1/allocations_controller_index_spec.rb

- The previous change was made as part of an attempted hotfix yesterday. We observed slow performance on the `GET /allocations` endpoint and assumed this was due to returning additional relationships that were recently added.
- The original change made did not improve the observed performance on staging environment (which was caused by another bug returning all documents for a move without a profile)
- Reverting this change does not impact the current performance baseline against staging data (tested locally)
```
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::JsonApi (1234.66ms)
Completed 200 OK in 1464ms (Views: 1261.5ms | ActiveRecord: 134.0ms | Allocations: 1066401)
```
```
[active_model_serializers] Rendered …
```

Reinstate default includes for GET allocations endpoint

---

.circleci/config.yml

-  as it was affecting the 'swagger.yml' generation, causing only part of the endpoint to be generated.

Run api_jobs non-concurrently

---

app/serializers/move_serializer.rb
app/serializers/person_serializer.rb
spec/requests/api/v1/moves_controller_create_spec.rb
spec/serializers/move_serializer_spec.rb
spec/serializers/person_serializer_spec.rb
swagger/v1/ethnicity_reference.yaml
swagger/v1/location_reference.yaml
swagger/v1/prison_transfer_reason_reference.yaml

[P4-1432](https://dsdmoj.atlassian.net/browse/P4-1432)
To adhere to the JSON:API [specs](https://jsonapi.org/format/#document-resource-object-linkage) regarding relationships linkage where an empty relationship should be represented as:
- null for empty to-one relationships.
- an empty array ([]) for empty to-many relationships.
Allow relationships to be surfaced in serializers even if missing.

P4-1432 Allow relationships to be surfaced in Serializers even if missing

---

swagger/v1/identifier_type.yaml
swagger/v1/profile_identifier.yaml

Removes dead references from swagger docs. It is impossible that these are returned as they are never populated.

Removes dead references

---

app/controllers/api/v1/move_events_controller.rb
app/models/move.rb
app/models/move_event.rb
app/serializers/move_serializer.rb
app/services/event_log/move_runner.rb
db/migrate/20200612133540_add_original_move_id_to_moves.rb
db/schema.rb
spec/factories/events.rb
spec/models/move_spec.rb
spec/requests/api/v1/move_events_controller_reject_spec.rb
spec/serializers/move_serializer_spec.rb
spec/services/event_log/move_runner_spec.rb
swagger/v1/post_move_reject.yaml

P4-1633
- This allows the front end to specify that a move should be automatically be rebooked in 7 days; the new move is a proposed move with allocation, profile, location and date details copied across from the original move. This provides a convenience for the PMU/OCA to create a new move in future.
- This API endpoint is not yet implemented in the front end, so low risk (story to implement is being worked on at present)

Add support for automatically rebooking a move when rejecting

---

.circleci/config.yml

N/A
- We need to get additional permissions for circleCI to be able to do this. Until then we are suppressing it so that we can deploy.

Deferring log extraction until we sort out permissions

---

app/services/move_events/params_validator.rb
spec/services/move_events/params_validator_spec.rb
swagger/v1/post_allocation_cancel.yaml
swagger/v1/post_move_approve.yaml
swagger/v1/post_move_cancel.yaml
swagger/v1/post_move_complete.yaml
swagger/v1/post_move_reject.yaml

P4-1633
- The front end code base makes use of a JSONAPI client library Devour which does not have the flexibility to provide singular types and so would require significant changes to use an alternate approach to call endpoints with singular types defined.
- Strictly speaking, the JSONAPI spec suggests that an API should use either singular or plural terms consistently throughout the implementation. In almost every case we adopt plural terms but this seems less grammatically correct for some verbs used in these endpoints that fall outside the usual RESTful conventions.
- We don't really want to update existing production `Event` data as this would require a coordinated change across front end, back end and the database meaning a likely planned outage, plus is tricky to manipulate nested …

Allow specific plural types within move events validator

---

.circleci/config.yml

Related to:
P4-1631
- It is useful to be able to deploy to the dev environment so that we can fully test the workflow and if a change runs in the target platform

Trigger deploy to DEV on a branch suffix

---

app/models/move.rb
spec/factories/move.rb
spec/models/move_spec.rb

P4-1633
- This now sets the move `date`, `date_from` and `date_to` to 7 days ahead from their current values if present, otherwise they are kept as nil values.
- It's possible that a proposed move would have any of these values set - at a minimum `date_from` must be set but we want to preserve everything if possible, whilst also not throwing a 500 error if one of the values happens to be nil.
- This forms part of the `POST /moves/:id/reject` endpoint that is not yet in production

Update rules for rebooking a move

---

.circleci/config.yml

Related to:
P4-1631
- So that we can see the output of the migrations job in the pipeline.
-
-

Extract logs on migrations job

---

app/serializers/allocation_serializer.rb
spec/requests/api/v1/allocations_controller_index_spec.rb
spec/serializers/allocation_serializer_spec.rb

Since we now support profiles instead of person, change includes to
support profile as well in the allocation serializer. I've kept the old person associations to allow for the final cleanup that will be done by the people/profile team.

Amend includes for an allocation

---

app/services/people/importer.rb
app/services/person_populator.rb
spec/services/people/importer_spec.rb

P4-<TODO>
Fixes missing import for the latest_nomis_booking_id in the Nomis Importer service.
This is a bug and needs fixing so that Nomis court hearings, court cases, personal care needs, risks and activities can be returned correctly.
There is no data loss resulting from this bug.
- Integrations with Nomis are critical

Reinstate importing of latest_nomis_booking_id

---

app/models/profile.rb
app/models/profile/profile_identifier.rb
app/models/profile/profile_identifiers.rb

P4-<TODO>
Reinstate profile identifier serializers
These are needed to move profile_identifiers around as part of the person populator

Reinstate profile_identifier serializers

---

Gemfile
Gemfile.lock
lib/tasks/create_application.rake

P4-<TODO>
- Removes tty-prompt gem
- Remove references to tty-prompt
This 1 gem brings in 8 gems and adds very little value - it was giving us a fzf interface for choosing from 3 options when `gets` and a message saying which options are possible works just as well.
I've ran all three variations of this and it works as we expect.
I generally prefer to maintain as few deps as possible to make our lives
easier/give us fewer things to worry about from a security point of view

Remove tty-prompt from project

---

app/models/allocation.rb
app/models/concerns/state_machineable.rb
app/models/journey.rb
app/state_machines/allocation_state_machine.rb
db/migrate/20200617155359_change_null_allocation_status.rb
db/schema.rb
spec/factories/allocation.rb
spec/factories/journeys.rb
spec/models/allocation_spec.rb
spec/services/allocations/finder_spec.rb

P4-1657
- There was some divergence in the approach to integrating the state machine with each model, this cleans that up and means it's more straightforward to add a state machine to `Move` in future.
- The `Allocation` state machine no longer needs to handle `nil` status (the state machine and status attribute was added after we already had some production data, but all production data has been cleaned up to set an explicit status value).

Refactor state machine integration with models

---

app/controllers/api_controller.rb
lib/routing_filter/versioned_path.rb

P4-1666
- Fix swagger docs in staging by not changing routes for requests for swagger docs.
- Fix issue with matching missing Accept headers.
We broke swagger docs when we started filtering out v1 in our apis. 
- Fix v2 docs

[P4-1666] Fix swagger docs

---

spec/swagger/definitions/hand_coded_paths_v1.yaml

P4-1500
This is no longer supported

[P4-1500] Removes move documents from hand_coded_paths_v1

---

.circleci/config.yml

P4-<TODO>
- Add swagger directory back into api_docs generation job
The glob pattern enhancement to the api_docs job ended up missing
all of our swagger directory doc generation tests.
The TEST variable includes only our rswag tests in full now:
```
spec/requests/api/documents_controller_create_rswag_spec.rb
spec/requests/api/moves_controller_role_access_rswag_spec.rb
spec/requests/api/reference/prison_transfer_reasons_controller_rswag_spec.rb
spec/swagger/api/allocations_controller_show_spec.rb
spec/swagger/api/court_hearings_controller_create_spec.rb
spec/swagger/api/moves_controller_show_spec.rb
spec/swagger/api/people_controller_court_cases_spec.rb
spec/swagger/api/people_controller_image_spec.rb
spec/swagger/api/people_controller_timetable_spec.rb
```
We are missing a whole bunch of …

Adds swagger directory specs back into api_docs job

---

.circleci/config.yml

P4-1631
- This functionality was lost during the refractoring of the pipeline, as we no longer have a dedicated production build.

[P4-1631] Bring back notification on release.

---

app/controllers/api/v1/people_actions.rb
spec/requests/api/people_controller_index_spec.rb

P4-<TODO>
prison_number/offender_number only comes in upcase form so just upcase them when they come into the index action
- To support any casing on a prison number

Fix casing of the prison number when indexing by prison number

---

config/initializers/rswag-ui.rb

P4-<TODO>
We're moving away from v1 and don't want to encourage integration with v1 apis.
Let's default to v2 so that links to our swagger docs point to what we want people to integrate with by default.
Reduce accidents, generally.

Default rswag ui to point at v2 docs first in list

---

app/controllers/api/reference/regions_controller.rb
app/serializers/region_serializer.rb
spec/serializers/region_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml

P4-1766
- The front end requires this to correctly deserialize location id's through the Devour JSONAPI library. Although only location id's are needed to subsequently build up location filters on calling `GET /allocations` to filter by region, Devour seems unable to return relationship id's unless the corresponding entities are included in the response.
- This does increase the size of the response payload significantly, and is a bit slower. Local testing shows response time changing from ~35ms with a 10KB payload to ~85ms with a 40KB payload. I've been able to introduce this without any N+1 queries - the ActiveRecord element is only 2.3ms.
- API behaviour is unchanged if no include parameter is specified (i.e. locations are listed as relationships within each region, but not included). …

Add support for include `locations` when retrieving regions

---

db/schema.rb

Running a vanilla rake db:migrate is adding those changes to the
schema, commit them to avoid having to undo changes each time a new
migration is added

Commit latest db schema changes

---

app/controllers/api/journeys_controller.rb
app/controllers/api/people_controller.rb
app/serializers/journey_serializer.rb
spec/requests/api/people_controller_court_cases_spec.rb
spec/requests/api/people_controller_timetable_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml
swagger/v1/allocation_include_parameter.yaml
swagger/v1/journey_include_parameter.yaml
swagger/v1/location_include_parameter.yaml
swagger/v1/move_include_parameter.yaml
swagger/v1/person_include_parameter.yaml
swagger/v1/profile_include_parameter.yaml
swagger/v2/move_include_parameter.yml
swagger/v2/person_include_parameter.yaml

[P4-1616](https://dsdmoj.atlassian.net/browse/P4-1616)
- Add swagger docs for all include endpoints
- Add Include params to court cases and timetable people endpoints
To support includes everywhere we have associated resources in the serializer, add `include` param to allow the resources to be rendered with its associated resources under the `included` section.
In the people controller however, since we are supporting multiple endpoints, we had to disable the normal validation which happens at the API controller level, and add custom validations for the extra endpoints themselves.

P4-1616 Support includes in all relevant controllers

---

app/controllers/api/allocations_controller.rb
app/controllers/api/people_controller.rb
app/controllers/api/v1/allocations_actions.rb
app/controllers/api/v1/people_actions.rb
app/controllers/api/v2/allocations_actions.rb
app/controllers/api/v2/people_actions.rb
spec/requests/api/allocations_controller_create_v2_spec.rb
spec/requests/api/allocations_controller_index_v2_spec.rb
spec/requests/api/people_controller_court_cases_v2_spec.rb
spec/requests/api/people_controller_timetable_v2_spec.rb

[P4-1618](https://dsdmoj.atlassian.net/browse/P4-1618)
- Removed default includes in people/allocation controllers into v2 version
Since we have moved to using the include param, remove default includes from controllers everywhere in v2, but leave v1 the same
- Only change API in v2, v1 should remain exactly the same

P4-1618 Remove default includes

---

app/controllers/api/allocations_controller.rb
app/models/location.rb
app/models/person.rb
app/services/allocations/finder.rb
spec/requests/api/allocations_controller_index_spec.rb
spec/services/allocations/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml

P4-1327
- This supports adding a search feature in the front end. The original intent was to add a single search param covering both location titles and person name but this got very messy so I decided to separate the two searches for simplicity. This is an option we discussed during refinement and is likely to be more useful to the user.
- Tested locally with a copy of staging data and performance is good (searching across all allocations with no filters is around 400-500ms response time - the bulk of that being AMS rendering of included resources).
- Extends a production API with a non breaking change; original behaviour remains unchanged if search params are not passed in request

Add support for searching within GET /allocations endpoint

---

app/serializers/move_serializer.rb
app/serializers/v2/move_serializer.rb
spec/factories/move.rb
spec/factories/profile.rb
spec/serializers/move_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
swagger/v1/move_include_parameter.yaml
swagger/v2/move_include_parameter.yaml

P4-1813
Reduce impact of migration of documents for frontend.

[P4-1813] Adds support for profile.documents in MoveSerializer

---

Gemfile
Gemfile.lock

P4-1696
- We want to explore this tool on real environments, selectively.
- Having the gem loaded without providing the required config should result safely in a NoOp. As as additional safety net we   can set `ELASTIC_APM_ENABLED`to false explicitly on the environments we don't want to introduce this just yet. 
It goes in tandem with this PR on api-deploy: 
https://github.com/ministryofjustice/hmpps-book-secure-move-api-deploy/pull/67/files

Enable APM on config

---

.env.example

P4-<TODO>
Default to disabling apm for new devs to avoid local log output noise.

Default to APM off for new devs

---

app/services/moves/import_people.rb
spec/services/moves/import_people_spec.rb

P4-1823
We noticed a bug during importing of people and profiles in v1 in production. Profiles (and therefore people) weren't being saved because the `changed?` method returns false for new profiles without any assessment_answers.
This PR fixes this issue by checking to see whether person attributes have changed in addition to profile ones and does the saving of Person/Profile separately.
New Nomis prison numbers aren’t being created in production. This means that we can’t find them when calling GET /api/people?filter[prison_number]=:prison_number. This feature is needed.

[P4-1823] Handle profiles with no assessment answers in importer

---

app/models/flag.rb
app/models/framework_question.rb
app/services/frameworks/question.rb
db/migrate/20200630071352_create_flags.rb
db/schema.rb
spec/factories/flag.rb
spec/factories/framework_question.rb
spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-professional-referral.yml
spec/models/flag_spec.rb
spec/models/framework_question_spec.rb
spec/services/frameworks/importer_spec.rb
spec/services/frameworks/question_spec.rb

[P4-1750](https://dsdmoj.atlassian.net/browse/P4-1750)
To show users on the summary pages on the Frontend application certain alerts a person transported might have, flags are linked to questions if they are answered in a certain way. A question can have multiple flags, with a `type`, `name` and the question value they relate to.

P4-1750 Add flags to frameworks

---

app/models/move.rb
app/services/court_hearings/create_in_nomis.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_index_spec.rb
spec/requests/api/moves_controller_sorting_spec.rb
spec/serializers/move_serializer_spec.rb
spec/services/court_hearings/create_in_nomis_spec.rb

https://dsdmoj.atlassian.net/browse/P4-1819
I have altered the Move validation.
To make a move unique under the person not under the profile, in Api V2.
the API V1 and V2 require slightly different validations for the Move, 
to make it work I had to use this "hack":
```
def person_id
attributes['person_id'] || person&.id
end
```
That is not a good piece of code!
In case we do NOT need FE to create a Move with a person and without a profile, we can remove it.

Fix uniqueness for Move model

---

Gemfile
Gemfile.lock

its optional but broken sidekiq because it does not support ssl

Remove hiredis gem

---

k8s_migrate_job.yml

n/a
- It's possible that migrations can run with the existent version of the  container. 
We are tracking the `env.lastest` tag, that as been just recently updated when this runs.  If we don't force pull it for this job and the job is running in a node that is running any of the other pods we might end up using the cached one.

Force to pull a new image on migrations

---

spec/requests/api/reference/prison_transfer_reasons_controller_rswag_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/court_case.yaml
swagger/v1/get_court_cases_responses.yaml
swagger/v1/person.yaml
swagger/v1/person_id_parameter.yaml
swagger/v1/post_court_hearing_responses.yaml

Update swagger documentation to include the following endpoints:
`POST /court_hearings`
`GET /people/{person_id}/court_cases`
`GET /people/{person_id}/timetable`
`POST /documents`
Remove old `POST /moves/{move_id}/documents` endpoint
Remove duplication in `GET /reference/regions` endpoint that appears under region and locations

Update swagger documentation 

---

app/services/people/import_from_nomis.rb
k8s_migrate_job.yml
spec/services/people/import_from_nomis_spec.rb

P4-1852
The service we wrote and were mocking out in the controller for
importing a person from Nomis was built to operate against a single
person which is inconsistent with filter param possibilities described
by the json:api spec.
This is critical functionality for the frontend and is currently broken.

[P4-1852] Fix importing offenders from Nomis in v2

---

app/services/frameworks/importer.rb
lib/tasks/populate_framework_data.rake
spec/services/frameworks/importer_spec.rb

* Don't attempt to persist already imported framework
* Add logging for framework import success
* Add logging for framework import failure, with additional logging of all errors coming from the framework and the questions specifically with keys to help point out the offending files coming from the framework

Improve Framework importer and error logging

---

app/models/move.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/services/moves/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml
swagger/v1/move.yaml
swagger/v2/move.yaml

https://dsdmoj.atlassian.net/browse/P4-1781
This PR adds `police_transfer` to the allowed move_type
because we want to support transfer police -> police locations

Add `police_transfer` to the move types

---

spec/requests/api/journey_events_controller_reject_spec.rb
swagger/v1/assessment_question.yaml
swagger/v1/ethnicity.yaml
swagger/v1/gender.yaml
swagger/v1/identifier_type.yaml
swagger/v1/location.yaml

- "String" and "Boolean" are not defined types for swagger/open API schemas. These should be "string" or "boolean" (lower case) in all cases.
- This then caused a number of specs to fail - the root cause for that was that we did not correctly specify that `null` values are allowed for the failing attributes. Adding that fixes the tests. Presumably the JSON validator was confused by "String" and then finding "null" an acceptable substitute.
- I've searched through all of the type definitions within swagger schemas and can't find any other cases of this.

Fix inconsistent/incorrect type names in swagger docs

---

app/models/move.rb
app/serializers/move_serializer.rb
spec/requests/api/moves_controller_index_spec.rb

P4-<TODO>
We migrated away from `Move#person` to `Move#profile#person`.
I've added the ignored_columns for person_id to soft-force our not referencing the person_id and to stop us loading it as an active record attribute on the model.

Removes references to moves.person_id

---

.circleci/config.yml

N/A
- Migrations might take longer to run on busier environments and the 60s default timeout is not enough.

Increase migrations timeout to 300s.

---

config/environments/production.rb
config/initializers/lograge.rb
lib/log_formatter/json.rb
spec/lib/log_formatter/json_spec.rb

P4-1797
This PR moves our logs (in production, only) to spit out json rather than unparseable strings.
Fluentd defines a json parser for pod logs:
https://github.com/ministryofjustice/analytics-platform-fluentd/blob/eb7d529ba83abaa58c8253a39d2d11a86b91dc39/conf/kubernetes.conf#L8-L16
We think that if we move our logs to a json document per line we'll be able to filter our logs for useful things like request id in future (more on this later).
This will help us to debug issues in production more conveniently and generally make our logs more useable.
```
Running tests in:
- Chrome 83.0.4103.116 / macOS 10.15.5
Cancel allocation
✓ Cancel allocation
New PMU allocation
✓ Create allocation and verify the result
✓ Check validation errors on allocation details page
New move from Police Custody to …
```

[P4-1797] Make logs parseable by fluentd

---

app/models/journey.rb

related to: [P4-1788](https://dsdmoj.atlassian.net/browse/P4-1788)
- On the reporting task we want to filter for any moves that had journeys added or updated in the given time interval.
https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/659/files#diff-f45e1a76d527485f7af80db97fb81aa9R38-R39
- This will likely cause an increase in UPDATES on the `moves` table, but given the journey activity is not particularly busy, it's unlikely that it will cause UPDATE contention on the database.

Update moves.updated_at on journey updates

---

lib/tasks/journeys_report.rake

P4-1788
- It was being sourced from profiles, that we no longer use.
-
-

Fetch gender and dob from person, not profiles.

---

app/controllers/api/reference/regions_controller.rb
config/routes.rb
spec/requests/api/reference/regions_controller_index_spec.rb
spec/requests/api/reference/regions_controller_show_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/get_region_responses.yaml
swagger/v1/region_include_parameter.yaml

P4-1850
- This supports work to filter allocations by region in the front end
- New endpoint so minimal risk

Add new endpoint to GET /reference/regions/:id

---

app/controllers/api/v1/people_actions.rb
app/controllers/api_controller.rb
app/lib/nomis_client/base.rb
spec/lib/nomis_client/base_spec.rb
spec/requests/api/people_controller_index_spec.rb

Add rescue from error Timeout
https://dsdmoj.atlassian.net/browse/P4-1787
Reduce timeout to 10s for all NOMIS calls
Ensure we propagate the timeout error message and code (504) to the client for all NOMIS calls
To help FrontEnd to provide an appropriate error message

Change Nomis Timeout to 10 Secs

---

app/models/framework.rb
app/models/framework_question.rb
app/models/framework_response.rb
app/models/framework_response/array.rb
app/models/framework_response/collection.rb
app/models/framework_response/details_collection.rb
app/models/framework_response/details_object.rb
app/models/framework_response/object.rb
app/models/framework_response/string.rb
app/models/person_escort_record.rb
app/models/profile.rb
db/migrate/20200702063823_create_person_escort_record.rb
db/migrate/20200702081808_create_framework_responses.rb
db/schema.rb
spec/factories/framework_response.rb
spec/factories/person_escort_record.rb
spec/models/framework_question_spec.rb
spec/models/framework_response/array_spec.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response/details_collection_spec.rb
spec/models/framework_response/details_object_spec.rb
spec/models/framework_response/object_spec.rb
spec/models/framework_response/string_spec.rb
spec/models/framework_response_spec.rb
spec/models/framework_spec.rb
spec/models/person_escort_record_spec.rb
spec/models/profile_spec.rb

[P4-1746](https://dsdmoj.atlassian.net/browse/P4-1746)
To facilitate person escort record creation with responses, add the relevant tables as well as the validations and associations.
A Person escort record can be created with a framework and version, and will contain many responses which are initially empty. A response depending on the question it is for, can hold many answer types. To store the different types we have added two fields on the response table: text and jsonb. Those two will be able to store all the required values sent to us as answers, and will be hidden under a single field called value. According to the value type, the relevant answers will be set accordingly to the underlying tables. 
The 4 types of responses are: string, array, object and collection
- **String**: This …

P4-1746 Build PER related tables

---

app/models/move.rb
app/models/supplier.rb
db/migrate/20200708110909_add_supplier_to_moves.rb
db/schema.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/models/supplier_spec.rb

P4-1878
We are moving to having supplier ownership of moves. This is driven by the requirement that in the future two suppliers can have the same from location.
We can also more easily filter a suppliers moves in the frontend dashboard.

[P4-1878] Adds migration for supplier on move

---

app/controllers/api/v2/moves_actions.rb
spec/requests/api/moves_controller_update_v2_spec.rb

P4-1904-prevent-updating-from-to
Fix the v2 move endpoint to ensure that from_location and to_location cannot be updated.
This functionality was overlooked when creating the V2 endpoint. We still need it for V2.

Prevent V2 patch move to update from_location and to_location

---

app/serializers/v2/move_serializer.rb
app/serializers/v2/profile_serializer.rb
spec/serializers/v2/profile_serializer_spec.rb

P4-<TODO>
We need to conform to the swagger documentation for v2 and make sure that we're not coupling to v1 people.

[P4-1906] Fix v2 profile serialization

---

app/controllers/api/profiles_controller.rb
spec/requests/api/profiles_controller_create_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/profile.yaml

https://dsdmoj.atlassian.net/browse/P4-1881
If the `assessment_answers` param is not present AND the person's profile has a `prison_number`
THEN the new profile will be updated with Alerts and Personal Care from NOMIS.
the endpoint POST /people/:id/profiles
This is because an individual may have been out (released) for a while and when they are remanded at court NOMIS would be out of date

Prevent access to Nomis when assessment_answers are passed.

---

app/controllers/api/move_events_controller.rb
app/models/move.rb
app/services/journey_events/params_validator.rb
app/services/move_events/params_validator.rb
app/services/moves/move_type_validator.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_lockout_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/move_events/params_validator_spec.rb
swagger/v1/move.yaml
swagger/v2/move.yaml

P4-1816
- This is the first of many new move types to be added, each introducing additional validation rules on the permitted from and to location types. As the first step to implementing support for these rules, validation of move type and associated location types is extracted to a new custom validator; this allows the logic to be shared across the move model and move runner.
- Adds support for new move type, but does not change behaviour of existing move types

Add support for new video_remand_hearing move_type

---

lib/tasks/journeys_report.rake

* Run report for a given calendar day (defaults to yesterday)
[[P4-1897](https://dsdmoj.atlassian.net/browse/P4-1897)]
new format:
```
awslocal s3 ls --recursive s3://reports
2020-07-09 14:55:11     610923 2020/07/05/geoamey.json
2020-07-09 14:55:22     444080 2020/07/05/serco.json
2020-07-09 14:35:52    1278690 2020/07/08/geoamey.json
2020-07-09 14:36:16     819143 2020/07/08/serco.json
2020-07-09 13:20:52    1278690 2020/07/09/geoamey.json
2020-07-09 13:21:12     819143 2020/07/09/serco.json
```
- Aligned the reporting service with the intended daily frequency as opposed to an arbitrary one.
- Allows to back fill specific days manually if required.
- It has an impact  downstream on the integration with the HUB team, but these …

* Use a partitioned S3 prefix format for daily runs

---

app/controllers/api/profiles_controller.rb
spec/requests/api/profiles_controller_update_spec.rb

P4-1663
Fixes notifications that update suppliers when changes to the PTR are made.
We had a live production issues where a person on the road wasn't updated when the PTR was changed.

[P4-1663] Fix missing notifications when updating a profile

---

app/controllers/api/v2/people_actions.rb
spec/requests/api/people_controller_patch_v2_spec.rb

P4-1907
Previously we were wiping out the gender and ethnicity and not
conforming to the json:api specification around patching relationships
in the people_actions v2.
This updates the people_actions behaviour so that we:
1. Update relationships to nil when they are passed but empty
2. Update relationships to the passed type if they exist and are passed
3. Do not change relationships if they are not passed
Conform to json api specs

[P4-1907] Fix relationship patching on people v2

---

app/controllers/api/allocations_controller.rb
app/services/allocations/creator.rb
spec/factories/location.rb
spec/requests/api/allocations_controller_create_spec.rb
spec/services/allocations/creator_spec.rb

P4-1896
This PR enables us to stamp an allocation move with the relevant
supplier based on either the token provided by the api request and then the
from location supplier.
**This is transparent to clients of the allocation controller api**
As part of moving away from having a single supplier supporting each
location we are going to migrate our ownership model for the allocation
and singleton moves.

[P4-1896] Adds move supplier for allocation moves

---

db/schema.rb

Those keep coming up after dropping/creating/migrating the db so best have them in original structure

Add correct schema structure

---

app/controllers/api/allocations_controller.rb
app/models/allocation.rb
app/serializers/allocation_serializer.rb
db/migrate/20200713092251_add_estate_comment_to_allocations.rb
db/schema.rb
spec/requests/api/allocations_controller_create_spec.rb
spec/requests/api/allocations_controller_create_v2_spec.rb
spec/serializers/allocation_serializer_spec.rb
swagger/v1/allocation.yaml

P4-1914
- This supports corresponding front end changes. Note that the new enum member is named `other_estate` - this could not be named `other` as we already have a member within sentence length enum in the same model. Rails creates methods for each enum member but in this case that causes a conflict. I don't think it's worth renaming the existing sentence length `other` member now, but we need to keep this in mind for future naming where the enum members have generic terms.
- Adds support for an additional attribute in existing production API, but the new value is optional to avoid a breaking change

Add new estate type and comment to allocation model

---

lib/tasks/move_supplier.rake

P4-1898
Adds a rake task to populate supplier relationships on historical moves.
In non-production environments it's possible for the supplier to be absent for a move - due to some locations not including definitions for suppliers [here](https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/move-supplier/lib/tasks/data/supplier_locations.yml) and us creating moves for those locations.
The way I've handled this is to report the count of these for informational purposes but (beyond changing the locations) there's no need to fix these.
```shell
rake move:supplier
Populating supplier Serco for moves from Bishopsgate Custody Suite
18/1265 moves populated...
Populating supplier GEOAmey for moves from CHANNINGS WOOD (HMP)
27/1265 moves populated...
Populating supplier GEOAmey for …
```

[P4-1898] Adds rake task for populating supplier moves

---

Gemfile
Gemfile.lock
app/controllers/api/person_escort_records_controller.rb
app/models/framework.rb
app/models/framework_question.rb
app/models/person_escort_record.rb
app/serializers/framework_question_serializer.rb
app/serializers/framework_response_serializer.rb
app/serializers/framework_serializer.rb
app/serializers/person_escort_record_serializer.rb
config/routes.rb
db/migrate/20200710061513_add_unique_index_on_person_escort_record.rb
db/schema.rb
spec/factories/framework_question.rb
spec/factories/person_escort_record.rb
spec/models/framework_question_spec.rb
spec/models/framework_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/serializers/framework_question_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/framework_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/framework_reference.yaml
swagger/v1/framework_response_reference.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/post_person_escort_record_responses.yaml

[P4-1761](https://dsdmoj.atlassian.net/browse/P4-1761)
To allow clients to create a new PER, add POST `/person_escort_records` endpoint which accepts a profile, and a version of the framework to build empty responses for all questions related to a framework. If the version of the framework is not passed in use the latest framework (versioning is going to be revised, this is only temporary).
To bulk create a PER record, active record import gem has been added. This allows us passing in an actual object rather than a hash, and helps with deeply nested record creation. However to associate a PER record to deeply nested responses, we have had to create it first then associate them after.

P4-1761 POST /person_escort_records endpoint

---

app/controllers/api/move_events_controller.rb
app/models/move.rb
app/services/move_events/params_validator.rb
app/services/moves/move_type_validator.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/move_events/params_validator_spec.rb
spec/services/moves/move_type_validator_spec.rb
swagger/v1/move.yaml
swagger/v2/move.yaml

P4-1830, P4-1832, P4-1835, P4-1836
- We want to support hospital moves (moves from any location to a high security hospital) in the near future.
- Adds support for a new move type when creating a move, but is not a breaking change

Added support for new 'hospital' move type

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
spec/requests/api/moves_controller_filter_spec.rb
spec/requests/api/moves_controller_filter_v2_spec.rb
spec/services/moves/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

P4-1879
from_location with supplier_id directly on the move
We're moving to supporting multiple suppliers on a location so our
authorisation model of move ownership through the location no longer
works.
- We may find that this breaks something for frontend since we technically supported - but didn't document - a version of supplier filter in the past based on the from location -> suppliers relationship.

[P4-1879] Filter moves by supplier

---

.circleci/config.yml

[P4-1476](https://dsdmoj.atlassian.net/browse/P4-1476)
- Automate everything™ 
- Apply the process  outlined in [Confluence](https://dsdmoj.atlassian.net/l/c/b0u0ExVQ) automatically every Monday.
- This was tested on a number of conditions to prevent the current images to being deleted, but there is always a slight change that it could happen do to a bug.
- Only the newest 100 < images < 200 will be left behind.
- Images containing "latest" on its tag designation will be always left behind untouched.
- Up to 100 images will be deleted per run (max aws batch-delete size)

Clean ECR images weekly

---

app/controllers/api/person_escort_records_controller.rb
app/models/framework_response.rb
app/models/person_escort_record.rb
app/serializers/framework_response_serializer.rb
app/serializers/person_escort_record_serializer.rb
config/routes.rb
db/migrate/20200715041742_add_responded_to_framework_responses.rb
db/schema.rb
spec/factories/framework.rb
spec/factories/framework_question.rb
spec/factories/person_escort_record.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/get_person_escort_record_responses.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/person_escort_record_id_parameter.yaml

[P4-1791](https://dsdmoj.atlassian.net/browse/P4-1791)
To support getting an existing PER, add new endpoint which accepts an id and returns a PER. To help the FE render different section progress, a new `meta` section has been added. This is supported by the [JSON:API spec](https://jsonapi.org/format/#document-resource-objects) in the data section. This will summarise all sections and their progress according to the new `responded` attribute on responses. The `responded` field is by default set to false. If a response is supplied and valid, the `responded` value is updated to true.

P4-1791 GET /person_escort_records/{person_escort_record_id}

---

app/serializers/framework_response_serializer.rb
app/serializers/move_serializer.rb
app/serializers/profile_serializer.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/profile_serializer.rb
spec/serializers/framework_question_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/serializers/profile_serializer_spec.rb
spec/serializers/v2/profile_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/move_include_parameter.yaml
swagger/v1/person_escort_record_include_parameter.yaml
swagger/v1/person_escort_record_reference.yaml
swagger/v1/profile.yaml
swagger/v2/move_include_parameter.yaml

To allow the FE to access the PER from the moves detail dashboard, expose PER relationship in profile. I also updated swagger documentation as it was missing includes. I added some tests for serializers as we are keying questions/responses differently 

Expose PER in profile and update swagger docs

---

app/models/profile/assessment_answer.rb

We got the following error whilst creating the PER with a profile with assessment answers:
```
ArgumentError (wrong number of arguments (given 1, expected 0)):
app/models/profile/assessment_answer.rb:42:in `as_json'
```
We should be allowing an argument to be passed to `as_json` method to mimic original method

Overriding existing method needs an argument

---

app/models/location.rb
app/models/move.rb
app/services/moves/move_type_validator.rb
spec/factories/location.rb
spec/models/location_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/moves/move_type_validator_spec.rb
swagger/v1/move.yaml
swagger/v2/move.yaml

P4-1873 P4-1860
- We want to support additional move types in the near future.
- Adds support for new types in move type param but these are not currently used, so no risk

Add support for prison_recall and court_other move types

---

app/models/framework_response/array.rb
app/models/framework_response/collection.rb
app/models/framework_response/details_collection.rb
app/models/framework_response/details_object.rb
app/models/framework_response/object.rb
app/models/framework_response/string.rb
spec/factories/framework_response.rb
spec/models/framework_response/array_spec.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response/details_collection_spec.rb
spec/models/framework_response/details_object_spec.rb
spec/models/framework_response/object_spec.rb
spec/models/framework_response/string_spec.rb
spec/models/framework_response_spec.rb

[P4-1771](https://dsdmoj.atlassian.net/browse/P4-1771)
Correct the following validations:
- Array responses inclusion: inclusion validation works on strings not arrays use custom validation instead
- Validate option inclusion if option present to allow empty responses to be valid if response optional
- Validate details presence only if question answered with dependent answer
Added the following validations:
- Type validation for each response type
- Uniqueness validation on collection options incase someone sends a checklist response more than once
- Move option presence to only be required if details sent, as presence is done in main object class

P4-1771 Extend PER validations

---

lib/tasks/journeys_report.rake

n/a
- So that we can keep track of the report evolution without having to open the actual reports. 

log number of moves exported

---

Gemfile
Gemfile.lock

n/a
- We ended the trial and the spike for evaluating Elastic APM. It's unlikely that we adopt this tool on it's current form so better to remove this from our code for the time being. 

Remove Elastic APM gem

---

.circleci/config.yml

n/a
- Tring to save some CI credits on lighter tasks.  Default is medium (10 credits) and small uses only 5.
Classes here: https://circleci.com/docs/2.0/configuration-reference/#docker-executor

Use `resource_class: small` on ligther tasks

---

app/models/move.rb
app/services/moves/move_type_validator.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/moves/move_type_validator_spec.rb
swagger/v1/move.yaml
swagger/v2/move.yaml

P4-1816
- This is consistent with the naming for `prison_remand` and matches the value for front end work that's already been started. It's not yet been used to create any production moves so is safe to change at this point.
- Not yet used in production, so safe to change now

Rename video_remand_hearing to video_remand

---

app/models/framework_response.rb
spec/models/framework_response_spec.rb

[P4-1945](https://dsdmoj.atlassian.net/browse/P4-1945)
If the parent answer is changed, we would like to clear all answered dependent values and flags. We should clear
the full tree of dependents and not only the first level down. To determine the correct dependent responses to clear, only
select the responses with dependent values used to match the answered value, this is found
in the framework question attached to the response under `dependent_value`.
I have added a recursive CTE to retrieve a full list of descendants for a list of response ids, rather than recursively attempting to retrieve them as its more efficient. Full explanation can be found [here](https://www.gmarik.info/blog/2012/recursive-data-structures-with-rails/).
To bulk update, I am using …

P4-1945 Clear dependent answers

---

app/models/person_escort_record.rb
spec/models/person_escort_record_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1792
The previous implementation of the progress section included all responses and only looked at a response having responded
true or false. This is an issue with dependent questions, where they are valid remaining unanswered if a parent question is answered differently and doesn't lead to them, meaning they will always remain unanswered.
Add a filter to only select and check nodes which are not dependent responses, or dependent responses where the parent has been answered with the correct dependent response to include them.

P4-1792 Fix progress section for the PER

---

app/models/framework_response.rb
app/models/person_escort_record.rb
app/serializers/person_escort_record_serializer.rb
app/state_machines/person_escort_record_state_machine.rb
db/migrate/20200724071959_add_state_timestamps_to_person_escort_records.rb
db/migrate/20200727043305_rename_state_on_person_escort_record.rb
db/schema.rb
spec/factories/person_escort_record.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/state_machines/allocation_state_machine_spec.rb
spec/state_machines/journey_state_machine_spec.rb
spec/state_machines/person_escort_record_state_machine_spec.rb
spec/support/state_machine_target_state.rb
spec/support/state_machine_target_status.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/patch_framework_response_responses.yaml
swagger/v1/person_escort_record.yaml

[P4-1591](https://dsdmoj.atlassian.net/browse/P4-1783)
- The PersonEscortRecord state machine has been added to handle the different transitions of the PER, as well as add two new states: `not_started` and `printed`. Since we cannot have `not_started` in the enum values due to it overlapping with the negation generated methods `not_`, only expose that value in the serializer.
- To track when a PER is confirmed and printed, timestamps for each event have been added. After a state is changed to either set the timestamps respectively in the after callback.
- To calculate the state changes on a person escort record, utilise the same query for sections, but do not group them to the specified section to calculate the general state. If the person escort record is …

Add Person Escort Record state machine

---

app/controllers/api/person_escort_records_controller.rb
app/models/person_escort_record.rb
app/services/person_escort_records/params_validator.rb
config/routes.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/services/person_escort_records/params_validator_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/patch_person_escort_record.yaml
swagger/v1/patch_person_escort_record_responses.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/post_person_escort_record.yaml

[P4-1783](https://dsdmoj.atlassian.net/browse/P4-1783)
Add new PATCH endpoint for person escort record, which accepts a status, which could be `confirmed` or `printed`, and updates the person escort record state. It also sets the timestamps for each respectively.
If either the start state is invalid (`completed -> confirmed` or `confirmed -> printed`), or any other params are passed in, it returns an error.

P4-1591 Add Person escort record PATCH endpoint

---

app/controllers/api/person_escort_records_controller.rb
app/jobs/prepare_person_escort_record_notifications_job.rb
app/services/notifier.rb
spec/jobs/prepare_person_escort_record_notifications_job_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/services/notifier_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1783
If a person escort record is confirmed, send an update move webhook and email. We have written up a proposal for suppliers,  if using the same `update_move` notification is not preferable we can create a specific action name instead (we will wait for their feedback).

P4-1783 Add webhook on confirming a person escort record

---

app/controllers/api/v1/moves_actions.rb
app/controllers/api/v2/moves_actions.rb
app/models/move.rb
db/migrate/20200728090010_remove_nomis_event_ids_from_moves.rb
db/schema.rb
lib/tasks/data_maintenance.rake
lib/tasks/fake_data.rake
spec/models/move_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/services/alerts/importer_spec.rb

P4-1949 P4-1499
It seems that in the distant past, Nomis events were imported from Nomis and used to create associated moves in PECS. When first implemented, the original Nomis event id was stored in the move `nomis_event_id` attribute as these have a 1:1 mapping with moves. Also these imported moves were treated as read only so that they could not be modified via the API (which would presumably be a bad thing).
Time passed...
Subsequently it was discovered that court hearings break the original 1:1 mapping approach with the same prisoner potentially having multiple court hearings (for different offences) on the same date and location, which means a move cannot be created for each event. Nomis stores each individual court hearing as a separate event; so at that point `nomis_event_ids` was …

Remove dead nomis_event_ids attribute from moves

---

.env.example

P4-1982
We need to be able to disable logging on Appinsights.
Logging is causing some timeout issues and also it is not used, since the main logging tools we use is Kibana.
No risk.

Add APPINSIGHTS_LOGGING_ENABLED env var 

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
spec/factories/move.rb
spec/services/moves/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

[P4-1793](https://dsdmoj.atlassian.net/browse/P4-1793)
Add new filter to return all moves ready to be in transit if set to true. Moves ready for transit are moves where the person escort record is confirmed.
A move is not ready to be in transit if there is no person escort record attached, or if the status is not confirmed. This filter will be used on the FE dashboard for moves.
- Adds a filter to an api that is used in production

P4-1793 Add `ready_for_transit` filter on moves

---

app/controllers/api/move_events_controller.rb
app/lib/nomis_client/allocations.rb
app/lib/nomis_client/base.rb
app/lib/nomis_client/court_hearings.rb
app/models/move_event.rb
app/services/allocations/create_in_nomis.rb
app/services/court_hearings/create_in_nomis.rb
app/services/event_log/move_runner.rb
spec/factories/events.rb
spec/lib/nomis_client/allocations_spec.rb
spec/lib/nomis_client/court_hearings_spec.rb
spec/requests/api/move_events_controller_approve_spec.rb
spec/services/allocations/create_in_nomis_spec.rb
spec/services/event_log/move_runner_spec.rb
swagger/v1/post_move_approve.yaml

P4-1949
- This is to support creating prison to prison transfers (aka allocations) in Nomis automatically when the singleton move request is approved in the front end. Further PR's will do the same when updating existing allocation profiles.
- Note that the front end always receives a success response regardless of the Nomis response. We do not wish to block front end in the event of Nomis failure, so must return a success response. Unfortunately we do not have a mechanism to return a success response with associated warnings (e.g. the move was approved but Nomis was not updated).
- Integrates with a new (or at least not used yet) Nomis endpoint, so will require end to end testing
- Introduces a new optional attribute to existing API endpoint, so does not affect production API

Allow prison to prison transfers (allocations) to be created in Nomis

---

spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

P4-1986
- suppliers download the swagger.yaml specification in order to easily import URLs into their system

add UAT URL to swagger

---

app/models/framework_flag.rb
app/models/framework_question.rb
app/models/framework_response.rb
app/models/person_escort_record.rb
app/serializers/framework_flag_serializer.rb
app/serializers/framework_response_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/services/frameworks/question.rb
db/migrate/20200729080731_rename_flags_to_framework_flags.rb
db/schema.rb
spec/factories/framework_flag.rb
spec/models/framework_flag_spec.rb
spec/models/framework_question_spec.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/serializers/framework_flag_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/services/frameworks/importer_spec.rb
spec/services/frameworks/question_spec.rb

Currently all framework entities have `framework` prepended to the name like `framework_questions` and `framework_responses`. For consistency prepend `framework` to `flags`. 
The keys on the API responses have been set already to `flags` but the name of the resource is called `framework_flags`. This is consistent with other framework resources.
- The documentation has already been changed to framework flag previously
- There is no data currently in this table so should not affect anything in prod

Rename `flags` to `framework_flags`

---

app/models/framework.rb
app/models/person_escort_record.rb
spec/models/framework_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb

[P4-1944](https://dsdmoj.atlassian.net/browse/P4-1944)
Remove default framework version and always expect a framework version to be passed when creating a person escort record, otherwise raise an error. This avoids any unexpected behaviour or using frameworks that might include questions with breaking changes

P4-1944 Require framework on creating a person escort record

---

app/controllers/api/v2/moves_actions.rb
app/serializers/move_serializer.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/serializers/move_serializer_spec.rb
spec/swagger/swagger_doc_v2.yaml

P4-1942
- OCA users can view the moves within an allocation, and choose an appropriate person to be moved. This updated person relationship is sent via a PATCH to the move. The front end can now include the additional param when the corresponding checkbox is ticked and have the move created in Nomis.
- The front can check that the Nomis event was created by checking presence of `nomis_event_id` attribute. If present the Nomis event was created, if `nil` it was not created; Nomis can return an error if e.g. the prisoner is not currently booked into the same from location - we still want to return a success response to the front end.
- A query parameter makes more sense in this instance as the included attributes in the body are all attributes of a move.
- Adds an extra query string param, …

Create prison to prison transfer in Nomis when adding person to allocation

---

app/controllers/api/v1/moves_actions.rb
app/controllers/api/v2/moves_actions.rb
app/services/moves/finder.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1993
* Add PER includes in single Move endpoint to avoid N+1 queries
* Include all other resources in multiple moves GET endpoint
This list was compiled from the Bullet gem
[P4-1993]( https://dsdmoj.atlassian.net/browse/P4-1993)
To avoid N+1 queries add the required includes on a Move Endpoint. I used the [Bullet gem](https://github.com/flyerhzm/bullet) to flush out the full list of required includes. I tested this with the following variations to make sure we don't cause any performance issues with/without Includes:
Single Move with/without includes
Multiple Moves
- with filters with time range
- with filters without time range
- with one include
- with no includes
- with all includes
- Changes an api and performance that is used in …

P4-1993 Include resources in move endpoint to improve performance

---

Gemfile.lock

P4-1982
- The updated gem allows disabling the forwarding of logs to Azure AppInsights, which was found causing performance issues.

Bumps appinsights gem to support disabling log forwarding

---

app/services/moves/finder.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-1993
Add includes when fetching multiple moves. This avoids N+1 queries
[P4-1993]( https://dsdmoj.atlassian.net/browse/P4-1993)
To avoid N+1 queries, I used the Bullet gem to get a list of N+1 queries on a move. I pulled in the staging database as well to be able to benchmark things properly.
This change does not slow down current queries, and speeds them up:
1) Without `include` in params
2) With `include` in params
3) With all filters and includes in params

P4-1993 Add includes on move endpoint

---

app/controllers/api/people_controller.rb
app/controllers/api/v1/people_actions.rb
app/controllers/api/v2/people_actions.rb
spec/requests/api/people_controller_index_spec.rb
spec/requests/api/people_controller_index_v2_spec.rb
spec/swagger/swagger_doc_v1.yaml

https://dsdmoj.atlassian.net/browse/P4-1252
If you query the GET /people endpoint with no filters it returns a `400` saying a filter is required.
The expected behaviour is:
Without the filter, or without a valid filter, the index people endpoint should return all the entries.
Other endpoints (see /moves)  do not expect the filters to be mandatory.

Allow filter for /people to be empty

---

app/lib/nomis_client/allocations.rb
app/lib/nomis_client/base.rb
app/services/allocations/create_in_nomis.rb
app/services/allocations/remove_from_nomis.rb
app/services/event_log/move_runner.rb
spec/fixtures/files/nomis_put_bookings_400.json
spec/fixtures/files/nomis_put_bookings_404.json
spec/fixtures/files/nomis_put_bookings_500.json
spec/lib/nomis_client/allocations_spec.rb
spec/lib/nomis_client/base_spec.rb
spec/requests/api/move_events_controller_cancel_spec.rb
spec/services/allocations/create_in_nomis_spec.rb
spec/services/allocations/remove_from_nomis_spec.rb
spec/services/event_log/move_runner_spec.rb
spec/support/with_nomis_client_auth_context.rb

P4-1950
- When moves are cancelled any corresponding transfer in event should be removed to keep Nomis in sync. The new service uses the persisted `nomis_event_id` attribute to determine if there is an existing Nomis transfer event (this is assigned when calling `Allocations::CreateInNomis` service). On success the `nomis_event_id` is cleared so that calling the service again has no effect. This cancellation behaviour is automatically applied for all move cancellations but only calls Nomis when an event id is stored on the move.
- Changes behaviour for an existing API (cancelling move), but has no effect unless event was previously created

Automatically cancel Nomis prison transfer events when cancelling move

---

lib/tasks/inspect_move.rake

P4-2008
- to help with supplier testing and assurance
```
$ rake 'inspect:move[PXJ2479F]'
MOVE RECORD
-----------
id:		a8c06937-475b-4342-a5e2-5586cb28eecd
reference:	PXJ2479F
date:		2020-04-27
status:		requested
move type:	court_appearance
from location:	Oakhill Secure Training Centre
to location:	Houghton-le-Spring Youth Court
created at:	2020-04-27 12:46:06 +0100
updated at:	2020-04-27 12:46:06 +0100
additional information: 
MOVE EVENTS
-----------
(no events recorded)
JOURNEYS
--------
ID					TIMESTAMP			STATE		FROM --> TO
855923bf-9cfd-4e53-a12c-1065d05ee954	2020-04-27 05:00:00 +0100	completed	Oakhill Secure Training Centre --> Yarls Wood AIT
9b4b6c18-a6c0-454e-b9b4-c0534f14e885	2020-04-27 05:43:00 +0100	completed	Yarls Wood AIT …
```

P4-2008 simple rake task for printing out a move

---

spec/swagger/swagger_doc_v2.yaml
swagger/v1/journey_reference.yaml
swagger/v2/event.yaml
swagger/v2/get_events_responses.yaml
swagger/v2/post_event_responses.yaml

P4-1973
I have added documentation for:
We need this to flag implementation detail early on to suppliers.

[P4-1973] Adds swagger documentation for events endpoints

---

app/models/profile.rb

P4-<TODO>
- Ignore unused columns on profile
I noticed them when dumping attributes of a profile just now.
They'll confuse new developers since they aren't used/populated.

Ignore columns that need to be removed from the Profile model

---

db/migrate/20200729191640_drop_person_id_from_moves.rb

P4-<TODO>
```sh
│ -- remove_foreign_key(:moves, {:column=>:person_id, :name=>"fk_rails_moves_person_id", :to_table=>:people})
Caused by:                                                                                                                                                                                                                                                 │
│ ArgumentError: Table 'moves' has no foreign key for people                                                                                                                                                                                                 │
│ /usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1382:in …
```

Foreign key names are dynamically generated

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
app/services/moves/params_validator.rb
db/migrate/20200805154106_add_index_to_people_date_of_birth.rb
db/schema.rb
spec/services/moves/finder_spec.rb
spec/services/moves/params_validator_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

P4-1995
- We wish to support showing moves only for people with specific age ranges. Rather than pass in an age (which could include a number of years and/or months), this requires the front end to determine a specific date based on the current date and pass corresponding date range. Agreed this approach during refinement as it is more flexible and avoids having to invent a new mechanism for passing age in year and month parameters.
- Includes support for additional filters, but these do not affect returned moves if not specified

Add support for filtering moves by person date_of_birth attribute

---

lib/tasks/data/regions.yml

P4-1931
- This allows moves for these locations to be viewed as part of the youth region. The Nomis agency id's for these are as follows (note - there is no STC7):
Wetherby - WYI
Werrington - WNI
Parc - PRI
Feltham YOI - FMI
Cookham Wood - CKI
Rainsbrook - STC1
Oakhill - STC3
Vinney Green - SCH9
Hillside - SCH6
Barton Moss - SCH4
Aycliffe - SCH3
Aldine House - SCH2
Lincolnshire - SCH8
Adel Beck - SCH1
Clayfields - SCH5

Add additional STC and SCH locations to Youth region

---

app/controllers/api/v2/moves_actions.rb
app/models/move.rb
app/services/moves/move_type_validator.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/services/allocations/create_in_nomis_spec.rb
spec/services/moves/finder_spec.rb
spec/services/moves/move_type_validator_spec.rb
spec/services/moves/updater_spec.rb
swagger/v1/move.yaml

P4-1851
- We need to support a richer set of move types (already implemented in previous PR's) so cannot rely on move type being derived automatically in the back end API. Instead clients (front end and suppliers) must specify the `move_type` explicitly when creating a move under v2 `POST /moves` endpoint. v1 endpoint will still allow `move_type` to be omitted.
- This is a breaking change for v2 - which is in use now, so needs collaboration with front end devs and communication with suppliers before this can be merged. Will also require end to end test suite to pass successfully (currently this will break as `move_type` is not specified by front end code).

Enforce move_type attribute to be specified for v2 move creation

---

config/initializers/kaminari_config.rb
swagger/v1/pagination_parameters.yaml

P4-2027
- This allows the front end to request a larger page size if required (currently maximum is 100 rows). This doesn't change the default page size if pagination params are not specified. We also need to do some real world testing (maybe on staging) to see at what point the back end API starts to break down with larger page sizes.
- No risk unless passing larger page size params from front end or suppliers
- There is a significant risk performance will degrade with larger page sizes, but this needs to be tested on a realistic environment such as staging.

Bump up maximum pagination limit for Kaminari

---

lib/tasks/data/regions.yml

P4-1931
- On testing this against dev environment, only 14 locations got mapped rather than the expected 15. The missing one was Rainsbook which has `nomis_agency_id` of `STC2` rather than `STC1`.

Fix nomis_agency_id for Rainsbrook STC in Youth Region

---

Gemfile.lock

Reverts ministryofjustice/hmpps-book-secure-move-api#808

Revert "Bump prometheus_exporter from 0.4.13 to 0.5.3"

---

Gemfile.lock

Reverts ministryofjustice/hmpps-book-secure-move-api#817

Bump prometheus_exporter from 0.4.13 to 0.5.3"

---

app/models/notification.rb
app/services/feeds/notification.rb
db/migrate/20200813104335_adds_index_on_updated_at_to_notification.rb
db/schema.rb
lib/tasks/feeds/notification.rake
spec/factories/notification.rb
spec/models/notification_spec.rb

[P4-2015] Adds feed for Notification model

---

app/models/location.rb
spec/factories/move.rb
swagger/v1/location.yaml

P4-2048
- Whilst this seems reckless and controversial, the YOI type is never actually used. We have no locations of this type on any environment; instead all YOI locations are held within Nomis (and hence imported to PECS) as `prison` type. This change does not remove or affect any existing data, but does clear up some confusion by appearing to support a location type that is not actually supported. We should align with Nomis data and treat YOI locations as prisons.
- This location type is not used in production as we do not have (and have never had) any locations with a type of `youth_offending_institute`. As we have no YOI type locations, there are no moves created with YOI type locations, as moves cannot be created without specifying valid locations. Other than updating the Swagger …

Remove unused/confusing YOI location type

---

app/services/moves/move_type_validator.rb
spec/services/moves/move_type_validator_spec.rb

P4-2047
- This is to support `prison_transfer` type moves from STC and SCH locations in addition to the existing Prison locations.
- The new rules are more permissive so should not break any existing production use

Support prison_transfer moves from prison, STC or SCH locations

---

app/models/document.rb

P4-<TODO>
To avoid confusion about this field actually being used=

Ignore move_id in documents

---

app/controllers/api/v2/moves_actions.rb
app/controllers/api_controller.rb
app/models/move.rb
app/services/moves/exporter.rb
spec/requests/api/moves_controller_index_v2_spec.rb
spec/services/moves/exporter_spec.rb
swagger/v2/accept_type_parameter.yaml

P4-2028
- The existing approach for downloading CSV files in the front end uses the API to retrieve all of the relevant moves (normally 1 weeks worth for a given location) in JSONAPI format, and then reformats to a second JSON representation, then serializes that to a CSV format. This is far from efficient, so this new approach generates the CSV in the backend without involving any unnecessary JSON conversion - it simply uses ActiveRecord relationships and writes to a temporary file.
- Adding an additional content type to the existing v2 endpoint means that we can leverage all of the existing filters on the `GET /moves` endpoint - these are already well tested, so clients can obtain exactly the required moves.
- The simple synchronous approach adopted means we only require a `Tempfile` on …

Add support for returning GET /moves endpoint in CSV format

---

app/models/framework_question.rb
app/services/frameworks/question.rb
spec/fixtures/files/frameworks/person-escort-record-1/manifests/property-information.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/property-bag-seal-number.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/property-bag-type.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/property-bags.yml
spec/models/framework_question_spec.rb
spec/services/frameworks/importer_spec.rb
spec/services/frameworks/question_spec.rb

[P4-2004](https://dsdmoj.atlassian.net/browse/P4-2004)
To support importing questions which require multiple items, add new type of question which allows multiple questions to exist grouped by this question. The child questions are created without a dependent value.

1 - P4-2004 Add support for importing `add_multiple_items` questions

---

app/jobs/notify_webhook_job.rb
spec/jobs/notify_webhook_job_spec.rb

Parse response and extract error message from body, to help debugging of webhook errors. The raw response with an error coming from the server has the following structure:
```
{"resource"=>"/suite/webapi/getMOJEvents", "error"=>"APNX-1-4187-005", "message"=>"User password has expired. Please sign in using a web browser to change your password.", "title"=>"An Error Has Occurred"}
```
If the structure is different we should get empty values

Improve error message for webhook notifications

---

app/models/framework_question.rb
app/models/framework_response/collection.rb
app/models/framework_response/multiple_item_object.rb
app/models/framework_response/multiple_items_collection.rb
spec/factories/framework_question.rb
spec/factories/framework_response.rb
spec/models/framework_question_spec.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response/multiple_item_object_spec.rb
spec/models/framework_response/multiple_items_collection_spec.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb

[P4-2004](https://dsdmoj.atlassian.net/browse/P4-2004)
Add a new collection response type: multiple items. Each multiple items list contains a multiple item object which encapsulates the item and the corresponding responses. It applies the validations to that object and bubbles them up to the collection appropriately.
This type of question has nested questions which do not have corresponding responses, but rather those responses are encapsulated in the parent question, mapped to the item they are associated to. 
Since the responses provided for the item mirror framework responses, validate those on update (if normal validation added it allows them to be empty which we don't want). Scope validations to an index of the responses and the items to avoid overwriting validation messages. This …

2 - P4-2004 Add support for creating `add_multiple_items` responses

---

app/controllers/api/framework_responses_controller.rb
app/serializers/framework_question_serializer.rb
app/serializers/framework_response_serializer.rb
app/serializers/person_escort_record_serializer.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/serializers/framework_question_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
swagger/v1/framework_question.yaml
swagger/v1/framework_response.yaml
swagger/v1/framework_response_include_parameter.yaml
swagger/v1/person_escort_record_include_parameter.yaml

[P4-2004](https://dsdmoj.atlassian.net/browse/P4-2004)
To allow multiple item responses to be updated, permit nested `item` and `responses` attributes for framework responses.
Since value supports multiple types we have to mirror that in the permitted attributes by supporting both a nested string and object.
Since we are allowing the client to build the nested responses, they require the response type to be exposed. We can do this on the framework questions, which now have both `question_type` as well as `response_type`.
Expose a different response type for add multiple items, since this will indicate that this type of response is structured differently. Since migrating existing types is more involved, we are deferring it for later.

3 - P4-2004 Add support for PATCHing `add_multiple_items` responses

---

app/controllers/api/move_events_controller.rb
app/models/move_event.rb
app/services/event_log/move_runner.rb
spec/requests/api/move_events_controller_redirect_spec.rb
swagger/v1/move.yaml
swagger/v1/move_type_attribute.yaml
swagger/v1/post_move_redirect.yaml
swagger/v2/move.yaml

P4-2031
- If a move is redirected to a location which requires a new `move_type` then currently it's not possible to so as the move type cannot be changed after the move is created. This limits the flexibility for some move scenarios. This PR adds support for an extra `move_type` parameter to be passed in the redirect event (if not passed then existing move_type is retained). Existing move type validation logic ensures that the specified to_location and move_type combination remains valid. 
- Existing API behaviour is unchanged if new parameter is not specified, so low risk

Allow move_type to be updated when redirecting a move

---

app/serializers/person_escort_record_serializer.rb

introducing dependents is causing some n+1 queries whilst fetching the PER with questions associating on flags and responses. Double dependents is as fun as it sounds...
```
[active_model_serializers]   ↳ app/controllers/api/person_escort_records_controller.rb:61:in `render_person_escort_record'
[active_model_serializers]   FrameworkQuestion Load (17.2ms)  SELECT "framework_questions".* FROM "framework_questions" WHERE "framework_questions"."parent_id" = $1  [["parent_id", "40c3de38-75db-46fd-826a-0b34fd6fd5a4"]]
[active_model_serializers]   ↳ app/controllers/api/person_escort_records_controller.rb:61:in `render_person_escort_record'
[active_model_serializers]   FrameworkQuestion Load (18.0ms)  SELECT "framework_questions".* FROM "framework_questions" WHERE "framework_questions"."id" = $1 …
```

Include dependents in PER serializer to avoid n+1 queries

---

app/serializers/move_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/v2/move_serializer.rb
swagger/v1/move_include_parameter.yaml
swagger/v1/person_escort_record_include_parameter.yaml
swagger/v2/move_include_parameter.yaml

To expose the descendant questions resource on a Move, add to include list.
Update since descendants are nested and hierarchical we need to use `**` to allow includes for more than one level: https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/adapters.md#include-option 
I kept the response at a single level as we will never need to support multiple nested resources at that level, this is only on the PER or Move

Expose dependents on move endpoint for PER questions

---

app/jobs/prepare_move_notifications_job.rb
app/models/notification.rb
lib/tasks/notifications.rake
spec/jobs/prepare_move_notifications_job_spec.rb

P4-2038
- so that on go live suppliers can synchronise their system with ours
- pretty minimal

P4 2038 generate future move notifications

---

lib/tasks/fake_data.rake

- We use this rake task for local testing/development

Fix fake_data.rake

---

swagger/v2/event.yaml

P4-1975
- timestamp is actually client_timestamp in the database
- event_name is being deprecated in favour of event_type (which maps onto type in the database, but type isn't a compatible json:api key)

[P4-1975] Fix event swagger

---

app/controllers/api/suppliers_controller.rb
config/routes.rb
spec/requests/api/suppliers_controller_locations_spec.rb

https://dsdmoj.atlassian.net/browse/P4-2063
One of the tasks, before going live, is
to provide an endpoint to get a list of locations for which the suppliers own the moves (from_location)
The locations will be a unique list of the relevant move from_location locations.
I have added a new controller SuppliersController and the action locations.
read the https://dsdmoj.atlassian.net/browse/P4-2063 for an extensive explanation
Not necessary, we do not want to make it public for now
No, it does not change the existing endpoints.

Add new endpoint /suppliers/:supplier_id/locations 

---

spec/requests/api_stories/move_workflows/1_police_to_police/1_1_person_with_police_national_computer_spec.rb
spec/requests/api_stories/move_workflows/2_police_to_unspecified/2_1_person_with_police_national_computer_to_unspecified_prison_spec.rb
spec/requests/api_stories/move_workflows/5_court_to_prison/5_1_person_with_nomis_prison_number_spec.rb
spec/requests/api_stories/move_workflows/6_prison_to_prison_ipt/6_1_singleton_known_person_spec.rb

P4-<TODO>
- so they can be excluded with `rspec --tag ~@api_story`

fix api_story tags

---

.circleci/config.yml

n/a
- If there are images without any tags, it will cause an issue later when we try to filter out images based on tags.
If they don't have a tag, we don't want to keep it anyway.

Fix ecr cleanup

---

app/controllers/api/moves_controller.rb
app/controllers/api/v1/moves_actions.rb
app/controllers/api/v2/moves_actions.rb
app/controllers/api_controller.rb
config/routes.rb
spec/requests/api/moves_controller_csv_spec.rb
spec/requests/api/moves_controller_index_v2_spec.rb
swagger/v2/accept_type_parameter.yaml

P4-2028
- The original endpoint chosen for this aligned with Rails idioms with a GET verb - primarily chosen as it's returning a list of moves. Whilst this works fine the use of GET imposes a limitation in the length of the passed URL query string - tested to be around 8k characters. This limit is set within the web hosting infrastructure so is not easy to get around.
- Some of the users have a large list of locations they can access, so building a request that specifies each of the required location id filters results in a 10k request - this was blowing up with a 413 error because of the request size. This could be better architected by performing location authorisation in the API rather than the front end (passing some user info to the API instead of locations), but that's a longer term …

Different endpoint for returning moves in CSV format

---

app/services/moves/exporter.rb

P4-2028
- It looks like the Tempfile wasn't flushing incomplete buffers, which meant for small number of moves nothing gets returned. This fixes it.

Ensure that output buffer is flushed when generating CSV

---

.circleci/config.yml

n/a
- The sidekiq container was renamed as it was colliding with the webapp one. This makes the deployment target the correct new name

Match renamed sidekiq container name

---

app/controllers/api/framework_responses_controller.rb
app/models/framework_response.rb
app/models/framework_response/array.rb
app/models/framework_response/collection.rb
app/models/framework_response/multiple_item_object.rb
app/models/framework_response/object.rb
app/models/framework_response/string.rb
spec/models/framework_response/array_spec.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response/multiple_item_object_spec.rb
spec/models/framework_response/multiple_items_collection_spec.rb
spec/models/framework_response/object_spec.rb
spec/models/framework_response/string_spec.rb
spec/models/framework_response_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb

[P4-2061](https://dsdmoj.atlassian.net/browse/P4-2061)
Check the response type on setting the value in the base response class to avoid having to check errors in validations
later on, which has caused us to duplicate type validation across multiple points when creating/updating records to avoid random errors.
Now we first call super on value setting which checks the type, and fails if it is invalid.
The same is done in the multiple item object, where now the validation error is in the initialisation to avoid duplicating checking the type everywhere.
Can be tested on https://booksecuremove-br-master.herokuapp.com/

P4-2061 Fix type validation in Framework Responses

---

README.md
app/controllers/api/allocations_controller.rb
app/controllers/api/v1/moves_actions.rb
app/controllers/api/v2/moves_actions.rb
app/models/location.rb
app/models/move.rb
app/models/supplier.rb
app/models/supplier_location.rb
app/services/allocations/creator.rb
app/services/event_log/move_runner.rb
app/services/locations/finder.rb
app/services/moves/finder.rb
app/services/moves/updater.rb
app/services/supplier_chooser.rb
lib/tasks/reference_data.rake
spec/models/location_spec.rb
spec/models/move_spec.rb
spec/models/supplier_location_spec.rb
spec/models/supplier_spec.rb
spec/requests/api/move_events_controller_approve_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/services/allocations/creator_spec.rb
spec/services/locations/finder_spec.rb
spec/services/moves/updater_spec.rb
spec/services/supplier_chooser_spec.rb

P4-2041 P4-2062
- New SupplierLocation model supports effective dates for supplier contracts. We need to ensure that moves are assigned the correct supplier based on the move date - the location mapping changes either side of the go live date.
- Whenever the move date changes we need to determine the supplier location again as it may potentially have changed. If the date doesn't change then we can skip the update and avoid an extra database query.
- The legacy table `locations_suppliers` was used only for the HABTM relationship and is now ignored (will be removed in a future PR). The legacy rake task to populate that is hence no longer needed.
- This affects a few API's but should not be a breaking change providing the SupplierLocation data is correctly populated before deploying this PR. …

Use move date/date_from to determine correct supplier for move

---

config/puma.rb

P4-2098
- We're debugging slow requests and want to understand the puma queue backlog/active thread counts, etc.

[P4-2098] Adds puma instrumentation

---

lib/tasks/notifications.rake

P4-2038
- We can't determine move owner solely by location any more - this instead needs to consider the effective date (implemented in SupplierChooser service). However it's also a little beyond the scope of this rake task to be updating the supplier - we have another rake task to do that, so I've updated this to just report if there any moves found without a supplier assigned, but otherwise ignore those when sending out notifications.

Update notifications rake task to avoid assuming ownership of moves

---

app/services/moves/exporter.rb
spec/services/moves/exporter_spec.rb

P4-2102
- Suppliers don't want this column as apparently it's redundant, and the information needed can be obtained from the "Not to be released" column instead.
- Resolves a production API issue

Remove "Not for release" columns from CSV export

---

app/models/move.rb
spec/models/move_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml
swagger/v1/move.yaml
swagger/v1/move_cancellation_reason_attribute.yaml
swagger/v2/move.yaml
swagger/v2/patch_move.yaml

P4-2055
- We need to support this in the front end.
- Changes an api that is used in production (but is not a breaking change)

Add new move cancellation reason

---

app/services/supplier_chooser.rb
spec/services/supplier_chooser_spec.rb

P4-<TODO>
- Moves created by suppliers include locations that are not mapped in the supplier_location.yml file. We need to come up with a nice solution for this, potentially reverting to the previous approach based on the doorkeeper_application_owner. As a short term fix we are going live with just one supplier, Serco, so can make the assumption that any moves created without an appropriate SupplierLocation mapping will have been created by Serco.
- This removes the immediate blocker to going live and gives us time to work on a longer term fix to support further suppliers, and is also a simple change to understand/review.

Quick fix for go live with Serco

---

.env.example
config/puma.rb

To avoid `Prometheus Exporter, failed to send message Connection refused` in ENVs that don't have prometheus hooked up, make this optional according to ENV variable. This mirrors the setup in prometheus exporter initializer

Disable Prometheus by default

---

app/models/framework_question.rb
app/serializers/framework_question_serializer.rb
app/serializers/framework_response_serializer.rb
spec/factories/framework_response.rb
spec/models/framework_question_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/serializers/framework_question_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
swagger/v1/framework_question.yaml
swagger/v1/framework_response.yaml

[P4-2080](https://dsdmoj.atlassian.net/browse/P4-2080)
We currently support `collection::add_multiple_items` for a response that is a collection and of type multiple items. To
extend this pattern to other exact collections and objects, append `::followup_comment` to object and collection if it has followup comments. If another type of collection or object is added, we will add that type to those respectively. This will help the FE render the correct type of response.
This is a breaking change and has to be coordinated with the FE.

P4-2080 Support additional framework response types

---

lib/tasks/journeys_report.rake

Make sure a person, person DOB and move date exist before attempting to calculate person's age in journey report

Guard against empty move dates when calculating age in Journey reports

---

db/migrate/20200828145744_remove_locations_suppliers.rb
db/schema.rb

https://dsdmoj.atlassian.net/browse/P4-2100
The table `locations_suppliers` has been replaced by `supplier_locations` (which now keep the relationship suppliers-locations within effective dates)
So `locations_suppliers` should be removed.
`locations_suppliers` is not used anymore.

Remove redundant `locations_suppliers` table

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
app/services/moves/params_validator.rb
spec/factories/move.rb
spec/requests/api/moves_controller_filter_spec.rb
spec/requests/api/moves_controller_filter_v2_spec.rb
spec/services/moves/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

P4-2059
- This supports front end requirements to get a list of moves that are not rejected (By specifying a value of `nil` for the new filter). Follows existing patterns for other filters, also improved spec coverage slightly and refactored filter specs to avoid creating lots of unnecessary fixtures (now slightly faster).
- Extends production API, but is backwards compatible. New filter is optional.

Add a new GET /moves filter for rejection reason

---

app/lib/nomis_client/base.rb
spec/lib/nomis_client/activities_spec.rb
spec/lib/nomis_client/allocations_spec.rb
spec/lib/nomis_client/court_cases_spec.rb
spec/lib/nomis_client/court_hearings_spec.rb
spec/wiremock/prison-api/mappings/elite2api_api_bookings_offenderno_alerts-88bf8e3c-ca15-4af2-98f6-022dcb9f72f2.json
spec/wiremock/prison-api/mappings/elite2api_api_bookings_offenderno_personal-care-needs-dcb2c2b0-5b51-412f-86a0-c8034c5f9206.json
spec/wiremock/prison-api/mappings/elite2api_api_prisoners-0fe4f90b-2609-4749-a7eb-02fbdb68509e.json
spec/wiremock/prison-api/mappings/elite2api_api_reference-domains_domains_alert-2a9c3aa2-2e54-4d26-9268-e23aefa1d3cd.json
spec/wiremock/prison-api/mappings/elite2api_api_reference-domains_domains_alert_code-a79bc685-519f-4cda-8cd0-0e2b4f1ec15e.json
spec/wiremock/prison-api/mappings/elite2api_api_reference-domains_domains_ethnicity-a5e4e845-fbe7-4e85-acd9-3b54b7664c61.json
spec/wiremock/prison-api/mappings/elite2api_api_reference-domains_domains_sex-3c1ad947-cef0-4a62-bde1-3910a5c6e41e.json

P4-2068
- The prison api is now separate from the auth api

[P4-2068] Separate auth and prison api urls and update prefix

---

.env.test
spec/support/mock_prison_api.rb

P4-<TODO>
- We use wiremock so we don't call nomis in test envs. We should match this behaviour like before.

Update .env.test to include new environment variables

---

app/models/move.rb
spec/factories/move.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/jobs/prepare_person_escort_record_notifications_job_spec.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_approve_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/requests/api_stories/move_workflows/1_police_to_police/1_1_person_with_police_national_computer_spec.rb
spec/requests/api_stories/move_workflows/2_police_to_unspecified/2_1_person_with_police_national_computer_to_unspecified_prison_spec.rb
spec/requests/api_stories/move_workflows/5_court_to_prison/5_1_person_with_nomis_prison_number_spec.rb
spec/requests/api_stories/move_workflows/6_prison_to_prison_ipt/6_1_singleton_known_person_spec.rb
spec/services/event_log/move_runner_spec.rb
spec/services/moves/finder_spec.rb
spec/services/moves/updater_spec.rb
spec/support/with_nomis_alerts_seed_data.rb

https://dsdmoj.atlassian.net/browse/P4-2101
Make the relation **Move - Supplier** not optional.
When a move is created or updated, a supplier should always be set.

Making supplier_id not optional.

---

lib/tasks/data/supplier_locations_go_live.yml

P4-2166
- it was incorrectly mapped to Serco
- Already manually fixed on Production last week

P4-2166 fix Brecon Custody Suite mapping

---

config/application.rb
spec/requests/api/people_controller_index_v2_spec.rb
spec/swagger/swagger_doc_v2.yaml
swagger/v2/accept_encoding.yaml

https://dsdmoj.atlassian.net/browse/P4-2175
Add support for: Accept-Encoding: gzip, deflate
I have added support for **Accept-Encoding** in the header,
gzip and/or deflate values are supported
To sped up API requests
No risks, the compressed encoding is optional.

Add support for compressed requests.

---

app/models/concerns/move_event_validations.rb
app/models/generic_event.rb
app/models/generic_event/move_accept.rb
app/models/generic_event/move_approve.rb
app/models/generic_event/move_cancel.rb
app/models/generic_event/move_complete.rb
app/models/generic_event/move_lockout.rb
app/models/generic_event/move_redirect.rb
app/models/generic_event/move_reject.rb
app/models/generic_event/move_start.rb
spec/factories/generic_event.rb
spec/models/generic_event/move_accept_spec.rb
spec/models/generic_event/move_approve_spec.rb
spec/models/generic_event/move_cancel_spec.rb
spec/models/generic_event/move_complete_spec.rb
spec/models/generic_event/move_lockout_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/generic_event/move_reject_spec.rb
spec/models/generic_event/move_start_spec.rb

P4-1979
- We need these as part of the generic and existing event apis

[P4-1979] Adds move events

---

app/controllers/concerns/journeys/eventable.rb
app/models/event.rb
app/models/generic_event.rb
app/models/generic_event/journey_cancel.rb
app/models/generic_event/journey_complete.rb
app/models/generic_event/journey_lockout.rb
app/models/generic_event/journey_lodging.rb
app/models/generic_event/journey_reject.rb
app/models/generic_event/journey_start.rb
app/models/generic_event/journey_uncancel.rb
app/models/generic_event/journey_uncomplete.rb
app/services/event_log/move_runner.rb
spec/models/generic_event/journey_cancel_spec.rb
spec/models/generic_event/journey_complete_spec.rb
spec/models/generic_event/journey_lockout_spec.rb
spec/models/generic_event/journey_lodging_spec.rb
spec/models/generic_event/journey_reject_spec.rb
spec/models/generic_event/journey_start_spec.rb
spec/models/generic_event/journey_uncancel_spec.rb
spec/models/generic_event/journey_uncomplete_spec.rb
spec/models/generic_event_spec.rb
spec/requests/api/journey_events_controller_cancel_spec.rb
spec/requests/api/journey_events_controller_complete_spec.rb
spec/requests/api/journey_events_controller_lockouts_spec.rb
spec/requests/api/journey_events_controller_lodgings_spec.rb
spec/requests/api/journey_events_controller_reject_spec.rb
spec/requests/api/journey_events_controller_start_spec.rb
spec/requests/api/journey_events_controller_uncancel_spec.rb
spec/requests/api/journey_events_controller_uncomplete_spec.rb
spec/spec_helper.rb

P4-2161
We're dual writing so we can safely migrate from event v1 -> generic_event v2.

[P4-2161] Dual write journey events

---

app/controllers/concerns/journeys/eventable.rb
spec/requests/api/journey_events_controller_cancel_spec.rb
spec/requests/api/journey_events_controller_complete_spec.rb
spec/requests/api/journey_events_controller_lockouts_spec.rb
spec/requests/api/journey_events_controller_lodgings_spec.rb
spec/requests/api/journey_events_controller_reject_spec.rb
spec/requests/api/journey_events_controller_start_spec.rb
spec/requests/api/journey_events_controller_uncancel_spec.rb
spec/requests/api/journey_events_controller_uncomplete_spec.rb

P4-<TODO>
I'm adding a reference from event -> generic_event in my rake task that enables use to avoid creating duplicate generic_events/means we can run the rake task over and over and get the same effect.
Dual writing events currently breaks this contract. In this PR I'm disabling the dual write functionality and will deploy/clear out generic events in all environments in a console. We then need to merge the rake task/migration which enables the reference and then switch on dual writing events.
- We need to make sure we can safely rollback copied events/avoid duplicates via a reference. Currently written generic events are missing this reference and need removing.

Disable dual writing temporarily

---

app/models/generic_event/move_accept.rb
app/models/generic_event/move_approve.rb
app/models/generic_event/move_cancel.rb
app/models/generic_event/move_complete.rb
app/models/generic_event/move_lockout.rb
app/models/generic_event/move_redirect.rb
app/models/generic_event/move_reject.rb
app/models/generic_event/move_start.rb
spec/models/generic_event/move_accept_spec.rb
spec/models/generic_event/move_approve_spec.rb
spec/models/generic_event/move_cancel_spec.rb
spec/models/generic_event/move_complete_spec.rb
spec/models/generic_event/move_lockout_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/generic_event/move_reject_spec.rb
spec/models/generic_event/move_start_spec.rb

https://dsdmoj.atlassian.net/browse/P4-2161
Adds move events builder: 
We need to avoid mutual dependencies during the migration to using generic_events table in the v1 endpoints to avoid issues with maintaining two tables in future.

P4 2161 dual write events

---

app/controllers/concerns/journeys/eventable.rb
app/controllers/concerns/moves/eventable.rb
app/models/generic_event/move_approve.rb
spec/requests/api/journey_events_controller_cancel_spec.rb
spec/requests/api/journey_events_controller_complete_spec.rb
spec/requests/api/journey_events_controller_lockouts_spec.rb
spec/requests/api/journey_events_controller_lodgings_spec.rb
spec/requests/api/journey_events_controller_reject_spec.rb
spec/requests/api/journey_events_controller_start_spec.rb
spec/requests/api/journey_events_controller_uncancel_spec.rb
spec/requests/api/journey_events_controller_uncomplete_spec.rb
spec/requests/api/move_events_controller_accept_spec.rb
spec/requests/api/move_events_controller_approve_spec.rb
spec/requests/api/move_events_controller_cancel_spec.rb
spec/requests/api/move_events_controller_complete_spec.rb
spec/requests/api/move_events_controller_lockout_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/move_events_controller_reject_spec.rb
spec/requests/api/move_events_controller_start_spec.rb

P4-2161
- This is needed so that we can migrate to the new event model

[P4-2161] Dual write events

---

app/models/event.rb
app/services/event_copier.rb
lib/tasks/events.rake
spec/services/event_copier_spec.rb

P4-2162
- We need to copy all historical events as part of merging the two event tables

[P4-2162] Copy events rake task

---

app/services/moves/finder.rb

Having a nested include is causing some queries to be very slow,
due to the circular association of the dependency. This now loads quite
quickly for the filter `ready_in_transit`.
Keeping the other includes loads the moves generally quicker, but
might be slightly slower with filters.

Remove any repeat nested includes to avoid circular loading

---

app/services/event_copier.rb

P4-<TODO>
- We use the progress formatter for spec output, so it's good to avoid spamming the console with diagnostic messages using `puts`. This is just ugly:
```
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Processing 1 events ...
Processed 0 / 1 ...
.Processing 1 events ... …
```

Avoid noisy test output

---

app/controllers/api/framework_responses_controller.rb
app/models/framework_response.rb
app/services/framework_responses/bulk_update_error.rb
app/services/framework_responses/bulk_updater.rb
config/routes.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/swagger/swagger_doc_v1.yaml

P4-1799
- Suppliers cannot use the existing endpoint to `PATCH /framework_responses/:id` as they will be using mobile devices with potentially patchy communication. It's more convenient and performant for them to submit the entire set of framework responses for a PER in a single request, rather than send ~60 individual requests for each response.
- JSONAPI typically only supports updating a singular resource, but there is a draft specification for a bulk update extension which this follows. Essentially this passes an array of resources rather than just one, but each resource has the usual structure (see request specs for details).
- Implementation makes extensive use of the `activerecord-import` gem; this is able to provide bulk data upserts in a single query which means that 60 framework …

Add new endpoint for bulk update of PER framework responses

---

app/models/framework_response.rb
spec/models/framework_response_spec.rb

Since we are utilising STI in framework responses, missing the class name is causing issues when loading certain methods, as they are defined differently per response type. For instance the parent response type can be different to dependent responses, however when attempting to retrieve descendants, the parent class is being loaded, which means we are not looking at ALL framework responses.

Explicitly define the FrameworkResponse class in class methods

---

app/models/person_escort_record.rb
spec/models/framework_response_spec.rb

* Due to enum value name restrictions around prepending `not_` unstarted is used as the main enum name, but the value `not_started` is surfaced through the API.
* Fix test to use values from the set options.

Add comment to explain enum usage for unstarted and fix test

---

app/services/idempotency/store.rb
spec/services/idempotency/store_spec.rb

The `expires_in` setting will set the expiration time on the cache. It accepts seconds. 
https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-store
`expiry` does not set the `expires_in` value:
```
irb(main):019:0> Rails.cache.write('test', 'test', expiry: 3)
=> "OK"
irb(main):021:0> Rails.cache.send(:read_entry, 'test')
=> #<ActiveSupport::Cache::Entry:0x000055708b71e9a8 @value="test", @version=nil, @created_at=1600324732.0032308, @expires_in=nil>
```
`expires_in` sets the `expires_in` value:
```
irb(main):023:0> Rails.cache.write('test', 'test', expires_in: 300)
=> "OK"
irb(main):024:0> Rails.cache.send(:read_entry, 'test')
=> #<ActiveSupport::Cache::Entry:0x000055708a3475d8 @value="test", @version=nil, @created_at=1600324902.830221, @expires_in=300.0>
```
We now …

Use correct key in setting expiry for keys in cache

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
spec/requests/api/moves_controller_filter_spec.rb
spec/requests/api/moves_controller_filter_v2_spec.rb
spec/services/moves/finder_spec.rb

P4-2206
- This returns moves matching on **either** `from_location_id` **or** `to_location_id` - which allows the list of transfers in and out of a specific location to be returned in a single API call. This is to support initial work in the front end for PMU dashboard screens.
- Extends existing API but is backwards compatible; behaviour is unchanged if new filter is not specified.

Add support for filtering moves by `location_id`

---

app/services/feeds/event.rb
spec/services/feeds/event_spec.rb

P4-2244
- This will produce the agreed format for the hub.

[P4-2244] Updates event feed to use generic events

---

app/models/journey.rb
app/models/move.rb
app/services/event_log/journey_executor.rb
app/services/event_log/move_executor.rb
app/services/event_log/move_runner.rb
spec/factories/event.rb
spec/services/event_log/journey_executor_spec.rb
spec/services/event_log/move_executor_spec.rb
spec/services/event_log/move_runner_spec.rb

https://dsdmoj.atlassian.net/browse/P4-2163
Rewrite the journey and move runner classes to use the generic events that we’re now writing out in both v1/v2 apis.
To enable us to remove the v1 event writing### Have you? (optional)

Rewrite Runner using generic events

---

app/models/generic_event.rb
app/models/generic_event/journey_create.rb
app/models/generic_event/journey_update.rb
spec/factories/generic_event.rb
spec/models/generic_event/journey_create_spec.rb
spec/models/generic_event/journey_update_spec.rb

P4-2164
These events aren't documented, don't follow the standard process_event
behaviour and aren't affected by the event log.
We discovered these by auditing a migration outcome in production just
as we were going to make a breaking change.
These events are created via a controller callback for the update and
create actions: https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/5d1064f63a557f2b69eef16878ca8eb39e714e71/app/controllers/api/journeys_controller.rb#L10
- Make sure that all events are copied by the event copier

[P4-2164] Adds missing JourneyCreate and JourneyUpdate events

---

spec/swagger/swagger_doc_v1.yaml

P4-<TODO>
- to avoid confusing suppliers

update start move text

---

app/lib/nomis_client/personal_care_needs.rb
app/services/moves/import_people.rb
app/services/profiles/import_alerts_and_personal_care_needs.rb
spec/lib/nomis_client/personal_care_needs_spec.rb

To allow flexibility around the NOMIS personal care needs query, allow types to be passed in, or default to already defined personal care need types. This will allow the PER to define its own personal care need types, which can be different to the PTR.

Allow personal care need types to be passed into the NOMIS client

---

lib/tasks/fake_data/journeys.rb
spec/lib/tasks/fake_data/journeys_spec.rb

P4-<TODO>
- This is an impossible state to get into

Removes broken fake data generation

---

app/models/generic_event.rb
db/migrate/20200923102115_add_supplier_to_generic_events.rb
db/schema.rb
spec/models/generic_event_spec.rb

P4-<TODO>
- We want to make sure we're including the supplier that is currently present in the v1 apis on every generic event.

Adds supplier relationship to generic_event

---

app/models/event.rb
spec/models/event_spec.rb

P4-2265
Generic events need to have their supplier id populated as part of the migration from Event -> GenericEvent. In the original conception of GenericEvent we weren't storing the supplier_id and were instead referencing the created_by field to determine the supplier as an enum. This was inconsistent with our approach in the rest of the code base.
- For consistency
- For reporting to the hub
- This enables us to copy/create new generic events with a supplier id

[P4-2265] Adds supplier id to generic event attributes builder

---

app/models/generic_event.rb
spec/models/generic_event_spec.rb

P4-2265
- We need the supplier in the generic event feed for when we backfill the generic events for the JPC.

[P4-2265] Adds supplier to generic_event feed

---

app/services/allocations/finder.rb

IM-7
- There are quite a lot of slow API requests in production, these are all including from_location, to_location, moves and move profiles which means lots of DB queries. The design of this needs to be improved (e.g. calculating allocation progress on the backend to avoid the need to send move and profile details), but as a short term fix this should help with reducing N+1 queries and hopefully improve the immediate issue.
- Should improve performance at least slightly, but needs to be tested on some reasonably realistic data volumes

Reduce N+1 queries for GET /allocations endpoint

---

app/models/person_escort_record.rb
spec/requests/api/person_escort_records_controller_create_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2198
When a user is double clicking create the PER button, they are seeing a 500 error as opposed to be gracefully redirected to the already created PER. Ideally the API should be catching this uniqueness validation error, and returning a 422 with the relevant message, however due to the way our app is setup in production, where we have multiple instances attempting the same thing,  this isn't being caught as a validation error on uniqueness, and is falling back to the database level of
errors, and raises an exception.
I found that this article explains it pretty well: https://thoughtbot.com/blog/the-perils-of-uniqueness-validations
We have to manually catch this error if it happens. I've added tests for both instances, so now we can …

P4-2198 Fix unique profile when creating the PER error

---

app/models/person_escort_record.rb
spec/requests/api/person_escort_records_controller_create_spec.rb

We can throw a `ActiveRecord::RecordInvalid` when instantiating with record, as previously we couldn't in older rails, but its been changed: https://stackoverflow.com/questions/26024359/how-to-create-a-activerecordrecordinvalid-for-testing
This means the FE will not have to accommodate different types of errors

Use normal validation error when raising taken error

---

app/lib/cloud_data_feed.rb
lib/tasks/feeds/event.rake
spec/lib/cloud_data_feed_spec.rb

P4-2263
What
Write a script to backfill all generic events from updated_at from last 3 days of August to now.
Why
We need this for the JPC

Add new tasks to backfill generic event starting from a certain date

---

app/services/allocations/finder.rb
spec/services/allocations/finder_spec.rb

IM-21
- This was only surfaced on production, so also added a failing spec to cover the relevant scenario that was missing from unit test suite.

Fix ambiguous date column error in Allocations::Finder service

---

app/models/generic_event.rb
spec/models/generic_event/journey_lockout_spec.rb
spec/models/generic_event/journey_lodging_spec.rb
spec/models/generic_event/move_approve_spec.rb
spec/models/generic_event/move_cancel_spec.rb
spec/models/generic_event/move_lockout_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/generic_event/move_reject_spec.rb
spec/models/generic_event_spec.rb

P4-2264
- This is ugly and namespacing implementation detail that isn't relevant to the hub

[P4-2264] Remove GenericEvent:: prefix in type in feed view

---

spec/swagger/swagger_doc_v1.yaml

P4-<TODO>
- These are defined in the schema for `Location` but missing from the example location types in the ref data endpoint.

Add missing swagger docs for extra location types

---

app/controllers/api/person_escort_records_controller.rb
app/models/move.rb
app/models/person_escort_record.rb
app/serializers/person_escort_record_serializer.rb
db/migrate/20200929055929_add_move_to_person_escort_record.rb
db/schema.rb
spec/models/move_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/services/frameworks/question_spec.rb
swagger/v1/person_escort_record.yaml

[P4-2067](https://dsdmoj.atlassian.net/browse/P4-22067)
To allow the Person escort record access to a location's type, to determine if a location is a Police or Prison location for importing NOMIS resources, we need access to the Move associated to the PER. We cannot do that through the Profile, as a Profile can belong to multiple Moves. Instead we need to pass in the Move to create the Person Escort Record, and associate the Move's profile instead.
Since transitioning to passing in a Move to create a PER is a breaking change, support both Profile and Move until the FE completes the transition to only use Move. For now the Move relationship is optional.

P4-2067 Allow passing in a Move to create a Person Escort Record

---

app/services/allocations/finder.rb

Locally to query over 300 allocations this comes down from 16s to 4s, there are some circular dependencies for locations but because they are not pulling in much it seems ok

Add includes to allocation to avoid n+1 queries when including resources

---

app/models/framework_nomis_mapping.rb
app/models/framework_response.rb
app/services/framework_nomis_mappings/alerts.rb
app/services/framework_nomis_mappings/importer.rb
app/services/framework_nomis_mappings/personal_care_needs.rb
app/services/framework_nomis_mappings/reasonable_adjustments.rb
db/migrate/20201001043209_create_framework_nomis_mappings.rb
db/migrate/20201001043655_create_framework_nomis_mappings_responses.rb
db/schema.rb
spec/factories/framework_nomis_code.rb
spec/factories/framework_nomis_mapping.rb
spec/models/framework_nomis_mapping_spec.rb
spec/models/framework_response_spec.rb
spec/services/framework_nomis_mappings/alerts_spec.rb
spec/services/framework_nomis_mappings/importer_spec.rb
spec/services/framework_nomis_mappings/personal_care_needs_spec.rb
spec/services/framework_nomis_mappings/reasonable_adjustments_spec.rb

[P4-2067](https://dsdmoj.atlassian.net/browse/P4-2067)
NOMIS alerts, personal care needs as well as reasonable adjustments for a person will help users fill out the Person escort record more accurately. Each question in the PER is associated to the relevant mappings of NOMIS resource codes, or set as a fallback question if a person has NOMIS resources that are not associated to any question.
To allow users to view those associations, add an Importer which pulls in all the resources for a person, and maps them appropriately to the NOMIS response.
NOMIS codes are not unique to a question, so we need to make sure we associate mappings to each and every question a NOMIS code appears in. If this NOMIS code is not in out framework, we will group it under the fallback response with the correct …

P4-2067 Add NOMIS Mappings and Importer

---

app/models/person_escort_record.rb
app/serializers/framework_nomis_mapping_serializer.rb
app/serializers/framework_response_serializer.rb
app/serializers/move_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/v2/move_serializer.rb
spec/models/person_escort_record_spec.rb
spec/serializers/framework_nomis_mapping_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/framework_nomis_mapping.yaml
swagger/v1/framework_nomis_mapping_reference.yaml
swagger/v1/framework_response.yaml
swagger/v1/framework_response_include_parameter.yaml
swagger/v1/move_include_parameter.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/person_escort_record_include_parameter.yaml
swagger/v2/move_include_parameter.yaml

[P4-2067](https://dsdmoj.atlassian.net/browse/P4-2067)
After responses are created, import NOMIS mappings. We can only import mappings if a move is associated to the PER and the from location is a prison.
Importing is not part of the initial transaction as it is a standalone action, which is not performant can be moved to a sidekiq job in the future. 

P4-2067 Import NOMIS mappings when creating the PER

---

spec/acceptance/generic_events/runner_spec.rb

P4-2304
- See [conversation](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/997#pullrequestreview-501861810)

[P4-2304] Reinstate specs for v1 events

---

app/models/concerns/vehicle_type_validations.rb
spec/factories/generic_event.rb
spec/support/vehicle_event_with_type.rb

P4-2304
- These have been updated by the powers that be
- The two events that consume this enum aren't currently getting created so no issues updated these.

[P4-2304] Update list of possible vehicle types

---

app/models/person.rb
app/services/allocations/finder.rb

Avoid doing extra queries which ignore eager loading by sorting in memory, also add missing includes to allocation endpoint. Locally this cut down API calls from over 8seconds to 1.7seconds for 100 allocations

Sort in memory and add eager load profiles

---

app/models/person_escort_record.rb
app/serializers/person_escort_record_serializer.rb
app/services/framework_nomis_mappings/alerts.rb
app/services/framework_nomis_mappings/importer.rb
app/services/framework_nomis_mappings/nomis_sync_status.rb
app/services/framework_nomis_mappings/personal_care_needs.rb
app/services/framework_nomis_mappings/reasonable_adjustments.rb
db/migrate/20201007043824_add_nomis_sync_status_to_person_escort_records.rb
db/schema.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/services/framework_nomis_mappings/alerts_spec.rb
spec/services/framework_nomis_mappings/importer_spec.rb
spec/services/framework_nomis_mappings/nomis_sync_status_spec.rb
spec/services/framework_nomis_mappings/personal_care_needs_spec.rb
spec/services/framework_nomis_mappings/reasonable_adjustments_spec.rb
swagger/v1/person_escort_record.yaml

[P4-2301](https://dsdmoj.atlassian.net/browse/P4-2301)
To surface any NOMIS resource importing failures on PER creation, add a new column on the PER: 'nomis_sync_status' which lists all the resources imported, and their status, timestamp as well as error message if available. This will allow the FE to render a warning message if any NOMIS resources have not been successfully associated to the responses, and to allow the user to check any missing resources in NOMIS itself instead.
- Changes an api that is used in production, but importing is still not available in production until all features are released

P4-2301 Add NOMIS sync status to Person Escort Record

---

app/serializers/allocation_serializer.rb

P4-
- The old serializer pulls on the now-replaced person#latest_profile method which is going to be removed

Updates allocation_serializer to use v2 moves

---

app/models/framework_response/collection.rb
app/models/framework_response/object.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response/object_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2211
Do not validate comments on responses if there are any NOMIS mappings attached to the response. To avoid users having to fill in "see above" in required give details boxes when NOMIS mappings are available, make this box optional.

P4-2211 Details optional if NOMIS mappings present on response

---

Gemfile
Gemfile.lock

n/a
- We want to be able to selectively enable elastic APM on specific environments 

Add APM gem

---

app/controllers/api/v2/moves_actions.rb
spec/requests/api/moves_controller_create_v2_spec.rb

https://dsdmoj.atlassian.net/browse/IM-53
Default to an empty hash if empty attributes are supplied on move creation, or empty attributes but with relationships, to avoid the API returning a 500 error.

Protect against empty attributes when creating a move

---

app/services/moves/params_validator.rb
spec/services/moves/params_validator_spec.rb

The filters for move should accept a list of comma delimited values for cancellation reason or rejection reason. Change param validator to validate two arrays instead of a string value being included in an array.
This needs to be confirmed and tested/released with FE as we don't allow the use of undefined.

Cancellation reason and rejection reason should accept a list

---

Gemfile.lock

P4-<TODO>
- To fix deprecation warnings

Fix those pesky deprecation warnings

---

.circleci/config.yml

n/a
- There is an issue with pushing commit information to sentry [in certain conditions](https://github.com/getsentry/sentry-cli/issues/792). Removing this call for now as a workaround. 

Remove conflicting sentry command

---

.circleci/config.yml

n/A
- the underlying issue was addressed (deleting the bogus/test release details from sentry)
-
-

Re enable commit tracking

---

app/services/frameworks/question.rb
spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-professional-referral.yml
spec/services/frameworks/question_spec.rb

Read new validation from framework for conditional required validations on followup comments. This is just marked as
required on the question as well, as this validation is already handled in the detail object in framework responses, which checks for NOMIS mappings and does not require a followup comment.

Import new conditional framework validation

---

app/controllers/api/populations_controller.rb
app/serializers/population_serializer.rb
config/routes.rb
spec/factories/populations.rb
spec/requests/api/populations_controller_show_spec.rb
spec/serializers/population_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/get_population_responses.yaml
swagger/v1/population.yaml
swagger/v1/population_id_parameter.yaml
swagger/v1/population_include_parameter.yaml

P4-1427
- This supports front end requirements to display population details for a given prison location and date.
- New api endpoint, so minimal risk

Add GET /populations/:id endpoint to return a population resource

---

app/controllers/api/populations_controller.rb
app/models/population.rb
config/routes.rb
db/migrate/20201016104115_add_unique_index_on_populations.rb
db/schema.rb
spec/models/population_spec.rb
spec/requests/api/populations_controller_create_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/post_populations_responses.yaml

P4-1427
- All the front end things need this
- New endpoint, minimal risk

Add new endpoint POST /populations to support creating new populations

---

spec/swagger/swagger_doc_v1.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/person_escort_record_include_parameter.yaml
swagger/v1/post_person_escort_record.yaml

To create Person escort record, switch documentation to use move instead of profile, however we still surface a profile in
relationships.

Update swagger documentation to use Move instead of Profile

---

app/services/frameworks/question.rb
db/migrate/20201021055517_add_prefill_to_framework_questions.rb
db/schema.rb
spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-details-information.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/medical-professional-referral.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/medication-while-moving.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/property-bag-seal-number.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/property-bag-type.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/regular-medication.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/sensitive-medication.yml
spec/fixtures/files/frameworks/person-escort-record-1/questions/wheelchair-users.yml
spec/services/frameworks/question_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2353
Add a new column `prefill` to framework questions and import this value when pulling in a new framework. This column will determine if a question response should be prefilled or not when creating the Person escort record, with an existing confirmed person escort record. This value can be `nil` to support add multiple questions which allow dependent questions to determine their `prefill` status.

P4-2325 Import `prefill` value from a Framework

---

app/models/person_escort_record.rb
app/serializers/framework_response_serializer.rb
app/serializers/move_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/v2/move_serializer.rb
db/migrate/20201021063632_add_prefilled_to_framework_responses.rb
db/migrate/20201021065138_add_prefill_source_to_person_escort_records.rb
db/schema.rb
spec/factories/person_escort_record.rb
spec/models/person_escort_record_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
swagger/v1/framework_response.yaml
swagger/v1/move_include_parameter.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/person_escort_record_include_parameter.yaml
swagger/v2/move_include_parameter.yaml

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2356
To surface if a response has been already prefilled by an existing person escort record similar response, add a new column `prefilled` to framework responses. This value will be set to true if on creation of a person escort record the value is set from a different response.
To capture the previous person escort record the current record is being prefilled from, add a new relationship to `prefill_source` on `person_escort_records`.
Surface this values in the relative serializers and update documentation.

P4-2356 Surface pre-filling fields and relationships

---

app/models/generic_event/incident.rb
spec/factories/generic_event.rb
spec/support/an_event_about_an_incident.rb

jira link: https://dsdmoj.atlassian.net/browse/P4-2394
Fault classification is needed on every request to create an incident
event.
models via shared examples

[P4-2394] Adds incident fault classification enum to events

---

app/controllers/api/populations_controller.rb
app/controllers/concerns/serializable.rb
app/serializers/location_free_spaces_serializer.rb
spec/serializers/location_free_spaces_serializer_spec.rb

P4-1427
- Whilst working on another story to add metadata for allocations I realised that the existing metadata implementation for `GET /location_free_spaces` was calculating free space data for every location, rather than just the ones currently selected according to the pagination parameters. Cleaned this up by adding callback support in the `paginate` method to expose the paginated collection and options prior to instantiating the serializer. Also simplified the structure for passing parameters as only one parameter is currently needed.
- Doesn't affect api output and is not yet used in production

Ensure that metadata is only provided for paginated subset of locations

---

app/lib/nomis_client/base.rb
spec/lib/nomis_client/base_spec.rb

P4-2128
- It will make it more clear where the error is coming from

Add log warn to OAuth2::Errors

---

app/models/application_record.rb
app/models/framework_response.rb
app/models/person_escort_record.rb
app/services/framework_nomis_mappings/importer.rb
app/services/framework_responses/bulk_updater.rb
spec/models/person_escort_record_spec.rb
spec/services/framework_nomis_mappings/importer_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/IM-60
When deploying migrations, the database schema becomes invalid. If there were transactions midway during such a deploy a
`ActiveRecord::PreparedStatementCacheExpired` error is thrown. To avoid those errors on deploy, wrap all long running transacions with a custom retriable transaction, which retries once if this error is raised, but fails if it fails another time. All transactions to be retried are safe, but are long running so are prone to raise such errors on deploy.
Reference: https://flexport.engineering/avoiding-activerecord-preparedstatementcacheexpired-errors-4499a4f961cf

IM-60 Retry long transactions if they fail

---

app/controllers/api/allocations_controller.rb
app/models/allocation.rb
app/serializers/allocations_serializer.rb
spec/models/allocation_spec.rb
spec/requests/api/allocations_controller_index_spec.rb
spec/serializers/allocations_serializer_spec.rb

P4-2340
- This will allow the front end to use the provided count of total and filled moves per allocation, rather than having to request all of the associated move and profile resources per allocation and derive this calculation. Once the meta data is implemented within the front end the list of supported includes on the `GET /allocations` endpoint can be trimmed back to something more sensible - and ideally remove support for requesting moves entirely as this is a slow operation.
- This does add an extra query to derive the aggregated totals but it's extremely fast so shouldn't affect production performance significantly - during local testing against a snapshot of staging it takes around 6ms for ~400 allocations.
- It's not possible to add optional `meta` tags with the serializer …

Add support for custom move count metadata on `GET /allocations`

---

app/serializers/v2/moves_serializer.rb

Fixes bug preventing relationship between PER and profile from being returned

include person_escort_record relationship in moves serializer

---

app/models/allocation.rb
spec/models/allocation_spec.rb
spec/requests/api/allocations_controller_index_spec.rb

P4-2340
- This allows further simplification of front end code and doesn't impact backend performance so feels like a nicer place to implement this logic.
- Updates `meta` for production allocations api (which is currently ignored in production), the change ties in with ongoing front end work and has been discussed with @solidgoldpig

Add unfilled moves count to allocations meta

---

app/models/framework_question.rb
app/models/framework_response.rb
app/models/framework_response/collection.rb
app/models/person.rb
app/models/person_escort_record.rb
app/services/framework_responses/bulk_updater.rb
spec/models/framework_question_spec.rb
spec/models/framework_response/collection_spec.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/models/person_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/support/feature_flags.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2354
Allow Person escort records to be pre-filled by a previous, confirmed Person escort record if it exists on the same person.
If the feature flag is enabled for pre-fill, the previous person escort record is retrieved and is set on the `prefill_source` of a Person escort record.
To map previous responses to current responses, question keys are used to build a hash map to the response. This is injected into the response builder for creation.
A response is added to the hash map if a question should be pre-filled. Add multiple items questions are slightly different as the parent question does not hold the pre-fill value, but the dependent questions themselves. This allows flexibility in multiple item questions, where not all questions …

P4-2354 Prefill Person Escort Records on Creation

---

app/models/move.rb
spec/factories/profile.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

P4-2339
- Cat-A prisoners (and associated categories H and E) should not be moved by BaSM

P4 2339 validate prisoner category

---

app/models/allocation.rb
spec/models/allocation_spec.rb
swagger/v1/allocation.yaml

P4-2340 P4-2417
- The current front end implementation is showing `Move size` column by iterating over the moves associated with the allocation. When the allocation is not cancelled, this total excludes any cancelled moves (these would have been deleted from the allocation screen) so the allocation "size" should reflect the number of current moves.
- If an allocation is cancelled, all of the moves within the allocation are also cancelled. The front end implementation currently shows the total number of allocation moves regardless of move status for this scenario (i.e. including cancelled moves). This means that the move size could increase if the allocation has most of the moves removed and then the entire allocation is cancelled. However this mirrors the existing behaviour and is largely …

Tweak totals count for allocations metadata

---

app/models/move.rb
app/serializers/journey_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/person_serializer.rb
spec/factories/move.rb
spec/factories/profile.rb
spec/models/move_spec.rb
spec/serializers/journey_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
spec/serializers/v2/person_serializer_spec.rb
swagger/v1/get_journey.yaml
swagger/v1/person_escort_record.yaml
swagger/v1/post_journey.yaml
swagger/v2/move.yaml
swagger/v2/person.yaml

jira link: https://dsdmoj.atlassian.net/browse/P4-1976
We need to support surfacing events for the event timeline in the
frontend.
This commit removes the originally-implemented surfacing of events in
favour of a more efficient [alias](https://jsonapi.org/format/#fetching-includes).
This aliased relationship only applies to the single move _not_ the collection move
serializer once @martyn-w has successfully merged his [PR](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1067).
PersonEscortRecord serializers and their swagger documentation

[P4-1976] Support include alias for event timeline

---

app/controllers/api/person_escort_records_controller.rb
app/models/person_escort_record.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb

We currently support both profile or move for creating a PER. Switch to only use the move to create a PER, as using a profile is deprecated, we will be associating the profile attached to the move instead. The move is required to access the location and other data required for creating the PER, which isn't available by just passing the profile.
~This is blocked until FE fully switches to using move.~ FE has now fully switch to use move to create the PER

Remove profile from creation of person escort record

---

lib/tasks/feeds/event.rake
lib/tasks/feeds/journey.rake
lib/tasks/feeds/move.rake
lib/tasks/feeds/notification.rake
lib/tasks/feeds/person.rake
lib/tasks/feeds/profile.rake

P4-2420
Enables running each report feed for the hub and jpc on a specific date.
This change enables specifying the REPORT_ON_DATE for all or for each of
the feeds
We need this because of a reporting error in which migrations created
updates to every profile in the profiles table in production. We need to
rerun the report feeds that failed to generate for the relevant date.

Add capability of running every/each feed on a specific date

---

app/models/generic_event/incident.rb
spec/support/an_event_about_an_incident.rb

The incident enum was causing a warning when eager loading in the rails
console on production. Declutter the console output to be a good boy
scout
https://blog.bigbinary.com/2019/03/06/rails-6-adds-negative-scopes-on-enum.html

Removes negation prefixing on one of the enum options on incidents

---

app/models/location.rb
app/services/moves/move_type_validator.rb
spec/factories/location.rb
spec/factories/move.rb
spec/fixtures/files/nomis/get_locations_200.json
spec/lib/nomis_client/locations_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/moves/move_type_validator_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/location.yaml

P4-2409
- so we can import hospitals
- TODO: run `rake reference_data:create_locations` on all environments after deployment

P4 2409 import hospitals

---

app/models/category.rb
app/models/location.rb
app/models/profile.rb
db/migrate/20201030095815_create_categories.rb
db/schema.rb
spec/factories/category.rb
spec/models/category_spec.rb
spec/models/location_spec.rb
spec/models/profile_spec.rb

P4-2416 P4-1421
- This will be used to determine prisoner category (via profile) in order to block moving category A prisoners. It will also be used to provide a breakdown by prison (location) category in the PMU dashboards. This PR adds a skeleton implementation of the model for now to unblock work on both streams.
See also: https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1090
- Changes data structures but new relationships are optional so do not effect existing behaviour

Add schema migration and model for categories

---

app/models/application_record.rb
app/models/concerns/updated_at_range.rb
app/services/feeds/event.rb
app/services/feeds/notification.rb
lib/tasks/feeds/event.rake
lib/tasks/feeds/notification.rake
spec/models/generic_event_spec.rb
spec/services/feeds/event_spec.rb
spec/services/feeds/notification_spec.rb

P4-<TODO>
Notification and Event resources can reasonably be expected not to
change once they've been created.
We should control for these resources being in the feed using the
created_at rather than the updated_at since arbitrary updates to these
records might result from rake task migrations, etc, creating a large amount of data in the feed for that day.
This is one way in which we can protect ourselves from large numbers of updates to the feed for these resources.

Use created_at field in range query when retrieving immutable resources

---

app/serializers/generic_event_serializer.rb
app/serializers/v2/move_serializer.rb
spec/serializers/generic_event_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb

jira link: https://dsdmoj.atlassian.net/browse/P4-2423
Support eventable as an include in the move and generic event serializer
The frontend needs this for contextual information in the event
timeline.

[P4-2423] Support eventable include when pulling on move timeline

---

app/models/category.rb
app/services/categories/importer.rb
lib/tasks/data/categories.yml
lib/tasks/reference_data.rake
spec/models/category_spec.rb
spec/services/categories/importer_spec.rb

P4-1421
- This data will be used to categories locations within the PMU dashboard and also to associate prisoners with their correct category so that moves for category A prisoners can be prevented. The reference data is therefore a combination of the known categories within Nomis plus some additional ones used within PMU to group locations.
- Adds new data that is not yet used (future PR's will add this category data to PMU locations dashboard)

Add new service and YAML file to import category reference data

---

lib/tasks/data/categories.yml

P4-1421
- This was originally from returned Nomis data but apparently isn't actually a prison category.

Remove unused category

---

spec/models/category_spec.rb

To avoid warning message when running tests, where inclusion is not possible to fully test on booleans, remove test.
The warning message in full:
```
************************************************************************
Warning from shoulda-matchers:
You are using `validate_inclusion_of` to assert that a boolean column
allows boolean values and disallows non-boolean ones. Be aware that it
is not possible to fully test this, as boolean columns will
automatically convert non-boolean values to boolean ones. Hence, you
should consider removing this test.
************************************************************************
```

Remove inclusion test for boolean column on categories

---

Dockerfile

P4-XXXX
- The API is using the wrong time and that has impact on the data we store and communicate to suppliers.

Ensure the right version of tzdata is used in the docker container

---

app/controllers/api/generic_events_controller.rb
app/models/generic_event.rb
app/serializers/v2/move_serializer.rb
spec/models/generic_event_spec.rb
spec/requests/api/generic_events_controller_create_spec.rb
spec/serializers/v2/move_serializer_spec.rb

P4-2422
The goal of this PR is to achieve dynamic serializers which support
includes and relationships for every event STI class which default to V2
relationships where possible.
In this vain we:
dynamic classes
relationship_attributes and for those that don't define relationship_attributes
This enables `GET /api/events?include=from_location` if we need too. But mainly enables relationships that are currently in the jsonb details field to be surfaced automatically in the relationships section of the json:api document for the given event.
It automatically works on a collection and the classes are memoized only once (any additional object penalty affects only the startup of the application and only once).
- This is for json:api compliance
- This will reduce the …

[P4-2422] Adds support for dynamic anonymous event STI serializers

---

app/controllers/api/populations_controller.rb
app/controllers/api/reference/locations_controller.rb
app/serializers/category_serializer.rb
app/serializers/location_free_spaces_serializer.rb
app/services/locations/finder.rb
spec/requests/api/populations_controller_index_spec.rb
spec/requests/api/reference/categories_controller_index_spec.rb
spec/requests/api/reference/locations_controller_spec.rb
spec/serializers/category_serializer_spec.rb
spec/serializers/location_free_spaces_serializer_spec.rb
spec/services/locations/finder_spec.rb

P4-2297 P4-2416
- The PMU dashboard of free spaces per location should be broken down by category. Reference data for each category and associated mapping of prisons to categories has been completed previously. This PR leverages that data and adds support for `include=category` query string parameter which the front end can now specify.
- Note that the `Locations::Finder` service has been updated to follow the new pattern from `Moves::Finder` of eager fetching only the required relations to match the requested list of includes - this both avoids an N+1 query when categories are included, and needlessly fetching all categories when they are not included. Also added support for sorting by category so that the data can be returned to the front end in a sensible order.
- Extends free spaces …

Add support for including categories within PMU dashboard endpoint

---

app/serializers/generic_event_serializer.rb
spec/factories/generic_event.rb
spec/requests/api/generic_events_controller_create_spec.rb
spec/serializers/generic_event_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb

P4-P4-2422
Surface supplier relationship on the events so that the frontend can use their reference cache to look it up

[P4-2422] Surface supplier

---

app/models/generic_event.rb
app/serializers/generic_event_serializer.rb
app/services/serializer_version_chooser.rb
spec/factories/generic_event.rb
spec/requests/api/generic_events_controller_create_spec.rb
spec/serializers/generic_event_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
spec/services/serializer_version_chooser_spec.rb

jira link: https://dsdmoj.atlassian.net/browse/P4-2422
We need to make sure that eventables that are being serialized as
includes and as relationships for the frontend are picking the correct
serializer version.
In order to achieve this we:
class for polymorphic eventables in the `GenericEventSerializer`
class for STI relations

[P4-2422] Support smarter polymorphic serializer choice for eventable

---

app/models/generic_event.rb
spec/models/generic_event_spec.rb

jira link: https://dsdmoj.atlassian.net/browse/P4-2422
We ended up leaning on our json:api serializer gem to render the
relationships. This enables us to automatically support includes on each
of the anonymous serializers and is significantly cleaner.
This does mean that the method removed in this commit is no longer used.

[P4-2422] Removes presenter method

---

app/serializers/generic_event_serializer.rb
spec/requests/api/generic_events_controller_create_spec.rb
spec/serializers/generic_event_serializer_spec.rb

jira link: https://dsdmoj.atlassian.net/browse/P4-2422
Now we're compliant and have relationships in the correct json:api
location of the response when surfacing events we need to remove these
relationships from the details attribute dynamically for all events
I've done this separately to reduce review complexity.
Leaving this would be confusing for the frontend

[P4-2422]  Remove relationships from details in GenericEventSerializer

---

app/models/person_escort_record.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb

Pre-filling has been live for a while now without incident. Remove feature flag from codebase to make this feature permanent.

Remove prefill feature flag

---

app/state_machines/person_escort_record_state_machine.rb
db/migrate/20201106104806_add_completed_by_to_person_escort_records.rb
db/schema.rb
spec/factories/move.rb
spec/factories/person_escort_record.rb
spec/models/person_escort_record_spec.rb
spec/state_machines/person_escort_record_state_machine_spec.rb

To capture stats on when users are *first* completing a PER, add a new timestamp to capture the first date/time a user completes the PER. If the PER moves back to in progress then completed again we don't overwrite the timestamp with the new value, but maintain the old one. This is only internal for now so won't be surfaced in serializers.

Add `completed_at` timestamp on PER when status transitions to complete

---

app/controllers/api/allocations_controller.rb
app/serializers/allocations_serializer.rb
app/services/allocations/finder.rb
app/services/locations/finder.rb
spec/requests/api/allocations_controller_index_spec.rb
spec/services/allocations/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/allocations_include_parameter.yaml

P4-2443
- Previous work to introduce metadata for various moves count for this endpoint means that the front end code no longer needs to retrieve moves when fetching a list of allocations. The `Allocations::Finder` service was still preemptively including a worst case list of database level includes to avoid N+1 queries but most of those includes are no longer necessary now. Instead the database level includes are derived from the JSONAPI requested includes, with only `from_location` and `to_location` relationships now supported. Also tweaked the `AllocationsSerializer` to ensure that nested resources are not queried. The overall effect is a dramatic improvement in performance for this endpoint.
- Affects `GET /allocations` endpoint, but the previously supported includes are no longer …

Remove support for included moves with GET /allocations

---

Gemfile
Gemfile.lock
app/models/person.rb
lib/tasks/data_maintenance.rake
spec/models/person_spec.rb

P4-2456
- We (or rather suppliers) don't want empty strings for Person reference values to be stored as empty string, but should instead be stored as `null. Added `auto_strip_attributes` gem as the easiest way to achieve this as it's likely we will want to add this to more models over time. The gem is very minimal (only 100 LOC) and well maintained so I think is justified to use. Also added a rake task to clean up historic values to be run in each environment after the fix has been deployed.
https://github.com/holli/auto_strip_attributes
- Rake task changes production data but only converts empty strings to null so is safe to run, and has been tested locally.

Ensure that empty Person reference values are saved as null

---

app/controllers/api_controller.rb
spec/requests/api/people_controller_show_v2_spec.rb
spec/support/responds_with_error_502.rb

To fix https://sentry.io/organizations/ministryofjustice/issues/2024795868/?project=2014776&referrer=slack
Amend method name and add test for NOMIS OAuth2 errors when NOMIS responds with a 500

Fix method name for rendering NOMIS error

---

app/models/framework_question.rb
app/models/framework_response.rb
app/models/framework_response/collection.rb
app/models/framework_response/multiple_item_object.rb
app/models/framework_response/multiple_items_collection.rb
app/models/person_escort_record.rb
app/serializers/framework_response_serializer.rb
app/services/framework_nomis_mappings/importer.rb
app/services/framework_responses/bulk_updater.rb
db/migrate/20201109110657_add_assessmentable_to_framework_responses.rb
db/schema.rb
lib/tasks/refresh_framework_responses.rake
spec/factories/framework_response.rb
spec/factories/person_escort_record.rb
spec/models/framework_question_spec.rb
spec/models/framework_response/multiple_item_object_spec.rb
spec/models/framework_response/multiple_items_collection_spec.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/serializers/framework_response_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/services/framework_nomis_mappings/importer_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
swagger/v1/framework_response.yaml

[P4-2447](https://dsdmoj.atlassian.net/browse/P4-2447)
To add the Youth Risk Assessment, we need to be able to support multiple types of assessments on framework responses. Adding a new polymorphic association helps achieve this goal. Since this is a breaking change, we will first roll out support for this new relationship, whilst maintaining the old one. After we backfill all the data on production using the rake task included, and the frontend client starts utilising the new relationship, we can folllowup with a PR to remove the old relationship.
- Hopefully this shouldn't affect existing data, but rather adds a new relationship whilst keeping the old one

P4-2447 Add `assessmentable` association to responses

---

app/models/person_escort_record.rb

Revert to using old association, as if we use assessmentable now, between the time we run the rake task users will have a glitch where person escort record will not return any responses. Only switch to assessmentable when backfill is complete.

Keep old implementation to rely on person escort record relationship

---

app/services/framework_responses/bulk_updater.rb

To avoid any glitches in the FE before backfilling, use old column on framework bulk updates as well.

Use PER instead of assessmentable for updating framework responses

---

app/models/person_escort_record.rb
app/services/framework_responses/bulk_updater.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2448
Stop using the `person_escort_record` relationship on responses, although we still populate the `person_escort_record` value on creation. This is due to our deployment strategy, where we need to support both old and new pods, and the old pods will still be reading from the old column, so to avoid any glitched this change needs to be staggered. After this is fully deployed we can finally get rid of the PER column safely.

P4-2248 Stop using `person_escort_record` relationship on framework responses

---

app/services/locations/finder.rb
spec/services/locations/finder_spec.rb

P4-<TODO>
- This was previously loading the suppliers relationship for all requests, irrespective of whether suppliers filters were requested. If suppliers are not requested in the API includes and the supplier filter isn't used then there's no need to perform an additional join on suppliers.

Improve eager loading of Locations::Finder suppliers

---

app/models/move.rb

P4-<TODO>
- I noticed a few deprecation warnings about this - since we have `cancelled` already defined as a valid status enum value, then this scope is automatically generated - and in fact the code is ignored and replaced by the generated version so it's been doing nothing all this time. There is also some existing indirect coverage of this in both move and allocation model specs so it's very safe to remove.

Remove redundant move scope

---

app/serializers/person_escort_record_serializer.rb
app/serializers/prefill_source_serializer.rb
spec/serializers/prefill_source_serializer_spec.rb

P4-2480
- The front end currently only requires the `confirmed_at` attribute for the previously filled person escort record. However the prefill source is currently using the same `PersonEscortRecordSerializer` which requires lots of additional queries to fetch associated framework questions and responses, none of which are then consumed by the front end client.
- Since prefilling was introduced, observed performance in production has dipped significantly as fetching a move is now effectively returning two complete PER resources. The new lightweight serializer for the prefilled PER is effectively a subset of the PER serializer, but contains only those attributes which can be served directly from the prefill PER record and without any additional queries. This should support the existing …

Add custom serializer for prefill source with fewer fields

---

app/models/framework_question.rb
app/models/framework_response.rb
app/models/person_escort_record.rb
db/migrate/20201116093301_change_person_escort_record_to_optional_on_framework_responses.rb
db/schema.rb
spec/factories/framework_response.rb
spec/models/framework_question_spec.rb
spec/models/framework_response_spec.rb
spec/models/person_escort_record_spec.rb
spec/serializers/framework_response_serializer_spec.rb

* Make the `person_escort_record_id` column optional, but keep for now to support staggered release
* Stop writing to the `person_escort_record_id` column when populating responses

P4-2248 Stop writing to person_escort_record_id in responses

---

app/controllers/api/v2/moves_actions.rb
app/models/generic_event.rb
app/models/generic_event/move_proposed.rb
app/models/generic_event/move_requested.rb
spec/factories/generic_event.rb
spec/models/generic_event/move_proposed_spec.rb
spec/models/generic_event/move_requested_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

P4-2424
These events need to be generated to indicate the starting point of the
move in the timeline and supplement the events that Martyn added for
Journeys which are now deprecated/not used anywhere.
- This is needed to indicate the initial starting point in the events timeline

[P4-2424] Add MoveRequested and MoveProposed events for timeline

---

app/models/framework_response.rb
app/serializers/framework_response_serializer.rb
db/migrate/20201116095539_remove_person_escort_record_from_framework_responses.rb
db/schema.rb
spec/models/framework_response_spec.rb
spec/serializers/framework_response_serializer_spec.rb
swagger/v1/framework_response.yaml
swagger/v1/framework_response_include_parameter.yaml

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2448
Since we no longer need to populate/use the `person_escort_record_id` on framework responses, remove this column.

P4-2248 Remove person_escort_record_id from framework responses

---

app/controllers/api/v2/moves_actions.rb
spec/requests/api/moves_controller_create_v2_spec.rb

P4-2424
- The UI needs to know the original creator of the move rather than the inferred supplier picked by the `SupplierChooser`

[P4-2424] Fix supplier on new move events

---

app/controllers/api/journeys_controller.rb
lib/tasks/events.rake
lib/tasks/fake_data/journeys.rb
spec/lib/tasks/fake_data/journeys_spec.rb
spec/requests/api/journeys_controller_create_spec.rb
spec/requests/api/journeys_controller_update_spec.rb

P4-2507
This corrects a UI issue for the frontend where the presented data on the timeline indicates the wrong information about who created the move.
It also corrects cruft that should have been removed previously.

[P4-2507] Adjust supplier on move initial status events

---

app/jobs/prepare_move_notifications_job.rb
app/jobs/prepare_person_escort_record_notifications_job.rb
app/services/notifier.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/jobs/prepare_person_escort_record_notifications_job_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/services/notifier_spec.rb

P4-2485
- Previously PER completions were triggering move update notifications for all moves related to the per profile; this is a legacy approach predating the new direct relationship between a PER and the associated move. We also want to use a dedicated event type of `confirm_person_escort_record` for PER completion notifications.
- Suppliers are not yet making use of PER webhooks, so this PR aims to improve the implementation prior to it being integrated with suppliers and then being harder to change.

Use custom event type for PER completion notifications

---

app/models/person.rb
spec/models/person_spec.rb

P4-2430
Some PII information is needed by the journey pricing spreadsheet. This
PR adds that information and extends these fields for consumption by
the JPC from the next report run.
We already are returning all identifiers (prison_number, latest_nomis_booking_id, etc).

[P4-2430] Surface PII in person feed

---

app/controllers/api/allocations_controller.rb
app/controllers/api/populations_controller.rb
app/controllers/concerns/serializable.rb
app/lib/JSONAPI/conditional_relationships.rb
app/serializers/allocations_serializer.rb
app/serializers/framework_flags_serializer.rb
app/serializers/location_free_spaces_serializer.rb
app/serializers/move_serializer.rb
app/serializers/person_escort_records_serializer.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/moves_serializer.rb
app/serializers/v2/person_serializer.rb
app/serializers/v2/profiles_serializer.rb
spec/requests/api/moves_controller_index_v2_spec.rb
spec/serializers/allocations_serializer_spec.rb
spec/serializers/framework_flags_serializer_spec.rb
spec/serializers/location_free_spaces_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
spec/serializers/v2/profiles_serializer_spec.rb
swagger/v2/moves_include_parameter.yaml

P4-2467
- We have been trying a number of techniques to improve API performance when serialising a graph of resources. The aim is to support a reasonable set of includes for each endpoint and to ensure that the associated resources are retrieved efficiently without superfluous or N+1 queries. There are known performance issues when including `profile.person_escort_record.flags` as part of a `GET /moves` request that need to be addressed.
- Previous approaches have used a hard coded list of relationships to render in the `MovesSerializer` - this works to a point if all of those relationships are passed in the `include` query string. If those are omitted then for a `has_one` or `has_many` relationship we see N+1 SQL queries as the id's for those resources cannot be retrieved directly from …

Remove superfluous relationships and attributes from GET /moves endpoint

---

app/models/framework_response.rb
app/models/profile.rb
app/models/versioned_model.rb
config/initializers/paper_trail.rb
spec/models/move_spec.rb
spec/models/person_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

P4-2516
- There's no need to version FrameworkResponses - we don't care about those while the PER is in draft status and once completed the PER becomes read only so those rows are essentially immutable.
For other versioned resources there's no need to record a new version if only a timestamp is modified; this can happen when the `updated_at` attribute is updated in isolation, or if the model is touched.
This change now means that updating resources won't trigger a cascade of associated versions via the "touch model". In production this should speed up endpoints that modify data as we won't need as many writes to the 7 million row versions table.
- Minimal risk, but should improve performance

Reduce spam logging of Papertrail versions

---

app/controllers/api/v1/moves_actions.rb
app/serializers/move_serializer.rb
app/serializers/v2/moves_serializer.rb
spec/serializers/move_serializer_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
swagger/v1/move_include_parameter.yaml
swagger/v2/moves_include_parameter.yaml

P4-2476
- Suppliers have no need to see allocation details as part of a move so removing support completely under v1 API should not impact them. The v2 API still retains support for including an allocation when retrieving one move, but not multiple moves.
Including allocation details with a list of moves is extremely slow so has been replaced with custom metadata for moves counts under v2 GET /moves.
- We don't want API clients to inadvertently make use of this include so it's good to remove support and cleanup associated code.
- Should be no risk if suppliers and front end are not using this include. Flagging as a breaking change however to remind us to test this assumption!

Remove support for including allocation on v1/v2 GET /moves and v1 GET /move

---

app/models/move.rb
spec/models/move_spec.rb

P4-2415
- to ensure duplicate moves are correctly identified and reported to the frontend
- reduce the number of errors raised which are actually about duplicate moves

P4-2415 fix duplicate move validation

---

app/services/notifier.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/requests/api/youth_risk_assessments_controller_update_spec.rb
spec/services/notifier_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2451
Switch both youth risk assessment and PER to use generic assessment job notifier

P4-2521 Switch to using generic assessment job on assessment confirm action

---

app/models/youth_risk_assessment.rb
spec/factories/framework_assessment.rb
spec/factories/move.rb
spec/models/person_escort_record_spec.rb
spec/models/youth_risk_assessment_spec.rb
spec/requests/api/youth_risk_assessments_controller_create_spec.rb
spec/requests/api/youth_risk_assessments_controller_update_spec.rb
spec/support/a_framework_assessment.rb

Add validation on the youth risk assessment to only being created if a move `from_location` is either a secure training centre (STC) or a secure children's home (SCH).
This requires some changes to the shared tests, where now we allow passing in a `from_location` to the respective assessment specs.
This also means we will never import NOMIS mappings on the youth risk assessment, as for NOMIS mappings to be imported, the from location should be a prison. I have moved out the specific tests to the PER now instead.

Validate Youth Risk Assessment move `from_location` on creation

---

app/models/generic_event.rb
app/models/generic_event/incident.rb
app/models/generic_event/per_medical_aid.rb
app/models/move.rb
app/models/person_escort_record.rb
app/serializers/generic_event_serializer.rb
app/serializers/important_events_serializer.rb
app/serializers/person_escort_records_serializer.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/moves_serializer.rb
app/services/include_param_handler.rb
db/migrate/20201130142628_add_classification_to_generic_events.rb
db/schema.rb
lib/tasks/data_maintenance.rake
spec/factories/generic_event.rb
spec/models/generic_event/incident_spec.rb
spec/models/generic_event/per_medical_aid_spec.rb
spec/models/generic_event_spec.rb
spec/models/move_spec.rb
spec/models/person_escort_record_spec.rb
spec/serializers/generic_event_serializer_spec.rb
spec/serializers/important_events_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
spec/services/include_param_handler_spec.rb
swagger/v2/move.yaml
swagger/v2/move_include_parameter.yaml
swagger/v2/moves_include_parameter.yaml

P4-2425
- Medical events occur against a PER, and incident events (aka red flag events) occur against a move. These need to be exposed efficiently in the API to allow relevant flags to be shown in the front end when listing moves. This means minimising SQL queries and the rows retrieved to keep the endpoint performant.
- Extends includes for existing API, but is backwards compatible

Add support for medical and critical events

---

app/controllers/api/v2/moves_actions.rb

The assessments eager loading is a can of worms that needs to be addressed properly. I will add a ticket in the backlog but for now this will stave off many many bad queries on a move.
I paired with @smoothcontract around removing this include entirely and fixing the serializers, but it requires quite a bit of work so we will go with this solution for now.

Temporary solution to eager load youth risk assessment in a move

---

config/initializers/inflections.rb
spec/requests/api/move_events_controller_approve_spec.rb

P4-2563
- so the front end can call the approve endpoint easily

Fix pluralisation of approves move endpoint

---

app/serializers/person_escort_records_serializer.rb
spec/serializers/person_escort_records_serializer_spec.rb

Add the status to the PER seriazlier on the moves endpoint, as this is needed to show when the PER is completed to show flags under a person's name.

Surface the status on the PER serializer

---

lib/tasks/fake_data.rake
lib/tasks/fake_data/incident_events.rb
lib/tasks/fake_data/medical_events.rb

P4-2425
- Suppliers will eventually create these events via the API, but in the meantime we need some sample data for testing. As this will run on production mode environments the factory fixtures unfortunately can't be used as none of the required test group gems are bundled.

Add fake data rake tasks to create move incidents and PER medical events

---

app/models/framework_response.rb

We would like to track who answers/edits responses which helps us calculate the people responsible for completing sections in the PER for auditing purposes. Add back the version model to responses for now to have this information available and tracked, so we can parse it later.

Add framework responses back to the version model

---

app/controllers/api/profiles_controller.rb
app/serializers/profile_serializer.rb
app/serializers/v2/profile_serializer.rb
db/migrate/20201210135224_add_requires_youth_risk_assessment_to_profiles.rb
db/schema.rb
spec/requests/api/profiles_controller_update_spec.rb
spec/serializers/profile_serializer_spec.rb
spec/serializers/v2/profile_serializer_spec.rb
swagger/v1/profile.yaml

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2378
If a person is moving from a YOI, the client is required to ask the user if the person needs a youth risk assessment if their age is between 18 and 19. The answer can be stored on the profile as a new attribute which is a boolean representing if the user selects true or false. The attribute remains nil if the question is not answered.
The logic around when to ask this question will be with the client, which will be looking at the move from location, and at the age of the person, being between 18 - 19.

P4-2378 Add `requires_youth_risk_assessment` attribute to profiles

---

.rubocop.yml
spec/factories/journeys.rb
spec/factories/move.rb
spec/lib/cloud_data_feed_spec.rb
spec/models/activity_spec.rb
spec/models/move_spec.rb
spec/models/nomis_court_hearing_spec.rb
spec/models/notification_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/serializers/assessment_question_serializer_spec.rb
spec/serializers/ethnicity_serializer_spec.rb
spec/serializers/gender_serializer_spec.rb
spec/serializers/identifier_type_serializer_spec.rb
spec/serializers/location_serializer_spec.rb
spec/serializers/prison_transfer_reason_serializer_spec.rb
spec/services/court_hearings/create_in_nomis_spec.rb

Allow tests to utilise timezones, as running tests from a different timezone is causing issues if these aren't set.

Make sure tests use timezones in time specific tests

---

app/models/framework_question.rb
spec/support/a_framework_assessment.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2558
If a question type changes across frameworks, but they share a question key name, do not pre-fill the response value from the previous question. Since the value type validation occurs at setting the value attribute, rescue from this error and return an unpre-filled response instead.
An example of changing the question type would be removing the ability of setting the details section on radio buttons, meaning this changes responses from an object to a string question response.

P4-2558 Guard against question type change on pre-filling assessments

---

app/controllers/api/reference/locations_controller.rb
app/serializers/location_serializer.rb
app/services/locations/finder.rb
app/services/locations/updater.rb
db/migrate/20201210180043_add_yoi_to_locations.rb
db/schema.rb
lib/tasks/reference_data.rake
spec/requests/api/reference/locations_controller_spec.rb
spec/serializers/location_serializer_spec.rb
spec/services/locations/finder_spec.rb
spec/services/locations/updater_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/location.yaml

P4-2374
- Some institutions have YOI as well as adult populations. Within Nomis these are generally held with the prison location type, which means we can't perform YOI specific logic. In an effort to avoid these data issues from Nomis, the new attribute of YOI can be applied independently of the location type and is used to identify the 5 current YOI locations. The rake task and update service sets the correct YOI value for these known locations. `Locations::Finder service` has been extended to support filtering with/without this attribute to allow the front end to get a list of relevant YOI locations from the reference data end point. Finally the `LocationSerializer` now includes the new attribute.
- Introduces a new attribute in the serialized locations, so has a knock on effect to …

Add new `yoi` attribute to locations

---

app/models/population.rb
spec/models/population_spec.rb
spec/requests/api/populations_controller_index_spec.rb

P4-2566
- This now includes a count of transfers (moves) in and out as distinct keys in the metadata, so this necessitated a slight change in the behaviour. Previously if a population model was not present for a given date and location then the corresponding hash value was `nil`. With this change the hash is always generated so that `transfers_in` and `transfers_out` can be populated, but `id` and `free_spaces` keys will be `nil`.
- This allows the PMU dashboard to be updated in the front end so that transfer counts can be shown even if there is not yet a corresponding population record. As the behaviour of the generated metadata is amended this is a breaking change so will need to be released in coordination with the front end, however this is not yet a production feature.
- Changes an …

Update metadata for location free spaces endpoint

---

app/serializers/v2/move_serializer.rb
app/serializers/v2/moves_serializer.rb
app/serializers/v2/profile_serializer.rb
app/serializers/v2/profiles_serializer.rb
spec/serializers/v2/profile_serializer_spec.rb
spec/serializers/v2/profiles_serializer_spec.rb
swagger/v1/profile.yaml
swagger/v1/profile_include_parameter.yaml
swagger/v2/category_reference.yaml
swagger/v2/move_include_parameter.yaml
swagger/v2/moves_include_parameter.yaml

P4-<2461>
- in order to present a prisoner's category when viewing a move's details
- minimal
cc @solidgoldpig

P4-2461 adding category to profile serializer

---

app/controllers/api/v2/moves_actions.rb
app/controllers/api_controller.rb
app/models/move.rb
app/serializers/v2/moves_serializer.rb
app/services/include_param_handler.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_index_v2_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
spec/services/include_param_handler_spec.rb
spec/swagger/swagger_doc_v2.yaml

[P4-2537](https://dsdmoj.atlassian.net/browse/P4-2537)
- Add ability to pass in `meta` query param
- Add vehicle registration field in meta section in the move resource for moves index endpoint
To surface vehicle registrations for moves, to be used on the FE dashboards, add a meta section to the moves resources only on the moves index endpoint. The vehicle registration is optional and can be included in the new `meta` query string param. If no meta query param is included, we still get a meta section, but it will be empty, as there is no option to make the section itself optional.

P4-2537 Add metadata section to moves resource

---

app/controllers/api/v2/moves_actions.rb
app/models/generic_event.rb
app/models/generic_event/move_notify_premises_of_arrival_in_30_mins.rb
app/models/generic_event/move_notify_premises_of_eta.rb
app/models/generic_event/move_notify_premises_of_expected_collection_time.rb
app/models/generic_event/notification.rb
app/models/move.rb
app/serializers/v2/moves_serializer.rb
app/services/include_param_handler.rb
lib/tasks/data_maintenance.rake
lib/tasks/fake_data.rake
lib/tasks/fake_data/notification_events.rb
spec/factories/generic_event.rb
spec/models/generic_event/move_notify_premises_of_arrival_in30_mins_spec.rb
spec/models/generic_event/move_notify_premises_of_eta_spec.rb
spec/models/generic_event/move_notify_premises_of_expected_collection_time_spec.rb
spec/models/generic_event/notification_spec.rb
spec/models/generic_event_spec.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_index_v2_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
spec/support/an_event_about_a_notification.rb
spec/swagger/swagger_doc_v2.yaml

[P4-2538](https://dsdmoj.atlassian.net/browse/P4-2538)
[P4-2539](https://dsdmoj.atlassian.net/browse/P4-2539)
- Add new type of event classification: notifications
-  Add task to backfill all notification events with correct classification type
- Surface ETA and collection times in meta data for moves on index moves endpoint
- Add task to generate fake data for notification events
To allow the FE to build dashboards and group by vehicles expected collection time for outgoing moves, and ETA for incoming moves, surface those values from the relevant events that are attached to those moves in the metadata. The event corresponding to expected collection time is `MoveNotifyPremisesOfExpectedCollectionTime`, which contain an `expected_at` timestamp. The event corresponding to ETA is …

P4-2538 Surface ETA and collection time in moves meta data

---

app/models/concerns/framework_assessmentable.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/requests/api/youth_risk_assessments_controller_update_spec.rb
spec/support/a_framework_assessment.rb

To include a code in a PER confirmed error, raise a RecordInvalid error instead,
and set the code to 'invalid_status', to allow clients to look at the code and not the description of the error. This type of error is handled differently in the API controller and adds a code and pointer.
Old error:
```
{
"errors": [
{
"title": "Invalid status",
"detail": "Validation failed: Status can't update to 'confirmed' from 'confirmed'"
}
]
}
```
New error format:
```
{
"errors": [
{
"title": "Unprocessable entity",
"detail": "Status can't update to 'confirmed' from 'confirmed'",
"source": {
"pointer": "/data/attributes/status"
},
"code": "invalid_status"
}
]
}
```

Change the type of a PER confirmed error to return a code in API response

---

app/controllers/api/person_escort_records_controller.rb
app/models/generic_event.rb
app/models/generic_event/per_confirmation.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_confirmation_spec.rb
spec/requests/api/generic_events_controller_create_person_escort_record_events_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb

[P4-2058](https://dsdmoj.atlassian.net/browse/P4-2058)
To surface who and when a PER is confirmed on a move's timeline, add a PER confirmation event which captures who confirms a PER and when as a callback on a successful confirmation of the PER, through the PATCH endpoint.
This event will appear when including a move's timeline events.
- [] Updated API docs if necessary: I'll update https://github.com/ministryofjustice/hmpps-book-secure-move-api/wiki/Event-Documentation once this is merged

P4-2058 Add PER confirmation event

---

lib/tasks/data/categories.yml

P4-2583
- Stafford (SFI), Littlehey (LTI) and Bure (BRI) move from "Category C" to "Category C VPU". Manchester (MRI) and Woodhill (WHI) move from "Category B" to a new "Category B Training" category. This presumably better fits with how PMU manage the prison estate.

Update location categories

---

app/controllers/api/populations_controller.rb
app/models/population.rb
config/routes.rb
spec/models/population_spec.rb
spec/requests/api/populations_controller_new_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/get_new_population_responses.yaml
swagger/v1/population.yaml

P4-2576
- This doesn't create a new record, but returns default values to the front end with selected information copied from the most recent population details for the same location. This then allows the front end to provide a form with pre-populated information for the user to amend as needed and then call the existing `POST /populations` endpoint to actually create the new population record. This saves users time and avoids them having to manually look up and copy/paste previous figures.
- New endpoint so minimal risk

Add endpoint to provide pre-populated defaults for new population record

---

app/models/framework_question.rb
db/migrate/20210107140348_add_value_type_to_framework_responses.rb
db/schema.rb
lib/tasks/refresh_framework_responses.rake
spec/models/framework_question_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2589
We currently calculate the value type on responses on the fly using the framework questions in framework response serializers. This was previously ok as we were hard coding an eager load list when rendering the framework response serializer. Since we are moving away from this, and only eager loading including resources, reaching into questions for each response will cause n+1 queries. Instead persist the value_type on response creation. 
This is part of a phased deploy, this PR introduces the column and starts populating it going forward. Also add a rake task which backfills all value types in batches, the next pr will start using this value.

P4-2589 Add new column value_type to responses

---

app/models/concerns/framework_assessmentable.rb
app/models/framework_question.rb
spec/models/framework_question_spec.rb
spec/support/a_framework_assessment.rb

We currently slice response and dependent response values before setting them in bulk when creating an assessment. Make sure `value_type` is in the selected fields to be set on responses as well as dependent responses

Set value type when creating framework responses

---

app/serializers/framework_response_serializer.rb
spec/factories/framework_response.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2589
Switch to using persisted value type on responses, to avoid having to reach into framework questions. This is the second part of a phased deploy, after all value types have been backfilled on all ENVs

P4-2589 Use value_type column value in response serializer

---

config/environments/production.rb

As seen in: https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0
We need to change the `config.i18n.fallbacks` to `[I18n.default_locale]` instead of true to support newest release of i18n.

Set default callbacks to support new i18n gem version

---

db/migrate/20210113092719_add_unique_index_on_youth_risk_assessment.rb
db/schema.rb

Alls well that ends well
To prevent two youth risk assessments being created for the same profile add db level unique index.

Add a unique index to the profile id on youth risk assessments

---

app/controllers/api/framework_assessments_controller.rb
app/controllers/api/v2/moves_actions.rb
app/models/concerns/framework_assessmentable.rb
app/models/person_escort_record.rb
app/models/youth_risk_assessment.rb
app/serializers/framework_assessment_serializer.rb
app/serializers/framework_flag_serializer.rb
app/serializers/framework_question_serializer.rb
app/serializers/framework_response_serializer.rb
app/services/include_param_handler.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/requests/api/youth_risk_assessments_controller_create_spec.rb
spec/requests/api/youth_risk_assessments_controller_show_spec.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/framework_question_serializer_spec.rb
spec/serializers/framework_response_serializer_spec.rb

[P4-2564]( https://dsdmoj.atlassian.net/browse/P4-2564)
- Change eager loading includes on move endpoint
- Add eager loading includes on assessments
- Improve assessment serializers to avoid always eager loading resources
- Improve assessment creation performance
To improve the performance of assessments, and to avoid always setting up queries for the worst case scenario, only eager load required and included resources. This means we can cleanup the serializers in question.
Whilst testing there were some n+1 queries occurring on latest assessment, so now that has been cleaned up to look at the pre-fill source.
I avoided fixing up more serializers to avoid too much change in one PR. There is further work to be done on the meta section which is also a big offender, which I will be tackling …

P4-2564 Improve serializer performance for assessments

---

app/models/generic_event.rb
app/models/generic_event/journey_admit_through_outer_gate.rb
app/models/generic_event/journey_admit_to_reception.rb
app/models/generic_event/journey_arrive_at_outer_gate.rb
app/models/generic_event/journey_exit_through_outer_gate.rb
app/models/generic_event/journey_handover_to_supplier.rb
app/models/generic_event/journey_ready_to_exit.rb
spec/factories/generic_event.rb
spec/models/generic_event/journey_admit_through_outer_gate_spec.rb
spec/models/generic_event/journey_admit_to_reception_spec.rb
spec/models/generic_event/journey_arrive_at_outer_gate_spec.rb
spec/models/generic_event/journey_exit_through_outer_gate_spec.rb
spec/models/generic_event/journey_handover_to_supplier_spec.rb
spec/models/generic_event/journey_ready_to_exit_spec.rb
spec/requests/api/generic_events_controller_create_journey_events_spec.rb
spec/swagger/swagger_doc_v2.yaml
swagger/v2/event.yaml

P4-2616
- so that suppliers can log location with events relating to pick-up / drop-off (otherwise we won't know what they relate to)
- small; not used in production yet

P4 2616 extra journey events

---

app/controllers/api/framework_responses_controller.rb
app/models/concerns/framework_assessmentable.rb
app/models/framework_question.rb
app/models/framework_response.rb
app/services/framework_responses/bulk_updater.rb
db/migrate/20210118124654_add_section_and_responded_by_to_framework_responses.rb
db/schema.rb
lib/tasks/refresh_framework_responses.rake
spec/factories/framework_response.rb
spec/models/framework_question_spec.rb
spec/models/framework_response_spec.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/support/a_framework_assessment.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2588
This is part of multiple PRs to help with performance and capturing of user data.
To help simplify the assessment section completion calculation, add a new field `section` to framework responses, which although causes denormalisation in the data, will help with this calculation and will avoid reaching into framework questions.
The section will be added once on response creation and does not need to be edited after. Also add a backfill task to fill in all older section values on legacy responses. This value does not need to be surfaced through the serializer as its only for internal calculation.
I've also added the `responded_by` and `responded_at` values to responses, to start recording who responds to questions and when. This will …

P4-2588 Add `section`, `responded_by`, and `responded_at` to framework responses

---

app/models/person.rb
spec/factories/person.rb
spec/models/person_spec.rb

P4-2442
- A move recently failed when a person's date of birth was given as `0919-03-01`.

Add validation to Person#date_of_birth

---

app/models/concerns/framework_assessmentable.rb
app/models/framework_response.rb
app/serializers/framework_assessment_serializer.rb
app/services/framework_responses/bulk_updater.rb
db/migrate/20210118152930_add_section_progress_to_assessments.rb
db/schema.rb
lib/tasks/refresh_assessments.rake
spec/models/framework_response_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/support/a_framework_assessment.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2588
This is the second PR to improve performance. This comes after https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1277 has moved section to framework responses, and all sections have been backfilled.
Add a new column `section_progress` to both assessment tables, to avoid having to do this calculation each time we invoke the PER serialiser. 
First we add the column, and on creation calculate the section progress, then on recalculate on each PATCH either bulk or single. I have tested all PER endpoints and this does not make the calls any worse, as we are making use of already loaded responses on creation, and on PATCH updates we already call the relevant records to calculate the status, so it won't make things worse. …

P4-2588 Add `section_progress` to assessments

---

app/services/locations/updater.rb

P4-2622
- Looks like this one was missed previously as annoyingly, this location is only present in production environments as it comes from Nomis live, and isn't in Nomis dev.

Enable youth risk assessments for Feltham A location

---

app/models/framework_response.rb
app/serializers/framework_assessment_serializer.rb
app/serializers/person_escort_records_serializer.rb
db/migrate/20210120101859_add_null_fields_to_framework_responses.rb
db/schema.rb
spec/models/framework_response_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/requests/api/youth_risk_assessments_controller_show_spec.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb

jira-ticket: https://dsdmoj.atlassian.net/browse/P4-2588
This is the third PR for improving performance.
After all section progress columns are backfilled, use the section progress column instead in assessment serializer and multiple moves PER serializer, to allow section progress to be viewed on FE dashboards. Since responses are created after assessments, explicitly call section calculation in GET specs.
Also add null restrictions and validations to framework response database columns now we ensure they are always populated.

P4-2588 Use section progress in serializer

---

lib/tasks/refresh_framework_responses.rake

Since we longer have the column `person_escort_record_id`, this rake task won't work anymore.

Remove deprecated rake task

---

app/services/allocations/finder.rb
app/services/locations/finder.rb
app/services/moves/finder.rb
app/services/v2/people/finder.rb
spec/services/moves/finder_spec.rb
spec/services/people/finder_spec.rb

If a filter is present but empty in a query parameter, it is interpreted as an empty string. When splitting an empty string the result is an empty array. This means that we query an empty array instead of nil for filters which does not return the intended results. Instead we should return nil when the string is empty to query any filter and expect values that are nil to be returned.
```
[3] pry(main)> ''.split(',')
=> []
[4] pry(main)> Move.where(to_location_id: nil).count
(8.9ms)  SELECT COUNT(*) FROM "moves" WHERE "moves"."to_location_id" IS NULL
=> 3320
[5] pry(main)> Move.where(to_location_id: []).count
(0.6ms)  SELECT COUNT(*) FROM "moves" WHERE 1=0
=> 0
[6] pry(main)> Move.where(cancellation_reason: []).count
(0.6ms)  SELECT COUNT(*) FROM "moves" WHERE 1=0
=> 0
[7] pry(main)> …
```

Fix filters bug

---

app/services/diagnostics/move_inspector.rb

P4-2628
- so suppliers can see PER events they are raising for testing and development
- minimal

Add PER and PER Events to Diagnostics

---

app/serializers/framework_assessment_serializer.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/person_escort_records_serializer.rb
app/state_machines/framework_assessment_state_machine.rb
db/migrate/20210122172150_add_amended_at_to_person_escort_records.rb
db/schema.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/requests/api/youth_risk_assessments_controller_show_spec.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
spec/state_machines/framework_assessment_state_machine_spec.rb
swagger/v1/person_escort_record.yaml
swagger/v1/youth_risk_assessment.yaml

P4-2607
- This attribute is initially `nil` when the PER is first completed. If the PER is updated and completed again the current time is stored. This allows the front end to distinguish between initial completion and subsequent amendments.
- For now `amended_at` is not implemented for youth risk assessments, so the shared state machine checks whether the relevant model supports `amended_at` - if not then it's ignored.
- Adds new attributes to existing API endpoints so should be backwards compatible

Add amended_at timestamp for subsequent updates of a completed PER

---

Gemfile
Gemfile.lock
config/initializers/rack_timeout.rb

P4-<TODO>
- This is a temporary measure to gather improved diagnostics on dev and staging environments; we've been seeing an increase in timeouts recently but it's not obvious where those timeouts are happening or which requests are causing them. Adding this gem with a short timeout (9 seconds for now) should mean that this timeout fires first and gives decent exception details via Sentry so we have a clearer picture of what's happening rather than relying on just logs.
- As we build a single docker image for distribution on all environments, the gem is enabled for all environment, but to prevent this from affecting production or pre-production sites the timeout middleware is only loaded for specific environments. I've tested this locally and can confirm that the timeout logging …

Add rack:timeout gem

---

lib/tasks/refresh_assessments.rake

Before attaching a move to a PER, we previously used to attach a profile, which can be linked to multiple moves. Backfill legacy PERs with moves if possible, if there are multiple moves ignore those as they will be attached manually.

Add rake task to backfill moves on legacy PERs

---

app/controllers/api/framework_assessments_controller.rb
app/controllers/api/person_escort_records_controller.rb
app/models/concerns/framework_assessmentable.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/person_escort_records_serializer.rb
db/migrate/20210129120302_add_handover_details_to_person_escort_records.rb
db/schema.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
swagger/v1/person_escort_record.yaml

P4-2625
- The initial spike for this work proposed defining explicit attributes for each of the various handover attributes e.g. `handover_recipient` but already we have seen some churn in the requirements and expect this to continue. To provide future flexibility this instead supports a single `handover_details` attribute which will persist any key/value hash the front end wishes to use.
- Currently we only require handover details for PER's so this includes some refactoring to support the diverging parameter support when patching the PER.
- Changes an api that is used in production: new attribute is optional when updating a PER so is backwards compatible, but we should probably let suppliers know about it.

Add support for new handover_details JSONB attribute when confirming PER

---

app/controllers/api/person_escort_records_controller.rb
app/models/concerns/framework_assessmentable.rb
app/serializers/person_escort_record_serializer.rb
app/serializers/person_escort_records_serializer.rb
db/migrate/20210201121439_add_handover_occurred_at_to_person_escort_records.rb
db/schema.rb
spec/models/person_escort_record_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/serializers/person_escort_record_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
swagger/v1/person_escort_record.yaml

P4-2625
- It's better if this is set explicitly rather than passed as part of the `handover_details` JSON attribute, as this needs to be incorporated into event timestamps in the near future. It's also easier to work with as a strongly typed timestamp rather than having to parse out of the other JSON details.
- Changes an api that is used in production; additional attribute is backwards compatible with existing API clients.

Add new handover_occurred_at attribute to PER

---

app/controllers/api/person_escort_records_controller.rb
app/models/generic_event.rb
app/models/generic_event/per_handover.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_handover_spec.rb
spec/requests/api/generic_events_controller_create_person_escort_record_events_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb

P4-2591
- This is created instead of the PerConfirmation event when a PER is confirmed with the new `handover_details` and `handover_occurred_at` attributes populated; this will be from the updated frontend including the new PER handover screen. 
- We want to use the new PerHandover event when the handover process is used, but retain the original PerConfirmation event for the legacy PER's. The new PerHandover event includes all of the `handover_details` in the `details` section and the `handover_occurred_at` timestamp in the `occurred_at` attribute.
- The new event looks like this when serialized back to the API client:
```json
{
"data": {
"id": "3251297f-ec8d-4d5c-9b59-4391f5fec650",
"type": "events",
"attributes": {
"event_type": "PerHandover",
"classification": "default", …
```

Add new PerHandover event

---

app/controllers/api/journeys_controller.rb
app/controllers/api/moves_controller.rb
app/controllers/api/person_escort_records_controller.rb
app/controllers/api/v1/moves_actions.rb
app/controllers/api/v2/moves_actions.rb
app/controllers/concerns/eventable.rb

P4-2591
- This happens in a few controllers now, so it's good to standardise the implementation of this with a single method with sufficient flexibility to work for all current use cases. Event creation already has good existing coverage to ensure the correct attributes are populated so we can be confident this is working as expected.

DRY up various implementations of automatic event creation

---

app/jobs/notify_webhook_job.rb

P4-<TODO>
- otherwise each webhook will be tried for 60 seconds - overnight this can lead to a large backlog if a supplier service goes down
- important fix!

Timeout webhooks after 5 seconds

---

app/serializers/framework_assessment_serializer.rb
app/serializers/person_escort_records_serializer.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
swagger/v1/person_escort_record.yaml
swagger/v1/youth_risk_assessment.yaml

P4-2659
- This will be used in the front end to show last updated at timestamp prior to other more relevant timestamps being shown once the assessment is completed.
- Changes an api that is used in production; adds a new attribute to existing PER and Youth risk assessment endpoints but is backwards compatible with existing clients.

Include `updated_at` attribute for serialized PERs and Youth risk assessments

---

app/controllers/api/framework_responses_controller.rb
app/jobs/notify_email_job.rb
app/jobs/prepare_base_notifications_job.rb
app/jobs/prepare_move_notifications_job.rb
app/jobs/prepare_person_escort_record_notifications_job.rb
app/mailers/base_mailer.rb
app/mailers/move_mailer.rb
app/mailers/person_escort_record_mailer.rb
app/models/notification.rb
app/serializers/notification_serializer.rb
app/services/notifier.rb
config/initializers/gov_uk_notify.rb
spec/factories/framework_assessment.rb
spec/jobs/notify_email_job_spec.rb
spec/jobs/prepare_person_escort_record_notifications_job_spec.rb
spec/mailer/person_escort_record_mailer_spec.rb
spec/models/notification_spec.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/serializers/notification_serializer_spec.rb
spec/services/notifier_spec.rb

P4-2627
- This requires a new Gov notify template as the email content is different than for moves, and updates to the webhook serializer as we want to send notifications (including a link) related directly to the PER. This presents some interesting challenges as there is a lot of shared behaviour for both notifications and we also need to be careful not to break and notification jobs that may be currently queued in sidekiq, so cannot change any method signatures or underlying behaviour.
- The approach I've taken is to add a new mailer class for the PER, but refactored the existing MoveMailer to extract common personalisation attributes to a new BaseMailer. The new PER mailer then needs to be called rather than the MoveMailer from the Notification class; that already has support for …

Add webhook and email notifications for PER amendments

---

app/mailers/move_mailer.rb
config/initializers/gov_uk_notify.rb

P4-2627
- The `GOVUK_NOTIFY_TEMPLATE_ID` variable has now been retired and replaced with `GOVUK_NOTIFY_MOVE_TEMPLATE_ID` and `GOVUK_NOTIFY_PER_TEMPLATE_ID`.

Small cleanup of legacy ENV vars for Govuk notify service

---

app/controllers/api/framework_assessments_controller.rb
app/controllers/api/person_escort_records_controller.rb
app/controllers/api/youth_risk_assessments_controller.rb
app/jobs/concerns/queue_determiner.rb
app/services/notifier.rb
spec/jobs/concerns/queue_determiner_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/services/notifier_spec.rb

P4-2560
- This is sent rather than PER confirmation when the update PER endpoint includes handover attributes (i.e. has been called from the updated front end handover page). This means a change in behaviour as the previous PER confirmation webhook and email will not be sent. Youth Risk assessment behaviour is unchanged.
- Suppliers need to be ready to receive the new webhook; if not then we can disable individual webhooks with an environment variable

Add new webhook (no email) for PER handover event

---

app/models/generic_event/per_court_hearing.rb
spec/models/generic_event/per_court_hearing_spec.rb

P4-2667
- presence validation is not a valid validation for boolean attributes

remove presence validation on PerCourtHearing

---

app/controllers/api/person_escort_records_controller.rb
spec/requests/api/person_escort_records_controller_update_spec.rb

P4-2560
- This is a temporary measure to support GeoAmey integration with PER Webhooks - they're not currently able to process the new PER handover webhook. This will be reverted as soon as they are able to process the new webhook.

Quick and dirty hack to reinstate PER confirmation Webhook for GeoAmey

---

app/models/location.rb
app/models/subscription.rb
app/services/locations/importer.rb
app/services/moves/move_type_validator.rb
spec/factories/location.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/services/moves/move_type_validator_spec.rb

P4-2636
- To prevent API clients from creating or redirecting moves to locations which are no longer active in Nomis (i.e. `disabled_at` is not `nil`). Updated MoveTypeValidator to include new rules and also add an explicit code for each error for easier localisation within the front end (message shown to the user can be customised based on the error `code`).
- Leveraged existing discard gem for this - which adds handy mixin scopes and methods rather than directly working with `disabled_at` column. We should look at making further use of that in AssessmentQuestion, Ethnicity, Gender, IdentifierType, Nationality and PrisonTransferReason models, and perhaps standardise to rename the column to `discarded_at` for consistency with Document, Notification and Subscription models.
- Changes an …

Raise an error when creating/redirecting move to/from inactive location

---

.circleci/config.yml

Update the CircleCI config to use the new Slack orb.
- moving to the MoJ Slack workspace requires the new major version of the orb

refactor: Update circle config to use new Slack orb

---

app/lib/nomis_client/location_details.rb
app/serializers/location_serializer.rb
app/services/locations/importer.rb
db/migrate/20210224144350_add_address_to_locations.rb
db/schema.rb
lib/tasks/reference_data.rake
spec/factories/location.rb
spec/fixtures/files/nomis/get_location_details_200.json
spec/lib/nomis_client/location_details_spec.rb
spec/serializers/location_serializer_spec.rb
spec/services/locations/importer_spec.rb
swagger/v1/location.yaml

P4-2683
- This allows address details for prisons to be exposed to API clients. A future PR will geocode these addresses to provide latitude and longitude coordinates to API clients, which will support the display of locations on a map. We want to do this geocoding in the backend so that it only has to be done once (locations are reference data) and are available to multiple clients.
- Changes an api that is used in production; extends existing location JSON with additional attributes. This affects all endpoints that include location details.

Add support for importing prison addresses from Nomis

---

app/controllers/api/framework_responses_controller.rb
app/controllers/api/person_escort_records_controller.rb
app/controllers/api/youth_risk_assessments_controller.rb
app/jobs/prepare_assessment_notifications_job.rb
app/jobs/prepare_youth_risk_assessment_notifications_job.rb
app/serializers/notification_serializer.rb
app/services/notifier.rb
spec/jobs/prepare_youth_risk_assessment_notifications_job_spec.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb
spec/requests/api/youth_risk_assessments_controller_update_spec.rb
spec/serializers/notification_serializer_spec.rb
spec/services/notifier_spec.rb

P4-2670
- This now makes the various assessment notifications consistent in both their implementation and behaviour, resolving existing tech debt, temporary workarounds and confusing code. All assessment related notifications now include a relationship to the relevant assessment and unused notifications are now remove.
- A future PR will also remove references to `PrepareAssessmentNotificationsJob` once we are sure there are no jobs queued in sidekiq.

Add a new webhook when an assessment is completed

---

.circleci/config.yml

The fields attribute was defined incorrectly leading to an error when trying to send slack notification. Additionally, if a text field is of type markdown, emojis automatically work.

refactor: Fix slack fields definition to match accepted format

---

app/jobs/notify_email_job.rb
app/jobs/notify_webhook_job.rb
config/initializers/sentry.rb

Notification errors are missing from the sentry events on staging, even though they have happened and can be found in the logs. This reverts the change to how we handle those exceptions and also comments out the tracing config as it can't be used right now and we're getting errors from sentry about it.

refactor: Revert exception handling changes and tracing config for sentry

---

app/controllers/api/journeys_controller.rb
app/serializers/journey_serializer.rb
app/serializers/journeys_serializer.rb
app/serializers/location_serializer.rb
app/serializers/locations_serializer.rb
spec/requests/api/journeys_controller_index_spec.rb
spec/serializers/journeys_serializer_spec.rb
spec/serializers/locations_serializer_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/journeys_include_parameter.yaml

P4-2693
- This was previously documented as supporting the same includes as a single journey, but in fact had no include support at all. Added support for a limited set of includes (just the from and to location) as it's less useful to return the suppliers for multiple journeys. Added new serializers for journeys and locations to avoid N+1 queries.

Add include support to move journeys endpoint

---

.circleci/config.yml

The mentions env var was slightly wrong and so the notification for approval never went out.

Fix the name of the env var holding the slack mentions

---

Dockerfile

fixes dockerfile to include `shared-mime-info` package during runtime

VERY URGENT update to Dockerfile

---

.circleci/config.yml
Gemfile
Gemfile.lock

- scheduled security audit job for circle ci
- we currently have no way of automatically getting alerted of security vulnerabilities

Add bundler audit scheduled job to circle

---

.circleci/config.yml

The executor was using the wrong ruby version. Removed special executor as not needed, using the test executor now.

Fix security audit executor to use the test executor

---

app/jobs/prepare_base_notifications_job.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

P4-<2737>
- proposed moves are internal to Book a Secure Move and should not cause notifications to suppliers until they are requested

P4-2737 disable webhooks for proposed moves

---

app/models/generic_event/per_medical_aid.rb
spec/models/generic_event/per_medical_aid_spec.rb

P4-<TODO>
- requested change by suppliers to handle event where aid is requested but not required
- minimal

Relax rules on per_medical_aid treated_at and treated_by

---

app/jobs/notify_email_job.rb
app/jobs/notify_webhook_job.rb
app/services/retry_job_error.rb
config/initializers/sentry.rb
spec/jobs/notify_email_job_spec.rb
spec/jobs/notify_webhook_job_spec.rb

Raise RetryJobError on job errors, to avoid duplicate Sentry errors
P4-<TODO>
- we were getting duplicate errors in Sentry

Raise RetryJobError on job errors

---

Gemfile.lock

- there are security issues with version 3.2.4

bump rexml to 3.2.5

---

.circleci/config.yml

P4-2836
- It will make the failed audit more visible, so that it can be actioned faster.

[P4-2836] Notify Slack when circle audit job fails

---

.circleci/config.yml

P4-2836
- The CircleCI job has stopped running and we believe that it's waiting for a new commit, because the last run failed.

P4 2836/make audit notify slack on fail

---

app/controllers/api/reference/locations_controller.rb
app/serializers/locations_serializer.rb
app/services/locations/finder.rb
spec/requests/api/reference/locations_controller_spec.rb
spec/serializers/location_serializer_spec.rb
spec/serializers/locations_serializer_spec.rb
spec/services/locations/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/location.yaml

P4-2831
- It will allow JPC to automatically recognise new locations

P4-2831: Add created_at to locations + filter

---

app/controllers/api/generic_events_controller.rb
app/models/generic_event.rb
app/models/generic_event/move_notify_premises_of_drop_off_eta.rb
app/models/generic_event/move_notify_premises_of_eta.rb
app/models/generic_event/move_notify_premises_of_pickup_eta.rb
app/models/move.rb
lib/tasks/data_maintenance.rake
lib/tasks/fake_data/notification_events.rb
spec/factories/generic_event.rb
spec/models/generic_event/move_notify_premises_of_drop_off_eta_spec.rb
spec/models/generic_event/move_notify_premises_of_pickup_eta_spec.rb
spec/models/move_spec.rb
spec/requests/api/generic_events_controller_create_move_events_spec.rb
spec/requests/api/moves_controller_filtered_spec.rb
spec/requests/api/moves_controller_index_v2_spec.rb
spec/serializers/v2/moves_serializer_spec.rb

now re-maps MoveNotifyPremisesOfEta to MoveNotifyPremisesOfDropOffEta
P4-2816
- so we have clear visibility of whether the ETA is for collection or drop-off
- Frontend templates will require updating prior to deployment

P4-2816 drop-off and pickup ETA events

---

config/initializers/sentry.rb

- CP have enabled a trial for the performance features of Sentry

chore: Enable Sentry performance tracking

---

app/models/generic_event/move_notify_premises_of_arrival_in_30_mins.rb
app/models/generic_event/move_notify_premises_of_drop_off_eta.rb
app/models/generic_event/move_notify_premises_of_eta.rb
app/models/generic_event/move_notify_premises_of_expected_collection_time.rb
app/models/generic_event/move_notify_premises_of_pickup_eta.rb
app/models/move.rb
lib/tasks/data_maintenance.rake
spec/factories/generic_event.rb
spec/models/generic_event/move_notify_premises_of_arrival_in30_mins_spec.rb
spec/models/generic_event/move_notify_premises_of_drop_off_eta_spec.rb
spec/models/generic_event/move_notify_premises_of_expected_collection_time_spec.rb
spec/models/generic_event/move_notify_premises_of_pickup_eta_spec.rb
spec/models/generic_event/notification_spec.rb
spec/requests/api/moves_controller_filtered_spec.rb

P4-<TODO>
- they render better in the frontend without notifications

Change eta classification

---

app/models/move.rb
spec/models/generic_event/move_start_spec.rb
spec/support/an_event_with_eventable_types.rb

P4-2902
- because a large number of PERs are not being confirmed, which means they cannot be used for pre-fill later

P4-2902 auto confirm PER on move start

---

app/services/locations/finder.rb
spec/services/locations/finder_spec.rb

P4-2826
- to allow the front end to optimise its calls to the API - see https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/issues/1028
-
-

P4 2826 multiple location types

---

app/models/concerns/framework_assessmentable.rb
spec/models/person_escort_record_spec.rb

P4-2973
- sometimes the handover record needs to be added after the PER has been auto-confirmed

fix to allow an autoconfirmed PER to be handed over

---

spec/requests/api/moves_controller_create_v2_spec.rb

Category is an optional association on a profile, but we don't have a test for what happens when a move is created with a profile which doesn't have one. This test shows that currently the move is created (with a 201 status code being returned).
This test is effectively the same as https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/2d712137bb42b96bf83813326c33c97b20ea47a0/spec/requests/api/moves_controller_create_v2_spec.rb#L65-L67 but I think that's fine as it's more explicit and the behaviour is now well defined. If we decided to change the behaviour in the future such that a category was always required, we may decide to change the first `let(:profile`) in this test file to be one with a supported category (and then remove the test lower down in the file which tests …

Add a test for when a profile has no category

---

app/lib/nomis_client/base.rb
spec/lib/nomis_client/allocations_spec.rb
spec/lib/nomis_client/court_hearings_spec.rb
spec/services/framework_nomis_mappings/importer_spec.rb
spec/support/captures_sentry_message.rb

[P4-2982](https://dsdmoj.atlassian.net/browse/P4-2982)
- Added more information to Prison API errors in Sentry
- Refactored tests by including a shared example for testing a message is captured in Sentry
**Probably easier to review commit by commit because of the refactor.**
This should allow us to filter Sentry errors on the status of the response from the Prison API meaning ultimately we can focus specifically on the ones which return a `500` error.

Improve additional data for Prison API Sentry errors

---

app/controllers/api/people_controller.rb
spec/requests/api/people_controller_index_spec.rb

This changes how we use Strong Parameters to ensure that the value is first a hash before trying to execute `permit` on it, which avoids an unnecessary NoMethodError we've got in Sentry: https://sentry.io/organizations/ministryofjustice/issues/2510208419/

Avoid NoMethodError with an array filter

---

lib/tasks/gps_data_report.rake

Fix name of GPS data report rake task

---

Gemfile
Gemfile.lock
app/workers/gps_report_worker.rb
spec/workers/gps_report_worker_spec.rb

P4-2944
- It's much easier to use the webhook that we already have than to try to get an OAuth token.  We'll have to have a think about how best to supply the csv files to the suppliers. Possibly upload them to AWS.

Use Slack webhook instead of API

---

app/controllers/api/moves_controller.rb
app/services/moves/finder.rb
spec/requests/api/moves_controller_filter_spec.rb
spec/requests/api/moves_controller_filter_v2_spec.rb
spec/services/moves/finder_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

[P4-3019](https://dsdmoj.atlassian.net/browse/P4-3019)
I've added two new filters to the move endpoint, `profile_id` and `person_id` that allows a user to filter the moves based on those values. I've also refactored some of the code in this area.
We want to build a page which displays the moves for a specific profile/person, so we need this filter in the API to support that. We don't necessarily need both filters, but I figured there was no harm in having more options.

Allow filtering moves by profile or person

---

app/jobs/notify_webhook_job.rb
spec/jobs/notify_webhook_job_spec.rb

This is a new error which is raised when a notification webhook returns with a non-success response. I've introduced this so we can better organise the errors in Sentry as there will be a clear exception. It also allows us to record these as warnings in Sentry, rather than errors.

Add NotificationFailedResponseError

---

app/services/framework_nomis_mappings/importer.rb
spec/services/framework_nomis_mappings/importer_spec.rb

This improves the structure of Sentry issues related to Framework NOMIS Mappings by using tags and extras. Specifically, if we import a NOMIS code that we haven't seen before, it includes the NOMIS code in the tags and changes the level to a warning.

Improve Framework NOMIS Mappings Sentry issues

---

Gemfile
Gemfile.lock

This PR organises the Gemfile [according to the conventions used by GOV.UK at GDS](https://docs.publishing.service.gov.uk/manual/conventions-for-rails-applications.html#gemfile-organisation). I think this makes the Gemfile easier to read and understand, and avoids it becoming a bit of a mess.
See individual commits for more details on the changes.

Organise Gemfile according to GOV.UK conventions

---

app/services/framework_nomis_mappings/assessments.rb
spec/services/framework_nomis_mappings/assessments_spec.rb

This resolves an issue we saw in Sentry this morning https://sentry.io/organizations/ministryofjustice/issues/2554016969 where the assessment was imported without a classification, and therefore it was `nil` when trying to build the comment.

Handle when assessment has no classification

---

config/initializers/sentry.rb

We're hitting our monthly rate limit, and we probably don't need to capture all possible traces, so we can reduce the number we capture to ensure we get results throughout the month.
Related to https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1874

Reduce number of trace samples

---

app/services/gps_report.rb
spec/services/gps_report_spec.rb

P4-2944
- It will help us understand why the gps data report has failed

Add Athena query_id to sentry extras

---

k8s_migrate_job.yml

Some of our migrations require ActiveStorage to be available. Specifically this was most recently added in the Rails 6.1 upgrade in 7842199ed4186824fb96289bc7f36af9a99db12b.
Without these environment variables defined, trying to run migrations fails with the following error message:
```
Caused by:
Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:
- :access_key_id and :secret_access_key
- :credentials
- :credentials_provider
```
This is required to deploy #1527

Ensure S3 env vars are available during migrations

---

k8s_migrate_job.yml

To fix the following error:
```
error: error parsing STDIN: error converting YAML to JSON: yaml: line 31: mapping values are not allowed in this context
```

Fix indentation in YAML file

---

config/puma.rb

This was added in the upgrade to Rails 6.1 but we don't need to use it. We are seeing this error if we specify a pidfile:
```
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pids/server.pid
/usr/local/bundle/gems/puma-5.4.0/lib/puma/launcher.rb:247:in `write'
/usr/local/bundle/gems/puma-5.4.0/lib/puma/launcher.rb:247:in `write_pid'
/usr/local/bundle/gems/puma-5.4.0/lib/puma/launcher.rb:111:in `write_state'
/usr/local/bundle/gems/puma-5.4.0/lib/puma/cluster.rb:398:in `run'
/usr/local/bundle/gems/puma-5.4.0/lib/puma/launcher.rb:181:in `run'
/usr/local/bundle/gems/puma-5.4.0/lib/puma/cli.rb:80:in `run'
/usr/local/bundle/gems/puma-5.4.0/bin/puma:10:in `<top (required)>'
/usr/local/bundle/bin/puma:23:in `load' …
```

Don't define a pidfile

---

app/models/court_hearing.rb
spec/models/court_hearing_spec.rb

This ensures that the comments field of court hearings is always less than 240 characters as this is a requirement from NOMIS. This validation should prevent us getting a 400 error when communicating with NOMIS and instead pass the error up to the user who can fix the problem.
This should resolve: https://sentry.io/organizations/ministryofjustice/issues/2277351361/events/eb493612c82141d09387381ad3c22829/

Validate CourtHearing comments field length

---

app/workers/gps_report_worker.rb

P4-2944
- It will allow us more time to download the files (currently 15 minutes at 6 AM)

Change gps failure file expiry to 1 week

---

app/serializers/v2/move_serializer.rb

This should allow clients to get location information of different journeys of a move. We need this because the timeline events sometimes contain references to journeys which are cancelled, and therefore we have no way of including the `to_location` and `from_location` fields of those journeys. This means the timeline view on the frontend is sometimes missing information (this is the case where a journey has a different `to_location` or `from_location` of the move and therefore isn't included).
This might have a performance impact on the endpoint, but we can monitor closely is this becomes a problem. I don't expect many moves to have multiple journeys.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2988)

Allow including journey information on moves

---

app/models/person.rb
spec/factories/person.rb
spec/models/person_spec.rb
spec/requests/api/people_controller_create_spec.rb
spec/requests/api/people_controller_create_v2_spec.rb
spec/requests/api/people_controller_index_spec.rb
spec/requests/api/people_controller_index_v2_spec.rb
spec/requests/api/people_controller_patch_v2_spec.rb
spec/requests/api/people_controller_update_spec.rb
spec/serializers/person_serializer_spec.rb
spec/services/people/creator_spec.rb
spec/services/people/finder_spec.rb
spec/services/people/updater_spec.rb
spec/services/v2/people/finder_spec.rb

P4-2828
- It will stop our users from inputting invalid PNC numbers

Add PNC number validation to Person

---

app/services/gps_report.rb
spec/services/gps_report_spec.rb

P4-2944
- It's stopping the gps data report from running

Fix error when a journey has 1 gps point

---

app/lib/nomis_client/court_hearings.rb
spec/lib/nomis_client/court_hearings_spec.rb
spec/support/captures_sentry_message.rb
spec/support/sentry.rb

At the moment we get an exception whenever a court date is rejected because of a location mismatch (where NOMIS doesn’t understand that a prisoner may be in a different location in the future). Rather than reporting this as an error in Sentry, we want to call it out as its own type of warning so we can focus on other errors and get a better idea of how much of a problem this one is.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2157)

Warn when NOMIS rejects court dates due to location mismatch 

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

This updates the filter for moves such that a completed per is considered ready for transit, rather than just a confirmed one. This change means that moves with a completed, but not confirmed, PER will show in the "ready for transit" section rather than the "incomplete" section.
The old behaviour makes sense when PERs used to have to be confirmed, but now that PERs are automatically confirmed when a move starts, it doesn't make sense to keep the move in the incomplete state until that point.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2920)

Consider completed PERs as 'ready for transit'

---

config/initializers/sentry.rb

We're still experiencing a problem where the MoJ Sentry account gets rate limited after a couple of weeks because too many transactions are being reported.
This reduces the sample rate from 25% to 10%.

Reduce Sentry transaction sample rate

---

app/lib/imports/journeys_missing_vehicle.rb
app/lib/imports/missing_move_ending_events.rb
app/lib/imports/missing_move_start_events.rb
app/lib/imports/moves_without_ending_state.rb
app/lib/imports/results.rb
spec/lib/imports/journeys_missing_vehicle_spec.rb
spec/lib/imports/missing_move_ending_events_spec.rb
spec/lib/imports/missing_move_start_events_spec.rb
spec/lib/imports/moves_without_ending_state_spec.rb
spec/lib/imports/results_spec.rb

This adds the ability to record a reason if a record fails to import, so we can better investigate why it might have failed.

Record failure reason in import results

---

swagger/v1/post_move_lockout.yaml

P4-3287
- It has been confused for the Move's from_location

Clear up documentation for MoveLockout.from_location

---

app/lib/imports/moves_without_ending_state.rb
spec/lib/imports/moves_without_ending_state_spec.rb

This modifies the import process for moves without an ending state to rely on the existing event which should already be there. This change is so we can support cancelled or rejected moves that do more than just change the status of the move, they also assign a `cancellation_reason` field.

Use events to transition move status

---

app/lib/imports/journeys_without_ending_state.rb
lib/tasks/import.rake
spec/lib/imports/journeys_without_ending_state_spec.rb
spec/lib/tasks/imports/journeys_without_ending_state_spec.rb

This updates the status of journeys to the one specified in the spreadsheet. This is designed to fix the state of journeys which have an event but the incorrect associated journey status.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3300)

Add import task for journeys without ending status

---

app/lib/imports/missing_journey_ending_events.rb
lib/tasks/import.rake
spec/lib/imports/missing_journey_ending_events_spec.rb
spec/lib/tasks/imports/missing_journey_ending_events_spec.rb

This adds a task for import journeys which don't have ending events. This is similar to the one for moves which don't have ending events.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3300)

Import journeys missing ending events

---

lib/tasks/import.rake
spec/lib/tasks/imports/missing_journey_start_events_spec.rb

This fixes a small typo in 053c6a6791273a645beca53108ab0c0e0f3e49f2 where the column name was incorrect.

Fix typo in column name

---

app/services/diagnostics/move_inspector.rb

This was accidentally missed out in 895767b58efe2922c1c3fc221e25be880c5bf7ae and means that the diagnostics endpoint can return a 500 internal server error in certain cases.
The error in this case was something like:
```
NameError (undefined local variable or method `key' for #<Diagnostics::MoveInspector:0x00007fbf44dbbf18>)
```

Fix NameError in move inspector

---

app/lib/imports/journeys_missing_vehicle.rb
app/lib/imports/journeys_without_ending_state.rb
app/lib/imports/missing_journey_ending_events.rb
app/lib/imports/missing_journey_start_events.rb
app/lib/imports/missing_move_ending_events.rb
app/lib/imports/missing_move_start_events.rb
app/lib/imports/moves_without_ending_state.rb
app/lib/imports/results.rb
spec/lib/imports/results_spec.rb

This updates the various importers to check objects are valid before attempting to update them. This avoids problems where an object might be invalid prior to the import and processing an event calls `save!` which raises an exception and terminates the entire import.
Example Sentry issue: https://sentry.io/organizations/ministryofjustice/issues/2794490913/?project=2014776&query=is%3Aunresolved

Make importer ignore objects which aren't valid

---

app/lib/imports/moves_without_to_location.rb
lib/tasks/import.rake
spec/lib/imports/moves_without_to_location_spec.rb
spec/lib/tasks/imports/moves_without_to_location_spec.rb

This adds a task for importing and fixing moves which are missing a `to_location` value.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3364)

Add task for importing moves without a to location

---

db/migrate/20211208080712_drop_events.rb
db/schema.rb

This follows on from https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1171 to remove the underlying table for the now unused `Event` model. It looks like this was simply missed when the model was deleted, as it's now been entirely replaced by the `GenericEvent` model and is no longer used at all.

Remove unused events table

---

lib/tasks/data/supplier_locations.yml

This is a new location we want to support in BaSM so we need to assign a supplier location to it so moves can be booked against it.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3388)

Add BULMIL to Serco locations

---

app/models/move.rb

We need to manually fix the data on moves which were left uncancelled, however if the supplier has lost information such as the cancellation reason we need to pick one. Rather than using `other`, we can be explicit and say that we don't know the correct cancellation reason and that the data is not 100% accurate.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3400)

Add cancellation reason for database corrections

---

app/controllers/api/suppliers_controller.rb
spec/requests/api/suppliers_controller_locations_spec.rb

Currently, this endpoint only returns locations for a supplier if there's a move booked from that location for the associated supplier. This means when new locations are added and assigned to a supplier, it won't be included in this endpoint until a move has been booked from it.
We'd like to expand the scope of this so we have this existing behaviour, plus we return any locations where moves may (in the future) be booked from, allowing the suppliers to be aware of all possible locations. In particular, this helps our supplier users (for example contract delivery managers) see all the locations in the system.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3389)

Expand scope of supplier locations endpoint

---

app/lib/imports/missing_journey_ending_events.rb
spec/lib/imports/missing_journey_ending_events_spec.rb

Currently we can only import journeys which are then to be completed or cancelled. This change allows us to import journeys which are proposed and to be rejected.

Allow importing journeys to be rejected

---

app/lib/imports/cancel_or_reject_journeys.rb
lib/tasks/import.rake
spec/lib/imports/cancel_or_reject_journeys_spec.rb
spec/lib/tasks/imports/cancel_or_reject_journeys_spec.rb

This adds a new import task for cancelling or rejecting journeys which are duplicates and therefore shouldn't really exist. We don't want to delete the journeys as it may affect payments.

Import journeys which should be cancelled or rejected

---

app/controllers/api/suppliers_controller.rb
spec/requests/api/suppliers_controller_locations_spec.rb

Reverts ministryofjustice/hmpps-book-secure-move-api#1687
This seems to make the endpoint much slower and prevents some uses from being able to choose a location: https://sentry.io/organizations/ministryofjustice/issues/2926771799/?project=2014813&referrer=regression-activity-email

Revert "Expand scope of supplier locations endpoint"

---

app/lib/imports/cancel_or_reject_journeys.rb
spec/lib/imports/cancel_or_reject_journeys_spec.rb

Currently when cancelling or rejecting a journey that requires two events, we end up assigning the same timestamp to these dates. This is problematic as it means when replaying the events, there's no guarantee on the ordering.

Add delays between subsequent events when importing

---

app/models/person.rb
app/validators/prison_number_validator.rb
spec/models/person_spec.rb

This adds some basic validation to ensure they don't contain a colon character to prevent an exception happening when communicating with NOMIS.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2127)

Add basic validation on prison numbers

---

db/migrate/20220125102025_add_indexes_to_locations.rb
db/schema.rb

I've noticed that when the database is under high load, queries to the `/api/v1/reference/locations` endpoint often seem to take a long time, and even time out. Looking in the logs, the most common query parameters on this endpoint are `location_type` and `nomis_agency_id`, so I'm hoping that by putting in these indexes it will stop these timeouts from happening.
The indexes have been added concurrently which should mean the database table isn't locked as the migrations run.
See
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:fb2e6550-0186-11ec-a2cf-6b21ca2b1d39,key:log_processed.k …

Add indexes for some location fields

---

app/lib/imports/missing_move_start_events.rb

Serco are saying that they are experiencing performance issues with this backfill as notifications are sent to them at a high rate. I'm hoping that by introducing a small delay after each import should reduce those performance issues.
This will mean the imports take longer, but at the moment we're having to run the import in small batches with delays between each batch which is a lot of manual work whereas this should allow us to import large batches where the script itself introduces the delay.
The number I've chosen for the delay is arbitrary, and might need to be tweaked.

Add delay to import move start events

---

app/lib/imports/missing_move_start_events.rb

Reverts ministryofjustice/hmpps-book-secure-move-api#1712
We no longer need this as the import has finished.

Revert "Add delay to import move start events"

---

spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml

This is a feature that was added to allow suppliers and our frontend to find a move by searching for the reference (d98bd8eeca71369eaaa0d916bfc9e0021ca7952a). The documentation wasn't updated when it was originally added so this commits ensures the documentation is there now.

Document how to filter moves on the reference

---

Gemfile.lock
app/models/ability.rb
app/models/move.rb
spec/models/ability_spec.rb
spec/models/move_spec.rb

This is only allows if the move is between locations owned by different suppliers. For example, if location A is managed by supplier A and location B is managed by supplier B, and there is a move booked which goes between location A and B, both suppliers should have permission to manage this move.
This functionality allows us to support "supplier to supplier" moves where the person is handed over to a different supplier during the course of the move.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3436)

Allow suppliers to manage moves of other suppliers

---

app/controllers/api/journeys_controller.rb
app/models/journey.rb
app/serializers/journeys_serializer.rb
app/services/feeds/journey.rb
app/services/journeys/params_validator.rb
db/migrate/20220131135817_add_date_to_journeys.rb
db/schema.rb
spec/factories/journeys.rb
spec/models/journey_spec.rb
spec/requests/api/journeys_controller_create_spec.rb
spec/requests/api/journeys_controller_update_spec.rb
spec/serializers/journey_serializer_spec.rb
spec/serializers/journeys_serializer_spec.rb
spec/services/journeys/params_validator_spec.rb
swagger/v1/get_journey.yaml
swagger/v1/patch_journey.yaml
swagger/v1/post_journey.yaml

This adds the concept of journey dates which we're adding to support moves which happen across multiple days.
Once this has been deployed, the next step will be to backfill the journey dates to match with the move date.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3337)

Add dates to journeys

---

lib/tasks/backfill.rake
spec/lib/tasks/backfill/journey_dates_spec.rb

This will populate the journey dates with the move date as would happen if the journey had been created at the time.
Depends on #1723 
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3337)

Add a task for backfilling journey dates 

---

lib/tasks/backfill.rake
spec/lib/tasks/backfill/journey_dates_spec.rb

We want to be able to limit the number of journeys we import to reduce the sizes of the feed files. We'll end up importing all the journeys over time in batches.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3337)

Add limit to backfilling journey dates

---

app/services/locations/updater.rb

In #1743 we updated the reference data for HMP Parc (as it's youth side is being split up in to a separate location) but this was not updated as it should have been.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3032)

Mark PYI as a youth offender institution

---

app/models/generic_event.rb
app/models/generic_event/per_property_change.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_property_change_spec.rb
spec/requests/api/generic_events_controller_create_person_escort_record_events_spec.rb

This is to represent a change to the property of a person being moved after a move has started (and therefore the PER is locked in). We'll be using this event as a way of making amendments to the PER.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3335)

Add GenericEvent::PerPropertyChange

---

app/jobs/notify_webhook_job.rb

This refactors the notification webhook job to make it easier to read and maintain. I've also slightly changed the error reporting logic so that timeout errors are grouped with other kinds of `NotificationFailedResponseError` errors in Sentry.

Refactor notification webhook job

---

app/jobs/notify_webhook_job.rb

This follows on from https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1753 to capture another kind of error we get and group it into the notification failed error.
This should prevent issues like https://sentry.io/organizations/ministryofjustice/issues/3066627844/ being recorded as separate events in Sentry.

Capture error when requesting webhook

---

app/models/generic_event.rb
app/models/generic_event/per_concealed.rb
app/models/generic_event/per_escape.rb
app/models/generic_event/per_incident.rb
app/models/generic_event/per_self_harm.rb
app/models/generic_event/per_violent_dangerous.rb
app/models/generic_event/per_weapons.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_concealed_spec.rb
spec/models/generic_event/per_escape_spec.rb
spec/models/generic_event/per_incident_spec.rb
spec/models/generic_event/per_self_harm_spec.rb
spec/models/generic_event/per_violent_dangerous_spec.rb
spec/models/generic_event/per_weapons_spec.rb
spec/models/generic_event_spec.rb
spec/support/an_event_about_a_per_incident.rb

These will be used in lockouts and overnight lodges to record any changes to the PER which would be appropriate for the second leg of any move. Specifically, while in police custody, these might be recorded by police personnel.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3335)

Add lockout events

---

.github/CODEOWNERS

This team contains only developers and means we'll automatically be asked to review any PRs.

Assign PECS Developers as code owners

---

app/controllers/api/generic_events_controller.rb
app/jobs/prepare_generic_event_notifications_job.rb
app/models/generic_event.rb
app/models/notification.rb
app/serializers/notification_serializer.rb
app/services/notifier.rb
spec/jobs/prepare_generic_event_notifications_job_spec.rb
spec/serializers/notification_serializer_spec.rb
spec/services/notifier_spec.rb
spec/support/a_generic_event_endpoint.rb

This makes it possible to send out notifications for the creation of events. Specifically, we're adding this functionality to support lockouts and overnight lodgings, where we want police users to add events and to let the suppliers know.
This won't go live as I'll disable these notifications until the suppliers are ready to handle them using: 
https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/0f69b45111b8b5d831f5cfe1439280161c28f885/app/jobs/prepare_base_notifications_job.rb#L50
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3427)

Add support for events from notifications

---

app/models/journey.rb
app/serializers/journeys_serializer.rb
spec/models/journey_spec.rb
spec/serializers/journeys_serializer_spec.rb

This adds a number field to journeys which represents the human-readable index of the journey.
It's [a bit awkward to implement this in an efficient way (i.e. including it within the `SELECT` of the query)](https://stackoverflow.com/a/18751290) so I've left it as a separate query for now. I don't anticipate this being a problem as most moves only have one or two journeys, so it's not an extreme `N+1` problem, but we can monitor this when we release it.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3345)

Add numbers to journeys

---

app/models/move.rb
app/models/person_escort_record.rb
spec/models/person_escort_record_spec.rb

This expands which events are considered important in the context of a PER. This is necessary as we'd like to start displaying PER incidents and property change events on the move detail page which is populated from the `important_events`.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3519)

Expand important events for PERs

---

app/models/journey.rb
app/services/moves/finder.rb
spec/models/journey_spec.rb
spec/services/moves/finder_spec.rb

This modifies how the move finder works to search using the journeys associated with a move, as well as the move itself. This is necessary to support moves which happen across multiple days with a location in the middle.
The difference is that we now include the date of the journeys and the to/from location of the journeys when performing the search.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3339)

Include journeys when finding moves

---

app/models/move.rb
spec/services/moves/updater_spec.rb

We currently don't allow the date of an allocation to be modified after it's been created, but the date of the moves can be changed. This can cause a mismatch between the allocation and the moves which leads to the allocation not appearing in the right place in the frontend.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3585)

Prevent allocation moves date being updated

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

This follows up https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1791 to clarify some logic which was missing from the original implementation. Specifically, this prevents moves from appearing when they shouldn't, as rather than combining the move date/locations and the journey date/locations, we ignore the move details if journeys are there (this does require trusting the journey details are correct for multi-day moves).
I've added tests for the 12 different scenarios and when the moves should or should not appear.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3339)

Fix finding moves with journeys

---

app/controllers/api/allocation_events_controller.rb
app/models/move.rb
spec/models/move_spec.rb

Cancelling a move can affect the status of an allocation as only moves which are not cancelled are used to determine the status. Without this, you can end up in a state where an allocation is left unfilled if the one of the moves ends up being cancelled before the other moves start.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3563)

Refresh allocation status when cancelling a move

---

db/migrate/20220328093153_add_index_to_journey_date.rb
db/schema.rb

This adds an index on the journey date field to ensure the filters for finding a move based on the journeys is performant.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3339)

Add index to journey dates

---

app/models/generic_event/move_lockout.rb
app/serializers/v2/moves_serializer.rb
db/migrate/20220328100142_add_column_is_lockout_to_moves.rb
db/schema.rb
spec/acceptance/generic_events/runner_spec.rb
spec/requests/api/move_events_controller_lockout_spec.rb

[P4-3340](https://dsdmoj.atlassian.net/browse/P4-3340)
Added the `is_lockout` field to the move model, as well as trigger an update to the `is_lockout` field whenever a lockout occurs
I am doing this because: This allows the frontend to receive this specific field without the need for us to pull in more data than we need into the frontend

Add is_lockout field to move object and trigger change when lockout occurs

---

app/models/journey.rb
app/models/move.rb
app/validators/different_to_from_location_validator.rb
spec/models/journey_spec.rb
spec/models/move_spec.rb

This adds validation on moves and journeys to ensure that the `from_location` and `to_location` fields are different. It shouldn't be valid for a move to have the same source/destination location.
We may need to hold off on deploying this until both of our suppliers are aware and comfortable of the validation.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3363)

Ensure moves and journeys locations are different

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

This partially reverts #1793 and #1791 as it's having a performance impact. Hopefully once the indexes have been deployed in #1797 and #1799, we can put this query back without an issue.

Revert including journeys when finding moves

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

This brings back the functionality that was reverted in #1800 but with an optimised query making use of the `UNION` operator. This ensures the query planner is able to generate a better query rather than doing a sequential scan on the moves table, it can rely on in indexes.
To actually generate the `UNION` query in Rails, I've followed the code used from [this article](https://joshfrankel.me/blog/a-journey-into-writing-union-queries-with-active-record/) as it's not built in to ActiveRecord. The query is a little odd as it uses an `id IN (...)`, but that's more of a quirk of how it works in ActiveRecord and doesn't introduce any major slowdowns. I've concluded that it's better to keep the query in Ruby rather than dropping down to SQL, than to produce the most optimal query.
I'm confident …

Filter on journey information efficiently

---

app/models/concerns/framework_assessmentable.rb
app/serializers/framework_response_serializer.rb
spec/models/person_escort_record_spec.rb
spec/serializers/framework_response_serializer_spec.rb

This adds the information of who completed a framework response to the API so it can be accessible by the frontend.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3574)

Add framework response author information to serializers

---

app/models/concerns/framework_assessmentable.rb
spec/factories/framework_assessment.rb
spec/factories/framework_question.rb
spec/factories/framework_response.rb
spec/models/framework_response/string_spec.rb
spec/models/framework_response_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/requests/api/youth_risk_assessments_controller_show_spec.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/support/a_framework_assessment.rb

Currently we check if all of the questions have been responded to update the status of the assessment to complete. This isn't quite right as some questions are not required, and shouldn't prevent the assessment from being marked as complete.
Specifically, this is required to support the date of arrest optional question we're adding to the frameworks: https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks/pull/63
Related to https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/2392
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2987)

Update assessment status based on required questions

---

app/models/concerns/framework_assessmentable.rb
spec/factories/framework_assessment.rb
spec/factories/framework_question.rb
spec/factories/framework_response.rb
spec/models/framework_response/string_spec.rb
spec/models/framework_response_spec.rb
spec/requests/api/person_escort_records_controller_show_spec.rb
spec/requests/api/youth_risk_assessments_controller_show_spec.rb
spec/serializers/framework_assessment_serializer_spec.rb
spec/serializers/person_escort_records_serializer_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb
spec/support/a_framework_assessment.rb

Reverts ministryofjustice/hmpps-book-secure-move-api#1814
This is causing an issue with the Youth Risk Assessments (https://sentry.io/organizations/ministryofjustice/issues/3183417988/?referrer=slack)

Revert "Update assessment status based on required questions"

---

app/models/move.rb
app/models/person_escort_record.rb
spec/models/move_spec.rb
spec/models/person_escort_record_spec.rb

This refactors the move incident events to simplify the code, reduce the number of queries to the database and improves the tests.
Closes #1821 
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3346)

Refactor move incident events

---

app/controllers/api/person_escort_records_controller.rb
app/models/generic_event/per_handover.rb
app/models/move.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_handover_spec.rb
spec/models/move_spec.rb
spec/requests/api/person_escort_records_controller_update_spec.rb

For lockouts and overnight lodges, we know there will be at least two PER handovers. Once when the move starts on the first day (handover from location to supplier) and once on the second day (handover from police custody to supplier).
To better support this behaviour, I've added locations to the PER handover event so we know where the handover occurred, and ensured that the handover events are returned in the important events for a PER, allowing us to render these on the frontend in the details tab. The location should appear in the `handover_details` as a `location_id` field.
The ability to record multiple PER handover events is already implemented, it happens if automatically if you update the handover details on a PER, each time an event is created.
[Jira …

Support multiple handovers

---

app/models/concerns/location_feed.rb
spec/support/an_event_with_a_location_in_the_feed.rb

Some events, notable the PerHandover event, will have an optional location. This is currently not supported when it tries to export the feed for the events, and so we get an exception raised.
[Sentry Issue](https://sentry.io/organizations/ministryofjustice/issues/3231300738/)

Handle optional locations in event feed

---

app/controllers/api_controller.rb
app/models/concerns/framework_assessmentable.rb
app/models/generic_event/per_confirmation.rb
lib/tasks/populate_per_confirmation_with_responded_by.rake
spec/models/generic_event/per_confirmation_spec.rb
spec/models/person_escort_record_spec.rb

This is the API side of this work, there is still frontend work to do, but I'm releasing this so that I can complete the frontend work more easily.
P4-3575
- It will allow the frontend to display the authors of PERs.

Add responded_by to PerConfirmation event details

---

db/migrate/20220608135622_add_index_to_generic_event_updated_at.rb
db/schema.rb

We are experiencing slow queries for the events feed. Adding an index to the updated at should help reduce the query times.
[P4-3715](https://dsdmoj.atlassian.net/browse/P4-3715)
I have added:
Index to the update_at field on the generic_events table.
We are experiencing very slow times for the reporting feeds.

Add index to the updated_at field on the generic_events table.

---

lib/tasks/backfill_per_completion.rake

The backfill task from the previous PR was failing in staging because somehow, some completed PERs didn't have a completed_at set.

Fix issue with PerCompletion backfill without completed_at

---

db/migrate/20220608135622_add_index_to_generic_event_updated_at.rb

Updating index migration to only create if the index does not already exist.
**Jira link**
[P4-3715](https://dsdmoj.atlassian.net/browse/P4-3715)
What?
**I have added:**
Index to the update_at field on the generic_events table.
Why?
We are experiencing very slow times for the reporting feeds.

P4-3715 changing migration for updated_at on generic_events to only create if it doesn't exist.

---

db/migrate/20220608135622_add_index_to_generic_event_updated_at.rb

[P4-3717](https://dsdmoj.atlassian.net/browse/P4-3715)
- the index creation to be locking on the updated_at field.
We believe the migration is not able to be applied concurrently in a timely fashion due to the volume of data and activity in the events table hence the deployment is failing and the index is not valid.

P4-3715 change the index creation to be locking instead of concurrent on updated_at.

---

db/migrate/20220608135622_add_index_to_generic_event_updated_at.rb

Reverts ministryofjustice/hmpps-book-secure-move-api#1863

Revert "P4-3715 change the index creation to be locking instead of concurrent on updated_at."

---

app/models/generic_event.rb
app/models/generic_event/per_updated.rb
app/state_machines/framework_assessment_state_machine.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_completion_spec.rb
spec/models/generic_event/per_updated_spec.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/framework_responses_controller_update_spec.rb

P4-3577
- It's helpful to see which users updated which sections of the PER.

Add PerUpdated event

---

app/workers/notify_unnotified_moves_worker.rb
lib/tasks/gps_data_report.rake
lib/tasks/notify_unnotified_moves.rake
spec/workers/notify_unnotified_moves_worker_spec.rb

This job will create create_move notifications for moves without them.
Every hour a query will run, looking for moves in BaSM that:
1. are requested for the next two days
2. are not in the proposed or cancelled state
3. have no notifications
For any moves returned, a move requested event and a create move notification will then be generated.

Add notify_unnotified_moves job

---

app/services/allocations/creator.rb
spec/services/allocations/creator_spec.rb

[P4-3705](https://dsdmoj.atlassian.net/browse/P4-3705)
-  The creation of Allocation moves move requested events.
- This is to bring inline with move requested events for standard move creation so the UI logic for the events is the same.

Bring alloction move requested events in line with single move request, supplier does not need populating for these events

---

app/controllers/api/framework_responses_controller.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb

P4-3767
- We are currently getting sentry alerts for it and the response to the caller isn't very helpful as it's an unhandled error

Catch exception when invalid data is passed to bulk framework response update

---

.gitignore
app/models/concerns/framework_assessmentable.rb
app/services/framework_responses/bulk_updater.rb
spec/requests/api/framework_responses_controller_bulk_update_spec.rb
spec/requests/api/person_escort_records_controller_create_spec.rb
spec/services/framework_responses/bulk_updater_spec.rb

P4-3888
- Bulk updates skip before/after actions, which means that PaperTrail::Versions were not being created.

P4-3888 - Swap from bulk updates so that PaperTrail::Versions are made

---

app/controllers/diagnostics_controller.rb
app/services/diagnostics/move_inspector.rb
app/services/diagnostics/per_inspector.rb
spec/services/diagnostics/move_inspector_spec.rb

Previously, PII was only available in non-production environments, this change makes it so that applications with the `diagnostics.pii` scope (will only be internal) can view the PII.

P4-3888 - lock diagnostic PII behind a scope

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

P4-3876
- Currently, when a lockout move only has 1 active journey, the receiving location cannot see the move in their Incoming moves tab.

P4-3876 - Fix issue with move finder and single active journey lockout moves

---

.github/workflows/auto-merge.yml

This will automatically merge minor/patch dependabot dependency upgrades once they pass all merge criteria, to reduce the amount of open PRs.

Add Dependabot auto-merge from frontend

---

Gemfile.lock

Reverts ministryofjustice/hmpps-book-secure-move-api#1953
This version of doorkeeper is throwing an error when no scopes are specified

Revert "Bump doorkeeper from 5.5.4 to 5.6.0"

---

app/serializers/important_events_serializer.rb
spec/serializers/important_events_serializer_spec.rb

P4-3967
- The frontend needs access to event occurred_at to ensure that PerHandovers are correctly displayed

Fix frontend error with occurredAt.split

---

app/models/move.rb
spec/services/moves/updater_spec.rb

P4-3937
- This is a temporary fix to allow the dates of allocation moves to be changed, in the future this will be re-added and the date of the allocation will be able to be changed as a whole.

[P4-3937] Temporarily allow Moves within an Allocation to have their dates changed

---

app/models/generic_event/journey_admit_to_reception.rb
app/models/generic_event/journey_arrive_at_outer_gate.rb
app/models/generic_event/journey_exit_through_outer_gate.rb
app/models/generic_event/journey_person_leave_vehicle.rb
app/models/generic_event/journey_ready_to_exit.rb

P4-3769
- We are getting false positive alerts in Sentry

Check if event trigger is a dry run to remove false positive sentry logging

---

app/models/move.rb
spec/models/move_spec.rb

P4-3948
- Currently, if a move has a proposed journey and the move date is changed, the date doesn't update in the frontend, because it displays the journey's date.

[P4-3948] Change proposed journey dates when move date is changed

---

app/serializers/v2/profiles_serializer.rb
spec/serializers/v2/profiles_serializer_spec.rb

P4-3998
- As part of the incomplete PER work, the frontend requires this field to know which text to show.

[P4-3998] Include requires_youth_risk_assessment in ProfilesSerializer

---

app/serializers/v2/profiles_serializer.rb
app/serializers/youth_risk_assessments_serializer.rb
spec/serializers/v2/profiles_serializer_spec.rb
spec/serializers/youth_risk_assessments_serializer_spec.rb

P4-3998
- Frontend needs to know the YRA status to correctly display the incomplete PERs text

[P4-3998] Include youth_risk_assessment in ProfilesSerializer

---

app/models/move.rb
spec/requests/api/generic_events_controller_create_move_events_spec.rb

P4-3862
- We have allowed users to change move dates, but as soon as any other event is added, the move date reverts back to the original date.

[P4-3862] Fix move date being reverted to original date

---

app/controllers/api/generic_events_controller.rb
config/routes.rb
spec/requests/api/generic_events_controller_show_spec.rb
spec/swagger/swagger_doc_v2.yaml
swagger/v2/get_event_responses.yaml

P4-3910
- Currently, when an event is added via BaSM frontend, we send a notification to the suppliers containing the event id, but they have no way of directly getting the event details from us.

[P4-3910] Add new endpoint: GET /events/:event_id

---

.circleci/config.yml
spec/requests/api/moves_controller_sorting_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/locations/finder_spec.rb
spec/services/moves/finder_spec.rb

P4-3947
- Wiremock, postgres and base image versions in ci pipeline
- Postgres 10 support is being removed, update is required
- Doesn't change code but until DBs in cloud platform are upgraded, ci and deployed applications will be running against differing versions of postgres

P4 3947 upgrade postgres

---

app/controllers/api/moves_controller.rb
app/controllers/api/v2/moves_actions.rb
app/models/move.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/moves_serializer.rb
app/validators/date_validator.rb
db/migrate/20230119131112_add_recall_date_to_moves.rb
db/schema.rb
spec/factories/move.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb
spec/serializers/v2/move_serializer_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
swagger/v2/move.yaml
swagger/v2/patch_move.yaml

Add recall date field to moves.
[P4-P4-3970](https://dsdmoj.atlassian.net/browse/P4-3970)
- Added recall_date field to Move model
- This field is being moved to the booking form instead of the PER. Only police are able to provide this information, and it's easier to restrict access to sections of the booking form than the PER.
- The code expects the recall_date column to exist in the moves table so the migrations should be run prior to deployment
- Changes an API that is used in production - suppliers need to be kept informed

feat: Add recall_date field to moves [P4-3970]

---

app/workers/requeue_unsent_notifications_worker.rb
lib/tasks/requeue_unsent_notifications.rake
spec/lib/tasks/requeue_unsent_notifications_spec.rb
spec/workers/requeue_unsent_notifications_worker_spec.rb

Sometimes Sidekiq drops messages. This tasks checks for notifications that were created more than an hour ago (to give Sidekiq a chance to get to them) but less than a day ago (to avoid a torrent of old notifications when we first run this) and retries scheduling the job to send that notification.
[P4-3993]
[P4-3993](https://dsdmoj.atlassian.net/browse/P4-3993)
- Added requeue_unsent_notifications Rake task
- Sidekiq sometimes drop messages, meaning that suppliers sometimes do not receive notifications about moves. We can check for messages that have had no delivery attempts and recreate the job, to give Sidekiq another chance to pick them up.
[P4-3993]: https://dsdmoj.atlassian.net/browse/P4-3993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

chore: Add rake task for requeueing notifications with no delivery attempts

---

app/workers/requeue_unsent_notifications_worker.rb
spec/workers/requeue_unsent_notifications_worker_spec.rb

[P4-3993](https://dsdmoj.atlassian.net/browse/P4-3993)
- Added logging to the RequeueUnsentNotificationsWorker
- It will help with debugging and enable us to verify that the worker is doing what it said it would do
[P4-3993]: https://dsdmoj.atlassian.net/browse/P4-3993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add logging to RequeueUnsentNotificationsWorker

---

app/jobs/prepare_base_notifications_job.rb
app/jobs/prepare_move_notifications_job.rb
spec/jobs/prepare_generic_event_notifications_job_spec.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/jobs/prepare_person_escort_record_notifications_job_spec.rb
spec/jobs/prepare_person_notifications_job_spec.rb
spec/jobs/prepare_profile_notifications_job_spec.rb
spec/jobs/prepare_youth_risk_assessment_notifications_job_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

We don't send notifications if the move has not yet been approved. This means that sometimes there is no create_move notification. We have decided to always send this notification at the point when we start sending notifications to the subscriber, so at that point we create one and send it if it doesn't yet exist.
[P4-4118](https://dsdmoj.atlassian.net/browse/P4-4118)
- create_move notifications are now always sent out before any others
- Serco asked for it
- We need to liaise with the suppliers to make sure this is what they want and that it won't break anything
[P4-4118]: https://dsdmoj.atlassian.net/browse/P4-4118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Always send create_move notification

---

app/controllers/api/v2/moves_actions.rb
app/jobs/update_move_nomis_data_job.rb
spec/jobs/update_move_nomis_data_job_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

When a move is created we update the person's image from NOMIS. Sometimes this times out or fails, meaning that a 502 response is returned without JSON data containing the newly created move's ID.
To avoid this, we now queue up a job to update the person's image asynchronously instead, and after that is done we send an update_move notification.
[P4-4122](https://dsdmoj.atlassian.net/browse/P4-4122)
- When a move is created we now update the person's image asynchronously
- Suppliers are sometimes encountering a 502 response code and not receiving the ID of a move which was created successfully, meaning that they have no reference to the move and are therefore unable to track it or make any updates to it
- Changes the behaviour of the …

feat: Update person data from NOMIS asynchronously

---

app/models/move.rb
spec/models/move_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb

The validation on the event allows the same to and from location for lockout moves, but the validation on the move itself also needed relaxing in the same way.
[P4-4128](https://dsdmoj.atlassian.net/browse/P4-4128)
- Relaxed validation for lockout moves to allow identical to and from location
- GeoAmey were having trouble redirecting moves to the same location
[P4-4128]: https://dsdmoj.atlassian.net/browse/P4-4128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Disable DifferentToFromLocationValidator for lockouts

---

app/controllers/api_controller.rb
db/migrate/20230323145412_add_body_to_access_logs.rb
db/schema.rb
spec/factories/access_logs.rb

P4-4102
- POST searches without the body don't provide enough information about what is being looked at
-
-

P4-4102 add body to access log table

---

app/controllers/api_controller.rb
db/migrate/20230323145412_add_body_to_access_logs.rb

P4-4102
- as_json the request.body for access log table
- Currently we get an object reference
-
-

P4-4102 Store request body as json

---

app/controllers/api/moves_controller.rb
spec/requests/api/moves_controller_create_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_role_access_spec.rb
spec/requests/api/moves_controller_sorting_spec.rb
spec/requests/api/moves_controller_update_cancellation_reason_spec.rb
spec/requests/api/moves_controller_update_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

[P4-4131](https://dsdmoj.atlassian.net/browse/P4-4131)
- Implement idempotency for moves controller on create and update
- This should help suppliers to understand if they have sent a duplicate request and if the original request was processed or not
- This could potentially cause suppliers to receive a 422 response code if they aren't sending an idempotency key header, but we have not detected any requests missing that header
- If suppliers are sending different requests but with the same idempotency key they could start receiving a 409 response code where they weren't before, but we do not anticipate this being an issue if they are using the system correctly
[P4-4131]: https://dsdmoj.atlassian.net/browse/P4-4131?atlOrigin=eyJpIjoiNWR …

fix: Make the moves controller idempotent for create and update

---

.circleci/config.yml

- Upgrade CircleCI Slack orb to hopefully fix the error at the end of production deployments
- In the hope that it will stop it erroring out when it tries to send the Slack notification after deploying to production

Upgrade CircleCI Slack orb

---

config/initializers/sentry.rb

NA
- hmpps-book-a-secure-move-api currently consumes ~10% of the overall MoJ quota. This change will reduce the consumption to ~1%. Reducing the risk of reaching capacity and losing access to Sentry features.
NA
- Low risk, only affects Transaction Sampling Rates in Sentry

Reduce Sentry Transaction Sampling from 10% to 1%

---

app/serializers/v2/moves_serializer.rb
spec/serializers/v2/moves_serializer_spec.rb
swagger/v2/moves_include_parameter.yaml

[P4-4147](https://dsdmoj.atlassian.net/browse/P4-4147)
- It was causing a 500 server error
[P4-4147]: https://dsdmoj.atlassian.net/browse/P4-4147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Get timeline events using correct method

---

.circleci/config.yml

- Removed dev deploy step in build config
- The environment has been scrapped because we don't use it, and it was causing the build to fail on main

ci: Delete dev environment from build config

---

.circleci/config.yml

[P4-4193](https://dsdmoj.atlassian.net/browse/P4-4193)
- Push container images to quay.io in addition to ECR
- We are moving to a more DPS-like build pipeline which will need the image to be in Quay instead of ECR, but for now we will push it to both registries to facilitate a seamless transition
[P4-4193]: https://dsdmoj.atlassian.net/browse/P4-4193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: Build and push the image to quay.io

---

app/models/move.rb
spec/factories/location.rb
spec/requests/api/moves_controller_create_v2_spec.rb
swagger/v1/move_type_attribute.yaml

[MAP-21](https://dsdmoj.atlassian.net/browse/MAP-21)
- Requested addition
-
-
[MAP-21]: https://dsdmoj.atlassian.net/browse/MAP-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-21 Add Approved premises move type

---

Dockerfile
README.md
docs/pull_request_template.md
spec/rails_helper.rb

[MAP-26]
- Build Swagger docs during container build
- We are no longer in direct control of the container build step, so this is the easiest way to make sure the API docs are in the image

[MAP-26] Generate swagger docs during container build

---

config/initializers/sidekiq.rb

MAP-26
- Disable strict args in Sidekiq
- Sidekiq >= 7 throws an error for complex args. We pass in dates which seems to work OK so it seems simpler to just disable the error.

[MAP-26] Allow non-string args for Sidekiq

---

.circleci/config.yml

MAP-26
- Remove ECR cleanup job
- Rename build_quay step to build_image
- We are now only pushing to Quay, not ECR

ci: Remove ECR cleanup job

---

helm_deploy/values-production.yaml

MAP-26
- Added more env vars for Sidekiq jobs
- Reporting jobs were still missing some vars

feat: Add more env vars for reporting jobs

---

helm_deploy/hmpps-book-secure-move-api/values.yaml

MAP-26
- Added missing env var for reports
- Because Sentry alerted us to an error

fix: Add missing environment variable for reports

---

helm_deploy/hmpps-book-secure-move-api/values.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml

MAP-19
- Update reporting bucket config
- Because Terraform has created new secrets for us to use

fix: Update reporting bucket config

---

db/migrate/20230802145421_add_location_indexes_to_moves.rb
db/schema.rb

MAP-84
- Add index on from_location and to_location to moves
- Filtering by to_location and from_location has become an order of magnitude slower since adding the lodgings table and adding the related SQL clauses to the moves finder, so we are adding some indexes to see if that helps.

[MAP-84] Add index on from_location and to_location to moves

---

helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml

- Move ENCRYPTOR_SALT env var to secret
- It's binary and it will confuse the k8s CLI less if it's base64 encoded

Move ENCRYPTOR_SALT env var to secret

---

app/models/generic_event/move_overnight_lodge.rb
db/migrate/20230808150500_add_unique_index_to_lodgings.rb
db/schema.rb

MAP-84
- It will stop duplicate lodgings from being created

Add unique index to lodgings

---

app.json
app/lib/cloud_data/metrics_feed.rb
config/storage.yml
helm_deploy/hmpps-book-secure-move-api/templates/cron_jobs.yaml
helm_deploy/hmpps-book-secure-move-api/templates/deployment_sidekiq.yaml
helm_deploy/hmpps-book-secure-move-api/templates/migration_job.yaml
helm_deploy/hmpps-book-secure-move-api/values.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml

MAP-147
- Use IRSA for AWS S3 access
- The Cloud Platform team are disabling long-lived credentials on 4th Sept 2023

[MAP-147] Use IRSA for AWS S3 access

---

app/workers/feeds/jpc_worker.rb
spec/workers/feeds/feed_worker_spec.rb
spec/workers/feeds/jpc_worker_spec.rb

MAP-319
- Call to_s before formatting JPC feed names
- It was failing with an error

MAP-319: Fix JPC feed

---

helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml

MAP-319
- Ad JPC feed cron jobs
- We want this to run in addition to the analytical platform job

MAP-319: Add JPC feed cron jobs

---

helm_deploy/hmpps-book-secure-move-api/templates/migration_job.yaml

- Make migration job name unique per release
- When the migration pre-hook fails it hangs around, and Helm doesn't want to overwrite it when we rerun the job, so it fails again. Adding a hash generated from the values should make the name unique per release.

ci: Make migration job name unique per release

---

Dockerfile

Pin Bundler to 2.1.4 as 
MAP-359
- Pin Bundler to 2.1.4
- The newest version seems to not work in Docker - some gems are missing from the multi-stage build

[MAP-359] Pin Bundler to 2.1.4 as the newest version seems to not work in Docker

---

app/models/ability.rb
app/models/move.rb
spec/models/ability_spec.rb

MAP-334
- It was fed back to us after demoing the lodgings work to suppliers

Add lodgings into supplier move accessibility check

---

app/models/move.rb
spec/models/move_spec.rb
spec/swagger/swagger_doc_v1.yaml
spec/swagger/swagger_doc_v2.yaml
swagger/v1/move.yaml
swagger/v1/move_cancellation_reason_attribute.yaml
swagger/v2/move.yaml
swagger/v2/patch_move.yaml

MAP-293
- Added incomplete_per as a cancellation reason for moves
- Suppliers have been asked by PECS to reject moves with an incomplete PER, but they want it to be clear why they have cancelled the move so that they are not penalised for unnecessary cancellations

MAP-293: Add `incomplete_per` as a cancellation reason for moves

---

CHANGELOG.md

Generated changelog for v3.40.0

---

app/models/move.rb
spec/models/move_spec.rb

MAP-480
- Rewrite query in move for_supplier method
- We were getting 500 error responses when we deployed the app

[MAP-480] Fix error in move for_supplier method that was causing 500 errors

---

app/services/moves/finder.rb
spec/services/moves/finder_spec.rb

MAP-340
- Only show moves on the incoming/outgoing pages relative to the journey, if there is both a lodge and journey
- If the journey is booked for a different location to the lodge then we assume that the journey is correct and the lodge isn't, as it's more up-to-date
- Possible performance impact - we will test for this before going live

MAP-340: Let journey take precedence over lodge when filtering

---

app/controllers/api_controller.rb
spec/requests/api/access_logs_spec.rb

MAP-582
- Log correct response codes in access logs
- Sometimes they show up as 200 when they're actually error responses

MAP-582: Log correct response codes in access logs

---

app/workers/feeds/all_worker.rb
spec/workers/feeds/all_worker_spec.rb

[MAP-898]
- Send the same data that we send to JPC to the Analytical Platform
- To make sure they get enough data to build up a full snapshot and not miss any records
[MAP-898]: https://dsdmoj.atlassian.net/browse/MAP-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Send the same data we send to JPC to the Analytical Platform

---

Gemfile
Gemfile.lock

It's probably causing the errors seen in Staging
MAP-809
- Revert Doorkeeper upgrade
- Staging is not working

fix: Downgrade Doorkeeper

---

spec/requests/api/moves_controller_sorting_spec.rb
spec/services/allocations/finder_spec.rb
spec/services/locations/finder_spec.rb
spec/services/moves/finder_spec.rb

MAP-809
- As we can't reliably test the case-sensitivity in a cross-platform way, let's make the tests case-insensitive so that they pass on both platforms
- The collation on a Mac is different from on a Linux machine so Postgres will sort things differently and the tests fail on Mac

Fix sort order tests on Mac

---

app/controllers/subject_access_requests_controller.rb
spec/requests/api/subject_access_requests_controller_show_spec.rb

SAR is meant to throw a 403 if the role is missing

SAR - Throw 403 when missing role

---

app/controllers/api/lodgings_controller.rb
spec/requests/api/lodgings_controller_update_spec.rb

MAP-958
- The dates that were being assigned previously were incorrect

MAP-958: Assign the correct dates to future lodging LodgingUpdate events

---

reports/monthly-per/duplicates_per_month.sql
reports/monthly-per/incompletePerStatus.sql
reports/monthly-per/per_stats.sql

MAP-531
- Users reports an issues with a mismatch in numbers between tabs. This was a misunderstanding, however during investigation found that duplicates were being produced in the "Section Progress" tab. This has been fixed.
- Users wanted the ability to filter "Section Progress" tab for moves made by suppliers from court. 
- Efficiency improvements to SQL queries. 
- The scripts will be used in k8s automation of report production and sending.

MAP-531 Monthly incomplete PER report

---

app/controllers/api/reference/locations_controller.rb
app/serializers/locations_serializer.rb
app/services/locations/finder.rb
db/migrate/20240430143853_add_extradition_capable_to_locations.rb
db/schema.rb
spec/models/location_spec.rb
spec/requests/api/reference/locations_controller_spec.rb
spec/serializers/locations_serializer_spec.rb
spec/services/locations/finder_spec.rb
spec/services/locations/importer_spec.rb
swagger/v1/location.yaml

[MAP-1029]
- Added `extradition_capable` flag to Location model
- To indicate that a location can be used as a destination for extradition moves
- Database migration required
- Changes an API that is used in production (Serco may experience issues if they are not expecting this field)
[MAP-1029]: https://dsdmoj.atlassian.net/browse/MAP-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-1029] Add extradition_capable flag to Locations

---

app/models/move.rb
spec/models/move_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
swagger/v1/move_type_attribute.yaml

[MAP-1035]
- Added `extradition` move type, which is only allowed if `extradition_capable` is true for `to_location`.
- To allow extradition moves to be created
[MAP-1035]: https://dsdmoj.atlassian.net/browse/MAP-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-1035] Add `extradition` move type

---

app/controllers/api/flight_details_controller.rb
app/models/flight_details.rb
app/models/move.rb
app/serializers/flight_details_serializer.rb
app/serializers/v2/move_serializer.rb
config/routes.rb
db/migrate/20240502112955_create_flight_details.rb
db/schema.rb
spec/factories/flight_details.rb
spec/models/flight_details_spec.rb
spec/models/move_spec.rb
spec/requests/api/flight_details_controller_create_spec.rb
spec/requests/api/flight_details_controller_index_spec.rb
spec/requests/api/flight_details_controller_update_spec.rb
spec/requests/api/moves_controller_show_v2_spec.rb
spec/serializers/flight_details_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
swagger/v1/flight_details.yaml
swagger/v1/get_flight_details_responses.yaml
swagger/v1/patch_flight_details_responses.yaml
swagger/v1/post_flight_details_responses.yaml

[MAP-1038]
- Add FlightDetails model and controller
- FlightDetails can also be included when retrieving a move
- We need to be able to create and view the flight details in the frontend
[MAP-1038]: https://dsdmoj.atlassian.net/browse/MAP-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAP-1038]: https://dsdmoj.atlassian.net/browse/MAP-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-1038] Add FlightDetails model and controller

---

reports/monthly-incomplete-per/01-config.yaml
reports/monthly-per/incompletePerStatus.sql

MAP-1040
- Users want to be able to see and filter moves that include court locations.
- "supplier_from_court" column no longer required as users can filter the same conditions using a combination of the "created_by" and "from_location_court" columns.

Map 1040 - Add court columns to incomplete per report

---

helm_deploy/hmpps-book-secure-move-api/templates/reports/daily-ipt/01-daily-ipt-config.yaml
helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-court-moves/01-weekly-cancelled-court-moves-config.yaml
helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml

MAP-975
- Users want to be able to see reasons for moves being cancelled.

Modified daily-IPT report SQL query to add cancellation reasons

---

app/jobs/prepare_base_notifications_job.rb
app/jobs/prepare_lodging_notifications_job.rb
app/models/generic_event/move_redirect.rb
app/models/move.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/move_spec.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

[MAP-322]
- Where the receiving location is operated by another supplier, we now send them a `notify_move` notification at the same time as we send the departing supplier a `create_move` notification
- Any subsequent `update_move` notifications will go to both suppliers
- A `MoveRedirect` which results in the move becoming cross-deck will also result in a `notify_move` notification being sent to the receiving supplier
- A `MoveRedirect` which results in the move ceasing to be cross-deck will result in a `disregard_move` notification being sent to any supplier that previously received a `notify_move` notification
- So that the receiving supplier can add it to their systems to be ready for when they take over the move
[MAP-322]: …

feat: Send notify_move notification to cross-deck supplier

---

app/jobs/prepare_base_notifications_job.rb
app/jobs/prepare_lodging_notifications_job.rb
app/models/generic_event/move_redirect.rb
app/models/move.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/move_spec.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb

This reverts commit a08000838b2cd10aa3d99acde3d4a290ee5fe898.
GeoAmey have concerns about our implementation so we will roll back for now. Also the `disregard_move` notification doesn't seem to be firing.
[MAP-322]
[MAP-322]: https://dsdmoj.atlassian.net/browse/MAP-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "feat: Send notify_move notification to cross-deck supplier (#2266)"

---

app/controllers/api/journey_events_controller.rb
app/models/generic_event/journey_change_vehicle.rb
app/models/generic_event/journey_start.rb
app/models/journey.rb
spec/models/generic_event/journey_change_vehicle_spec.rb
spec/models/generic_event/journey_start_spec.rb
spec/models/journey_spec.rb
spec/requests/api/journey_events_controller_start_spec.rb
swagger/v1/post_journey_start.yaml

[MAP-972]
- Add vehicle_depot to Journey and JourneyStart & JourneyChangeVehicle events
- We would like suppliers to send us info on the vehicle depot so that we can use this in reports
[MAP-972]: https://dsdmoj.atlassian.net/browse/MAP-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-972] Add vehicle_depot to Journey and JourneyStart & JourneyChangeVehicle events

---

app/jobs/prepare_base_notifications_job.rb
app/jobs/prepare_lodging_notifications_job.rb
app/models/generic_event/move_redirect.rb
app/models/move.rb
spec/jobs/prepare_move_notifications_job_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/move_spec.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

[MAP-322]
Where the receiving location is operated by another supplier, we now send them a `cross_supplier_move_add` notification at the same time as we send the initial supplier a `create_move` notification. This means that they can add it to their systems to be ready for when they take over.
When a MoveRedirect causes a move to no longer be cross-deck, we send a `cross_supplier_move_remove` notification to any supplier that previously received a `cross_supplier_move_add` notification, to let them know that they no longer need to be aware of this move.
While a move is cross-deck, update and update status notifications will be sent to the receiving supplier as `cross_supplier_move_update` and `cross_supplier_move_update_status` respectively.
So that the receiving …

[MAP-322] Send cross_supplier_move_* notification to cross-deck supplier

---

app/jobs/prepare_base_notifications_job.rb
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml
spec/jobs/prepare_move_notifications_job_spec.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

[MAP-322]
- Added FEATURE_FLAG_CROSS_DECK_NOTIFICATIONS_SUPPLIERS environment variable. It should be set to a comma-separated list, e.g. "geoamey,serco".
- The suppliers aren't ready for this yet. We need to at least wait for them to ignore these notifications before we release it.
[MAP-322]: https://dsdmoj.atlassian.net/browse/MAP-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Hide cross-deck notifications behind feature flag

---

app/controllers/api/generic_events_controller.rb
app/controllers/api/move_events_controller.rb
app/jobs/prepare_base_notifications_job.rb
app/models/generic_event/move_redirect.rb
app/models/move.rb
helm_deploy/values-staging.yaml
spec/jobs/prepare_move_notifications_job_spec.rb
spec/models/generic_event/move_redirect_spec.rb
spec/models/move_spec.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/requests/api/generic_events_controller_create_move_events_spec.rb
spec/requests/api/move_events_controller_redirect_spec.rb
spec/requests/api/moves_controller_create_v2_spec.rb
spec/requests/api/moves_controller_update_v2_spec.rb

[MAP-322]
- Stop duplicating cross-deck notifications
- The notifications were being sent when the even is triggered, but all of the events get triggered again and again for an eventable so it has to happen outside of the trigger so that it only happens once.
[MAP-322]: https://dsdmoj.atlassian.net/browse/MAP-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-322] Stop duplicating cross-deck notifications

---

CHANGELOG.md

- Generated changelog up to v3.48.0
- So that we and our suppliers can see what changed in which version of the API

Generated changelog for v3.48.0

---

app/lib/nomis_client/rollcount.rb
app/services/populations/defaults_from_nomis.rb
docker-compose.yml
spec/fixtures/files/nomis/get_rollcount_200.json
spec/lib/nomis_client/rollcount_spec.rb
spec/services/populations/defaults_from_nomis_spec.rb

MAP-1363
- The old endpoint is deprecated and will shortly be removed.
- Changes where we get roll count data from, regression testing required

Map 1363 move basm api to use new roll count

---

app/services/moves/exporter.rb
spec/services/moves/exporter_spec.rb

MAP-1380
- Users want to be able to see when a move had been cancelled.

MAP-1380 Made changes to include a 'cancelled_at' column to the download showing the time when the move had been cancelled

---

app/controllers/api/journeys_controller.rb

[MAP-1442]
- Make sure that render is only called once
- Sentry alerted us to a bug: https://ministryofjustice.sentry.io/issues/5655896045/?alert_rule_id=975211&alert_timestamp=1722296566600&alert_type=email&environment=production&notification_uuid=f2f8bd96-912c-4225-939e-a0a4426d69e7&project=2014776
[MAP-1442]: https://dsdmoj.atlassian.net/browse/MAP-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-1442] fix double render error

---

app/services/moves/exporter.rb

Get the generic events with each batch of moves, and search them in memory instead of doing a SQL query for each one.
MAP-1479

[MAP-1479] Improve performance of CSV download

---

app/models/move.rb
app/models/profile.rb
spec/models/move_spec.rb
spec/models/profile_spec.rb

MAP-1485
- Analytical platform have requested it

MAP-1485 - Add PER/YRA id to move/profile feeds

---

Dockerfile

MAP-370
- Revert using JSON args in dockerfile as they don't work with env vars
- Deployment failed

MAP-370: Revert using JSON args in dockerfile as they don't work with env vars

---

config/application.rb
config/initializers/new_framework_defaults_7_1.rb
config/initializers/sidekiq.rb
config/secrets.yml
spec/requests/api/extradition_flight_controller_index_spec.rb
spec/serializers/lodging_serializer_spec.rb
spec/serializers/lodgings_serializer_spec.rb

MAP-1477
- Enable most Rails 7.1 defaults
- Get rid of the unnecessary guff that gets printed to the console during tests
- To continue with the Rails 7.1 upgrade and get ready for 7.2
- To make it easier to spot deprecation errors logged during test runs
- Some of these changes needed to only be deployed after all pods were running 7.1 (which they now are)

Rails 7.1 pt2

---

app/services/assessment_questions/importer.rb
spec/services/assessment_questions/importer_spec.rb

[MAP-1565](https://dsdmoj.atlassian.net/browse/MAP-1565)
Here we add a new assessment question: 
`Civil disorder offender`
See [Frontend PR for screenshots](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/2353)
To support the latest BaSM Framework [v2.5.1](https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks/releases/tag/v2.5.1)
- The following rake task **must** be run when the deployment is complete. [Docs](https://dsdmoj.atlassian.net/wiki/spaces/MAP/pages/4107239526/Process+for+making+a+frameworks+change)
`bundle exec rake frameworks:populate_data`
[MAP-1565]: https://dsdmoj.atlassian.net/browse/MAP-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1565 Add Civil disorder to the list of assessment questions

---

helm_deploy/REPORTS.md

MAP-1676
- Document beforeafter SQL function
- It needs to exist in the DB but it wasn't actually defined in the source code or documented anywhere

MAP-1676: Document beforeafter SQL function

---

app/models/journey.rb
spec/factories/journeys.rb
spec/models/journey_spec.rb
spec/requests/api/journeys_controller_update_spec.rb
spec/serializers/journey_serializer_spec.rb
spec/serializers/journeys_serializer_spec.rb

[MAP-1645](https://dsdmoj.atlassian.net/browse/MAP-1645)
I have added `vehicle_depot` to the Journey analytics feed (`#for_feed`)
So that `depot` will be available on the analytics platform
[MAP-1645]: https://dsdmoj.atlassian.net/browse/MAP-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1645: Send van depots to the analytical platform

---

Gemfile
Gemfile.lock

[MAP-1682](https://dsdmoj.atlassian.net/browse/MAP-1682)
Revert the [commit to upgrade the doorkeeper gem](https://github.com/ministryofjustice/hmpps-book-secure-move-api/commit/40666eb342f26b1c84e87a3c6cff510db9686525)
Authentication on staging is broken. User logs in and random pages raise a 401. No obvious solution
[MAP-1682]: https://dsdmoj.atlassian.net/browse/MAP-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAPI-1682 Revert doorkeeper upgrade

---

.circleci/config.yml

[MAP-1662](https://dsdmoj.atlassian.net/browse/MAP-1662)
Remove veracode policy scan
It's unclear when this last run successfully and the team are confident that we have other tools in place to do the job
[MAP-1662]: https://dsdmoj.atlassian.net/browse/MAP-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1662 Remove veracode policy scan

---

.github/workflows/security_trivy.yml

[MAP-1757](https://dsdmoj.atlassian.net/browse/MAP-1757)
I have upgraded to Trivy scan v1
Failing on v0.5 [Security trivy dependency check · ministryofjustice/hmpps-book-secure-move-api@43cdb35](https://github.com/ministryofjustice/hmpps-book-secure-move-api/actions/runs/11548024715)
Working on v1 https://github.com/ministryofjustice/hmpps-book-secure-move-api/actions/runs/11551365189
[MAP-1757]: https://dsdmoj.atlassian.net/browse/MAP-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade to Trivy Scan v1

---

.github/workflows/auto-merge.yml
.github/workflows/codeql-analysis.yml

[MAP-1758](https://dsdmoj.atlassian.net/browse/MAP-1758)
I have:
- upgraded CodeQL to use v3 and v4 actions/checkout
- upgraded Dependabot Auto Merge PR to use v4 actions/checkout
- CodeQL v1 is deprecated
- actions/checkout v4 uses an up to date node version 
[MAP-1758]: https://dsdmoj.atlassian.net/browse/MAP-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-1758] Upgrade CodeQL and Dependabot auto-merge

---

README.md
docker-compose.yml

[MAP-1621](https://dsdmoj.atlassian.net/browse/MAP-1621)
Updates the docker-compose file to build a local production environment. 
Adds additional instructions to the README.
The docker-compose file wasn't working.
[MAP-1621]: https://dsdmoj.atlassian.net/browse/MAP-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1621 Update docker-compose to build a local production environment

---

helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml

[MAP-1812](https://dsdmoj.atlassian.net/browse/MAP-1812)
Added `SELECT DISTINCT` to remove duplicate rows from report.
Tested locally and produced a sample report with 3398 rows. With duplicates removed, that became 2200.
For a large dataset, DISTINCT is not very efficient, but with a sample size of a few thousand rows that is run as an async task, it should be fine.
Duplicates are making it difficult for PECS and prisons to trust the data in the report
[MAP-1812]: https://dsdmoj.atlassian.net/browse/MAP-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Select DISTINCT to remove duplicates from report

---

app/services/locations/finder.rb

[MAP-304](https://dsdmoj.atlassian.net/browse/MAP-304)
Eager load location#suppliers to improve performance
The above ticket is about performance issues when loading Location reference data. I noticed an n+1 query when the list is not filtered by supplier_id. This wasn't very serious because Locations are cached in Redis by the frontend and not loaded multiple times.
[MAP-304]: https://dsdmoj.atlassian.net/browse/MAP-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-304 Eager load location#suppliers to improve performance

---

db/migrate/20241113160043_add_index_to_person_id.rb
db/schema.rb

[MAP-1837](https://dsdmoj.atlassian.net/browse/MAP-1837)
Index profiles#person_id
Loading person.profiles is very slow and could be the cause of the SAR bottleneck
[MAP-1837]: https://dsdmoj.atlassian.net/browse/MAP-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1837 Index profiles#person_id to improve SAR performance

---

helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml
lib/tasks/access_logs.rake
spec/factories/access_logs.rb
spec/lib/tasks/access_logs_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-1781
Adds a daily cronjob to delete stale Access Logs. 
DELETE can be a very expensive operation, so we do this in batches of 1000.
200k Access Logs are created every day. 
We use them for debugging production issues, so it should be okay to remove anything older than three months.

MAP-1781 Cleanup Access Logs more than 3 months old

---

Gemfile
Gemfile.lock
config/application.rb

[MAP-1672](https://dsdmoj.atlassian.net/browse/MAP-1672)
Pin Rails to 8.0.0 to prevent auto-upgrade to 8.1
Revert to 7.1 defaults until production has proven to be stable
[Issues raised on PR](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/2409)
[MAP-1672]: https://dsdmoj.atlassian.net/browse/MAP-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1672 Rails 8 PR comments

---

helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml

https://dsdmoj.atlassian.net/browse/MAP-1812
Resolve duplicates on the Weekly Cancellation report.
Update the SQL to report on a journey's to/from location, rather than the move's to/from location.
Recipients of this report noticed duplicate rows. Digging in, we discovered that the report is correctly writing a row for each move's journey, but is displaying the move's to/from location. To the end user, these rows look like duplicates, because the to/from location is repeated for each journey.
We have also learned that suppliers may be cancelling a journey that has the wrong location and creating a new one when, perhaps, they should be updating the journey with the correct location.

MAP-1812 Resolve duplicates on the Weekly Cancellation report

---

Gemfile
Gemfile.lock

- rubocop-govuk was pinned to a pre-release commit - new version has been released.

Update rubocop-govuk 

---

app/controllers/api/moves_controller.rb
app/models/move.rb
app/services/moves/exporter.rb
config/environments/development.rb
db/migrate/20241125114943_add_index_to_generic_events_type.rb
db/schema.rb
helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-court-moves/01-weekly-cancelled-court-moves-config.yaml
helm_deploy/hmpps-book-secure-move-api/templates/reports/weekly-cancelled-moves/01-weekly-cancelled-moves-config.yaml
spec/models/move_spec.rb
spec/requests/api/moves_controller_csv_spec.rb
spec/services/moves/exporter_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-530
Here, we
- Add 'Group 1, cancellation fields' to the CSV Download (weekly moves summary)
- Bring the Weekly Cancellation Reports (Monday morning cron job) inline with the CSV Download
- Add an index to `generic_events#type` to improve performance
- Enable bullet logging in the development console to help resolve n+1 queries
- Users have reported that results from CSV Downloads and Weekly Cancellation Reports don't match up.
- The cutoff `difference` (time between the move date and cancellation of the move) is now calculated from 6am on the day of the move in all reports
- A move is now `billable` if any of the journeys are `billable`
- The acceptance criteria for Group 2 needs clarification (how to map column names to journey events) and will be …

MAP-530 Add cancellation fields to CSV Download

---

helm_deploy/values-production.yaml

We added this to the helm chart but never enabled it, so it is actually still using the original manually-deployed preprod refresh script
MAP-1975

MAP-1975: Enable preprod refresh script via Helm chart

---

app/models/generic_event.rb
app/models/generic_event/per_suicide_and_self_harm.rb
spec/factories/generic_event.rb
spec/models/generic_event/per_suicide_and_self_harm_spec.rb

[MAP-1917](https://dsdmoj.atlassian.net/browse/MAP-1917)
Add a new GenericEvent `PerSuicideAndSelfHarm` with classification `suicide_and_self_harm`
Suppliers need to submit a PerSuicideAndSelfHarm via the API so it can be displayed as an important event in the move's timeline.
Documentation update: [wiki](https://github.com/ministryofjustice/hmpps-book-secure-move-api/wiki/Person-Escort-Record-Events#persuicideandselfharm)
[MAP-1917]: https://dsdmoj.atlassian.net/browse/MAP-1917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1917 Add a PerSuicideAndSelfHarm event

---

helm_deploy/hmpps-book-secure-move-api/templates/preprod-refresh/08-refresh-versions-cronjob.yaml

So that the name doesn't clash with the manually deployed one, or with any parallel Helm deployment if one should exist
MAP-1975

MAP-1975: Use unique name for preprod versions job

---

helm_deploy/hmpps-book-secure-move-api/templates/preprod-refresh/07-preprod-refresh-versions-script.yaml

When truncated it ended with a hyphen which made k8s have a right moan
MAP-1975

MAP-1975: Shorten name for preprod refresh versions script

---

app/models/generic_event/per_suicide_and_self_harm.rb
spec/models/generic_event/per_suicide_and_self_harm_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-1917
Adds `source` to the PerSuicideAndSelfHarm attributes
To add `details.source` to the event and enable frontend display
"source": {
"option": "Third Party",
"details": "PC Plod at Nuneaton"
"comments": "Lorem ipsum",
"observations": "Lorem ipsum"
}

MAP-1917 Add `source` to the PerSuicideAndSelfHarm attributes

---

helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml

MAP-1976: Remove old live-1 URLs

---

helm_deploy/values-production.yaml

https://dsdmoj.atlassian.net/browse/MAP-1975
Currently, there are 165 million records in the versions table and the migrate script is not working.
Rather than debugging the script, it makes more sense to disable it as there is no use case for Papertail version history on pre-prod.

Avoid migrating audit-trail data to pre-prod

---

app/services/moves/exporter.rb
db/migrate/20250109102311_add_index_title_to_framework_flags.rb
db/schema.rb
spec/services/moves/exporter_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-1971
Here we 
- restore the framework flags to the CSV downloads  
- add support for flags generated by the `Youth Risk Assessment`
- index the `framework_flags#title` to support `SELECT DISTINCT ON`
The ticket is to add 4 individual framework flags to the CSV download but, having looked at the code, there was a prior requirement to display all the framework flags. Due to performance issues, this was hidden behind a feature flag. It seems like a good opportunity to restore the original behaviour and resolve the performance issues.
- [original ticket to add the framework flags](https://dsdmoj.atlassian.net/browse/MAP-346)
- [ticket to disable the framework flags](https://dsdmoj.atlassian.net/browse/MAP-511)

Restore framework flags to CSV downloads

---

app/services/moves/exporter.rb

[MAP-1971](https://dsdmoj.atlassian.net/browse/MAP-1971)
Added eager loading to improve CSV download performance
Benchmark for 4000 moves (in seconds)
`Benchmark.measure {  Moves::Exporter.new(Move.where.not(date: nil).limit(4000)).call }.total`
Before enabling framework_flags:
10.715672
After enabling framework_flags:
11.017437
After enabling framework_flags and eager loading refactor: 
4.828155
CSV download performance is impaired and the download times out after 30 seconds
[MAP-1971]: https://dsdmoj.atlassian.net/browse/MAP-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend eager loading to improve CSV download performance

---

app/services/subject_access_request.rb

The fields were slightly more buried than originally thought

MAP-1987 - Remove some fields from SAR Locations export

---

Dockerfile

https://dsdmoj.atlassian.net/browse/MAP-2051
Add yaml-dev to satisfy missing libyaml dependency
libyaml-dev has been removed from the Docker image, and the CI pipeline is broken

Add yaml-dev to satisfy missing libyaml dependency

---

helm_deploy/values-preprod.yaml

This reverts commit 5a548ed561772a211c4877c0c749fe727fa0d5ae which prevented access to:
https://hmpps-book-secure-move-api-preprod.apps.cloud-platform.service.justice.gov.uk/health
https://dsdmoj.atlassian.net/browse/MAP-2076

Revert "Prevent prisons access to preprod (#2474)"

---

app/models/generic_event/move_reject.rb
spec/models/generic_event/move_reject_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-2128
Invoke the MoveRejectMailer with `deliver_later` 
Only the Sidekiq instance has access to the NOTIFY env vars, 
so we can't `deliver_now!`

Ensure MoveRejectMailer uses the Sidekiq worker

---

app/mailers/move_reject_mailer.rb
spec/mailer/move_reject_mailer_spec.rb

[MAP-2128](https://dsdmoj.atlassian.net/browse/MAP-2128)
Remove erroneous full-stop from Notify personalisation
It is already in the Notify template
[MAP-2128]: https://dsdmoj.atlassian.net/browse/MAP-2128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove erroneous full-stop that is already in the Notify template

---

app/controllers/api_controller.rb
db/migrate/20250325111637_add_client_ip_to_access_logs.rb
db/schema.rb

[MAP-2308](https://dsdmoj.atlassian.net/browse/MAP-2308)
New feature to save a Client IP address in the Access Logs table 
- Added a new column `access_logs#client_ip`
- Save the Header `X-Client-IP` to the new column
We need to audit users who are accessing BaSM off the VPN 
[MAP-2308]: https://dsdmoj.atlassian.net/browse/MAP-2308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2308 Audit off-network users by storing the Client IP address

---

app/controllers/api_controller.rb
db/migrate/20250325111637_add_client_ip_to_access_logs.rb
db/schema.rb

This reverts commit d51ca2f600e3a65ecbbde40eac5d6318b60c762b.
Disable the long-running indexing of the `access_logs` table

Revert "Save the X-Client-IP to access_logs#client_ip (#2525)"

---

Gemfile
Gemfile.lock

N/A
Removed gems: `logstash-event` and `logstash-logger`
Dependabot flagged a security vulnerability: https://github.com/ministryofjustice/hmpps-book-secure-move-api/security/dependabot/102
There is no indication that we actually use logstash, so removing it.

Remove unused logstash gems

---

.env.example
app/lib/prisoner_search_api_client/base.rb
app/lib/prisoner_search_api_client/location_description.rb
app/models/move.rb
app/serializers/move_serializer.rb
app/serializers/v2/move_serializer.rb
app/serializers/v2/moves_serializer.rb
helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml
spec/fixtures/files/prisoner_search_api/get_prisoner_200.json
spec/fixtures/files/prisoner_search_api/get_prisoner_404.json
spec/lib/prisoner_search_api_client/location_description_spec.rb
spec/models/move_spec.rb
spec/rails_helper.rb
spec/serializers/move_serializer_spec.rb
spec/serializers/v2/move_serializer_spec.rb
spec/serializers/v2/moves_serializer_spec.rb
spec/support/with_hmpps_auth_context.rb
swagger/v1/move_include_parameter.yaml
swagger/v2/move_include_parameter.yaml
swagger/v2/moves_include_parameter.yaml

https://dsdmoj.atlassian.net/browse/MAP-2387
Enables suppliers to checked prisoners are at establishment prior to pick up  
- introduced a Prisoner Search API client to retrieve a locationDescription
- added `prisoner_location_description` to the Move/Moves serializers eg:
```
prisonerLocationDescription: 'Winchester (HMP)` (prisoner is in this prison)
prisonerLocationDescription: 'Outside - released from Winchester (HMP)` (prisoner is not in this prison)
```
Sometimes after a move is booked in advance, the prisoner being moved is temporarily out of the prison on the day of the move. If the move isn’t changed or cancelled, the supplier still arrives to collect which results in wasted journey which we’re still charged for.
- Requires environment variable: `PRISONER_SEARCH_API_BASE_URL` in …

MAP-2387 Add prisoner location to moves api

---

Gemfile
Gemfile.lock

MAP-2348
In `oauth2 v2.0.10`, API responses are parsed into regular Ruby Hash objects, whereas in `oauth2 v2.0.9` they are parsed into SnakyHash::StringKeyed objects.
- 2.0.9 (working): `response['reasonableAdjustments'`] would work even if the actual key was `reasonable_adjustments` thanks to SnakyHash::StringKeyed
- 2.0.10 (broken): `response['reasonableAdjustments']` returns nil when the key is `reasonable_adjustments` because it's a regular Hash
The tests didn't pick this up so we are rolling back the oauth2 upgrade until we can figure out the possible impact.

Rollback oauth2 gem from 2.0.10 to 2.0.9 to restore SnakyHash 

---

app/controllers/api/moves_controller.rb
app/lib/manage_users_api_client/user_email.rb
app/mailers/report_mailer.rb
app/models/generic_event/move_reject.rb
app/workers/moves_export_email_worker.rb
helm_deploy/values-preprod.yaml
helm_deploy/values-production.yaml
helm_deploy/values-staging.yaml
helm_deploy/values-uat.yaml
spec/lib/manage_users_api_client/user_email_spec.rb
spec/mailer/report_mailer_spec.rb
spec/models/generic_event/move_reject_spec.rb
spec/requests/api/moves_controller_csv_spec.rb
spec/workers/moves_export_email_worker_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-2482
Currently, the BaSM front end has a "Download moves (.csv)" link that opens up a csv file.  This ticket is to update the code to deliver the CSV via email.
- Added async CSV export for large datasets (5000+ moves) with async=allow parameter
- Moves are only sent by email if the POST request is made with `async=allow`. 
- Added MovesExportEmailWorker background job
- Added moves_export mailer method
- Refactored UserEmail.get to handle emails directly 
- Large CSV downloads were timing out
- The async=allow parameter ensures existing clients continue working with CSV downloads by default

MAP-2482 Replace csv download with an email version

---

app/lib/prisoner_search_api_client/location_description.rb
app/models/move.rb
spec/lib/prisoner_search_api_client/location_description_spec.rb
spec/models/move_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-2530
Prevents API calls when prison_number is nil/blank.
This was causing 404 "No static resource prisoner" errors in BaSM logs.

MAP-2530 Avoid invalid calls to the Prisoner API

---

spec/requests/api/lodgings_controller_update_spec.rb

Fix flaky lodging event test:
- Use include matcher instead of assuming events are created in a specific order.
The spec occasionally fails due to a race condition when events are created 
simultaneously and don't have predictable ordering.

Fix flaky lodging event test by removing order dependency

---

app/controllers/api/allocations_controller.rb
app/models/allocation.rb
app/services/allocations/updater.rb
spec/requests/api/allocations_controller_update_spec.rb
spec/swagger/swagger_doc_v1.yaml
swagger/v1/allocation.yaml
swagger/v2/move.yaml
swagger/v2/patch_move.yaml

https://dsdmoj.atlassian.net/browse/MAP-2301
When allocation dates change,  propagate `date_changed_reason` to associated moves.
- Update allocation API to accept date_changed_reason parameter
- When allocation date changes, propagate the reason to all associated moves
- Include date_changed_reason in GenericEvent::MoveDateChanged events for moves
When allocation dates are updated (which cascades to all associated moves), we need to capture and maintain the reason consistently across the allocation and all its moves.

MAP-2301 Add date_changed_reason to Allocations

---

app/services/moves/import_people.rb
spec/services/moves/import_people_spec.rb

https://dsdmoj.atlassian.net/browse/MAP-2534
Changed `ImportPeople` service to make individual API calls to AlertsApiClient 
for each person instead of batching all prison numbers in a single request.
The Alerts API expects per-person calls rather than batch operations. 
The previous batch approach was incompatible with the API's design.
There is no evidence that anyone is using this particular endpoint (create move v1)
as the code wouldn't have worked in the current state, but as part of the overall
refactor to move away from NOMIS, we should ensure everything is working.

MAP-2534 Fix ImportPeople to use Alerts API per-person calls

---

Dockerfile

N/A
Add gcompat to Docker manifest
Fixes pg gem libresolv.so.2 error that broke the deployment pipeline

Add gcompat to fix pg gem libresolv.so.2 error

---

app/controllers/api_controller.rb

N/A
Override Rails' default exception mappings for RecordInvalid and 
RecordNotSaved to use :unprocessable_content instead of deprecated 
:unprocessable_entity status code.
To suppress deprecation warnings:
`./home/circleci/project/app/controllers****_controller.rb:358: warning: Status code :unprocessable_entity is deprecated and will be removed in a future version of Rack. Please use :unprocessable_content instead.`

Fix Rack deprecation warnings by overriding Rails' 422 status mappings
